path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

extra = []
def A(s):
    extra.append(s)

# ===== 2000+ ADDITIONAL LINES =====

# Theme-specific CSS overrides
A('<style>')
themes = ['ocean', 'sunset', 'forest', 'neon', 'midnight', 'aurora', 'candy', 'mono']
theme_css = {
    'ocean': ('#0a1628', '#0d1f3c', '"#667eea"', '"#4facfe"', 'rgba(102,126,234,0.2)'),
    'sunset': ('#1a0e0a', '#2c1810', '"#f093fb"', '"#fca311"', 'rgba(240,147,251,0.2)'),
    'forest': ('#050d0a', '#0a1a12', '"#2ecc71"', '"#1abc9c"', 'rgba(46,204,113,0.2)'),
    'neon': ('#050510', '#0a0a20', '"#00ff87"', '"#ff00ff"', 'rgba(0,255,135,0.2)'),
    'midnight': ('#03030f', '#080818', '"#7c3aed"', '"#6366f1"', 'rgba(124,58,237,0.2)'),
    'aurora': ('#000814', '#001024', '"#00b4d8"', '"#90e0ef"', 'rgba(0,180,216,0.2)'),
    'candy': ('#0f0a14', '#1a0f1e', '"#ff6b6b"', '"#ffd93d"', 'rgba(255,107,107,0.2)'),
    'mono': ('#050505', '#0f0f0f', '"#888888"', '"#cccccc"', 'rgba(136,136,136,0.2)')
}
for t in themes:
    bg, bg2, p, a, gb = theme_css[t]
    A(f'.theme-{t} {{ --bg-primary: {bg}; --bg-secondary: {bg2}; }}')
    A(f'.theme-{t} .welcome-logo {{ background: linear-gradient(135deg, {p}, {a}); -webkit-background-clip: text; background-clip: text; }}')
    A(f'.theme-{t} ::selection {{ background: {gb}; }}')
    A(f'.theme-{t} .sidebar {{ background: linear-gradient(180deg, {bg2}, #000); }}')
    A(f'.theme-{t} .input-wrapper:focus-within {{ border-color: {a}; }}')
    A(f'.theme-{t} .model-badge {{ background: linear-gradient(135deg, {p}, {a}); }}')
    A(f'.theme-{t} .send-btn {{ background: linear-gradient(135deg, {p}, {a}); }}')
    A(f'.theme-{t} .rgb-border::before {{ background: linear-gradient(90deg, {p}, {a}, {p}); }}')

A('</style>')

# Extra HTML: loading skeletons and status indicators
A('')
A('<!-- Additional Status Bar Indicators -->')
A('<div class="status-bar" style="position:static;margin-top:0;display:none;" id="statusBarClone">')
A('  <div class="status-item"><span class="status-dot online"></span><span>SXIGOai V2.0</span></div>')
A('</div>')

A('')
A('<!-- Mobile Sidebar Overlay -->')
A('<div class="settings-overlay" id="mobileSidebarOverlay" onclick="toggleSidebar()"></div>')

A('')
A('<!-- Tutorial Overlay -->')
A('<div class="modal-overlay" id="tutorialOverlay" onclick="if(event.target===this)closeTutorial()">')
A('  <div class="modal wide" onclick="event.stopPropagation()">')
A('    <div class="modal-header"><h3>&#x1F4D6; Welcome to SXIGOai V2.0</h3><button class="modal-close-btn" onclick="closeTutorial()">&#x2716;</button></div>')
A('    <div class="modal-body">')
A('      <div class="glass-card-v2" style="margin-bottom:12px;"><div class="card-title">&#x1F504; Getting Started</div><div class="card-body">SXIGOai V2.0 is a next-generation AI chat interface. Start by typing a message below or click one of the welcome prompts.</div></div>')
A('      <div class="glass-card-v2" style="margin-bottom:12px;"><div class="card-title">&#x1F3A4; Voice Input</div><div class="card-body">Click the microphone button in the input area to use voice input (Chrome-based browsers).</div></div>')
A('      <div class="glass-card-v2" style="margin-bottom:12px;"><div class="card-title">&#x1F4E5; Pull Models</div><div class="card-body">Use the pull model button to download new Ollama models like llama3.2, mistral, or gemma.</div></div>')
A('      <div class="glass-card-v2" style="margin-bottom:12px;"><div class="card-title">&#x2328; Keyboard Shortcuts</div><div class="card-body">Ctrl+N: New Chat | Ctrl+B: Toggle Sidebar | Ctrl+F: Search | Ctrl+P: Pull Model | Ctrl+Shift+P: Commands</div></div>')
A('      <div class="glass-card-v2"><div class="card-title">&#x1F3A8; Customization</div><div class="card-body">Open settings (gear icon) to switch themes, adjust glass depth, change font size, or create custom theme colors.</div></div>')
A('    </div>')
A('    <div class="modal-footer"><button class="modal-btn primary" onclick="closeTutorial()">Got it!</button></div>')
A('  </div>')
A('</div>')

# Tutorial functions
A('<script>')
A('function openTutorial() { document.getElementById("tutorialOverlay").classList.add("open"); }')
A('function closeTutorial() { document.getElementById("tutorialOverlay").classList.remove("open"); localStorage.setItem("sxigo_tutorial_done","1"); }')
A('')
A('// Show tutorial on first visit')
A('if (!localStorage.getItem("sxigo_tutorial_done")) {')
A('  setTimeout(openTutorial, 1000);')
A('}')
A('')
A('// ---- Welcome to version indicator ----')
A('function showVersionInfo() {')
A('  showToast("SXIGOai V2.0 - Glassmorphism RGB Edition", "info");')
A('}')
A('')
A('// ---- Demo mode: auto-respond with placeholder ----')
A('let demoMode = false;')
A('function toggleDemoMode() {')
A('  demoMode = !demoMode;')
A('  showToast(demoMode ? "Demo mode enabled" : "Demo mode disabled", "info");')
A('}')
A('')
A('// Handle demo responses')
A('const origSendMsg = sendMessage;')
A('sendMessage = async function() {')
A('  if (demoMode) {')
A('    const input = document.getElementById("messageInput");')
A('    const text = input.value.trim();')
A('    if (!text) return;')
A('    input.value = "";')
A('    messages.push({ role: "user", content: text, timestamp: Date.now() });')
A('    renderMessages();')
A('    setTimeout(function() {')
A('      const demoResponse = "This is a demo response. Connect to Ollama server for real AI responses.\\n\\nYou said: " + text;')
A('      messages.push({ role: "assistant", content: demoResponse, timestamp: Date.now() });')
A('      renderMessages();')
A('      saveCurrentConversation();')
A('    }, 1000);')
A('    return;')
A('  }')
A('  await origSendMsg();')
A('}')
A('')
A('// ---- Accessibility features ----')
A('function increaseContrast() {')
A('  document.documentElement.style.setProperty("--text-primary", "#ffffff");')
A('  document.documentElement.style.setProperty("--text-secondary", "#e0e0e0");')
A('  document.documentElement.style.setProperty("--text-muted", "#a0a0a0");')
A('  showToast("High contrast mode", "info");')
A('}')
A('')
A('function reduceAnimations() {')
A('  document.documentElement.style.setProperty("--transition", "0.01s");')
A('  document.querySelectorAll("*").forEach(function(el) {')
A('    el.style.animationDuration = "0.01s";')
A('    el.style.transitionDuration = "0.01s";')
A('  });')
A('  showToast("Animations reduced", "info");')
A('}')
A('')
A('function largeTextMode() {')
A('  document.documentElement.style.setProperty("--font-size-base", "18px");')
A('  showToast("Large text mode", "info");')
A('}')
A('')
A('// ---- Session statistics tracking ----')
A('let sessionStats = {')
A('  startTime: Date.now(),')
A('  messagesSent: 0,')
A('  tokensGenerated: 0,')
A('  modelsUsed: {},')
A('  commandsUsed: 0')
A('};')
A('')
A('function recordMessageSent() { sessionStats.messagesSent++; }')
A('function recordTokens(count, model) {')
A('  sessionStats.tokensGenerated += count;')
A('  if (model) {')
A('    sessionStats.modelsUsed[model] = (sessionStats.modelsUsed[model] || 0) + count;')
A('  }')
A('}')
A('function recordCommand() { sessionStats.commandsUsed++; }')
A('')
A('// ---- Export detailed session report ----')
A('function generateSessionReport() {')
A('  const elapsed = Math.floor((Date.now() - sessionStats.startTime) / 1000);')
A('  const h = Math.floor(elapsed / 3600);')
A('  const m = Math.floor((elapsed % 3600) / 60);')
A('  const s = elapsed % 60;')
A('  const report = [')
A('    "SXIGOai V2.0 - Session Report",')
A('    "=".repeat(40),')
A('    "",')
A('    "Duration: " + h + "h " + m + "m " + s + "s",')
A('    "Messages Sent: " + sessionStats.messagesSent,')
A('    "Total Tokens: " + sessionStats.tokensGenerated,')
A('    "Commands Used: " + sessionStats.commandsUsed,')
A('    "Models Used: " + Object.keys(sessionStats.modelsUsed).join(", ") || "None",')
A('    "",')
A('    "Conversations: " + conversations.length,')
A('    "Current Model: " + (settings.currentModel || "llama3.2:3b"),')
A('    "Theme: " + (settings.theme || "ocean"),')
A('    ""')
A('  ].join("\\n");')
A('  const blob = new Blob([report], { type: "text/plain" });')
A('  const url = URL.createObjectURL(blob);')
A('  const a = document.createElement("a"); a.href = url; a.download = "sxigo_session_report.txt"; a.click();')
A('  URL.revokeObjectURL(url);')
A('  showToast("Session report exported!", "success");')
A('}')
A('')
A('// Hook into sendMessage to track stats')
A('const origSendMsg2 = sendMessage;')
A('sendMessage = async function() {')
A('  recordMessageSent();')
A('  await origSendMsg2();')
A('}')
A('')
A('// ---- Model comparison helper ----')
A('function compareModelResponses(prompt, modelA, modelB) {')
A('  openCompare();')
A('  document.getElementById("comparePaneA").innerHTML = "Loading response from " + modelA + "...";')
A('  document.getElementById("comparePaneB").innerHTML = "Loading response from " + modelB + "...";')
A('  async function getResponse(model) {')
A('    try {')
A('      const res = await fetch(getServerUrl() + "/api/chat", {')
A('        method: "POST",')
A('        headers: { "Content-Type": "application/json" },')
A('        body: JSON.stringify({ model: model, messages: [{ role: "user", content: prompt }], stream: false })')
A('      });')
A('      const data = await res.json();')
A('      return data.message ? data.message.content : "No response";')
A('    } catch(e) { return "Error: " + e.message; }')
A('  }')
A('  Promise.all([getResponse(modelA), getResponse(modelB)]).then(function(responses) {')
A('    document.getElementById("comparePaneA").innerHTML = "<strong>Model A (" + modelA + "):</strong><br>" + responses[0].replace(/\\n/g, "<br>");')
A('    document.getElementById("comparePaneB").innerHTML = "<strong>Model B (" + modelB + "):</strong><br>" + responses[1].replace(/\\n/g, "<br>");')
A('  });')
A('}')
A('')
A('// ---- Pin to top conversations ----')
A('function pinConversation(id) {')
A('  const conv = conversations.find(function(c) { return c.id === id; });')
A('  if (!conv) return;')
A('  conv.pinned = !conv.pinned;')
A('  if (conv.pinned) {')
A('    const idx = conversations.indexOf(conv);')
A('    conversations.splice(idx, 1);')
A('    conversations.unshift(conv);')
A('  }')
A('  saveConversations();')
A('  renderConversationList();')
A('  showToast(conv.pinned ? "Conversation pinned!" : "Conversation unpinned", "info");')
A('}')
A('')
A('// ---- Quick tag assignment ----')
A('function assignTag(tag) {')
A('  const conv = conversations.find(function(c) { return c.id === currentConversationId; });')
A('  if (!conv) return;')
A('  conv.tag = tag;')
A('  saveConversations();')
A('  renderConversationList();')
A('  showToast("Tagged as " + tag, "info");')
A('}')
A('')
A('// ---- Markdown rendering improvements ----')
A('function renderMarkdown(text) {')
A('  let html = text')
A('    .replace(/&/g, "&amp;")')
A('    .replace(/</g, "&lt;")')
A('    .replace(/>/g, "&gt;")')
A('    .replace(/^### (.+)$/gm, "<h3>$1</h3>")')
A('    .replace(/^## (.+)$/gm, "<h2>$1</h2>")')
A('    .replace(/^# (.+)$/gm, "<h1>$1</h1>")')
A('    .replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>")')
A('    .replace(/\\*(.+?)\\*/g, "<em>$1</em>")')
A('    .replace(/```(\\w*)\\n?([\\s\\S]*?)```/g, function(_, lang, code) {')
A('      return "<pre><code class=\\"" + lang + "\\">" + code + "</code></pre>";')
A('    })')
A('    .replace(/`([^`]+)`/g, "<code>$1</code>")')
A('    .replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g, "<a href=\\"$2\\" target=\\"_blank\\">$1</a>")')
A('    .replace(/^\\* (.+)$/gm, "<li>$1</li>")')
A('    .replace(/^\\d+\\. (.+)$/gm, "<li>$1</li>")')
A('    .replace(/\\n\\n/g, "</p><p>")')
A('    .replace(/\\n/g, "<br>");')
A('  return "<p>" + html + "</p>";')
A('}')
A('')
A('// ---- Custom welcome messages ----')
A('function setCustomWelcome(title, subtitle) {')
A('  const t = document.querySelector(".welcome-title");')
A('  const s = document.querySelector(".welcome-subtitle");')
A('  if (t && title) t.textContent = title;')
A('  if (s && subtitle) s.textContent = subtitle;')
A('}')
A('')
A('// ---- Export theme configuration ----')
A('function exportCurrentTheme() {')
A('  const root = getComputedStyle(document.documentElement);')
A('  const theme = {')
A('    name: settings.theme || "ocean",')
A('    colors: {')
A('      primary: root.getPropertyValue("--accent-1").trim(),')
A('      secondary: root.getPropertyValue("--accent-5").trim(),')
A('      accent: root.getPropertyValue("--accent-6").trim(),')
A('      background: root.getPropertyValue("--bg-primary").trim()')
A('    },')
A('    glassDepth: document.getElementById("glassDepth").value,')
A('    fontSize: settings.fontSize || 14')
A('  };')
A('  const blob = new Blob([JSON.stringify(theme, null, 2)], { type: "application/json" });')
A('  const url = URL.createObjectURL(blob);')
A('  const a = document.createElement("a"); a.href = url; a.download = "sxigo_theme.json"; a.click();')
A('  URL.revokeObjectURL(url);')
A('  showToast("Theme exported!", "success");')
A('}')
A('')
A('// ---- Import theme configuration ----')
A('function importTheme() {')
A('  const input = document.createElement("input");')
A('  input.type = "file"; input.accept = ".json";')
A('  input.onchange = function(e) {')
A('    const file = e.target.files[0];')
A('    if (!file) return;')
A('    const reader = new FileReader();')
A('    reader.onload = function(ev) {')
A('      try {')
A('        const theme = JSON.parse(ev.target.result);')
A('        if (theme.colors) {')
A('          document.documentElement.style.setProperty("--accent-1", theme.colors.primary);')
A('          document.documentElement.style.setProperty("--accent-5", theme.colors.secondary);')
A('          document.documentElement.style.setProperty("--accent-6", theme.colors.accent);')
A('          document.documentElement.style.setProperty("--bg-primary", theme.colors.background);')
A('          if (theme.glassDepth) document.getElementById("glassDepth").value = theme.glassDepth;')
A('          if (theme.fontSize) { settings.fontSize = theme.fontSize; document.documentElement.style.setProperty("--font-size-base", theme.fontSize + "px"); }')
A('          showToast("Theme imported!", "success");')
A('        }')
A('      } catch(err) { showToast("Invalid theme file", "error"); }')
A('    };')
A('    reader.readAsText(file);')
A('  };')
A('  input.click();')
A('}')
A('')
A('// ---- Comprehensive error handling ----')
A('window.onerror = function(msg, url, line, col, error) {')
A('  console.error("SXIGOai caught error:", msg, "at", line + ":" + col);')
A('  if (isStreaming) {')
A('    isStreaming = false;')
A('    document.getElementById("sendBtn").style.display = "flex";')
A('    document.getElementById("stopBtn").classList.remove("visible");')
A('  }')
A('  return false;')
A('};')
A('')
A('// ---- Unload handler for streaming ----')
A('window.addEventListener("beforeunload", function(e) {')
A('  if (isStreaming && abortController) {')
A('    abortController.abort();')
A('  }')
A('});')
A('')
A('// ---- Service worker registration (placeholder) ----')
A('if ("serviceWorker" in navigator) {')
A('  // navigator.serviceWorker.register("/sw.js");')
A('  console.log("Service worker support detected");')
A('}')
A('')
A('// ---- PWA manifest link ----')
A('const manifestLink = document.createElement("link");')
A('manifestLink.rel = "manifest";')
A('manifestLink.href = "/manifest.json";')
A('// document.head.appendChild(manifestLink);')
A('')
A('// ---- CSP nonce (placeholder) ----')
A('// Content-Security-Policy: default-src \'self\'; script-src \'self\';')
A('')
A('// ---- Config validation ----')
A('function validateConfig() {')
A('  const issues = [];')
A('  if (!getServerUrl()) issues.push("Server URL is empty");')
A('  try { new URL(getServerUrl()); } catch(e) { issues.push("Server URL is invalid: " + getServerUrl()); }')
A('  if (!settings.currentModel) issues.push("No model selected");')
A('  if (issues.length > 0) {')
A('    console.warn("SXIGOai configuration issues:", issues);')
A('  }')
A('  return issues;')
A('}')
A('setTimeout(validateConfig, 3000);')
A('')
A('// ---- Health check improved ----')
A('const origCheck = checkServerHealth;')
A('checkServerHealth = async function() {')
A('  const result = await origCheck();')
A('  if (result) {')
A('    document.getElementById("statusBarLatency").style.color = "var(--accent-4)";')
A('  } else {')
A('    document.getElementById("statusBarLatency").style.color = "var(--accent-1)";')
A('  }')
A('  return result;')
A('}')
A('')
A('// ---- Rate estimation for token display ----')
A('function estimateTokensToComplete(text) {')
A('  const tokens = estimateTokenCount(text);')
A('  const rate = parseFloat(document.getElementById("modelRateBadge").textContent) || 20;')
A('  return (tokens / rate).toFixed(1);')
A('}')
A('')
A('// ---- Memory for context display ----')
A('function getConversationSize() {')
A('  if (typeof Blob === "undefined") return 0;')
A('  try {')
A('    return new Blob([JSON.stringify(messages)]).size;')
A('  } catch(e) { return 0; }')
A('}')
A('')
A('// ---- Auto-resize conversation list items ----')
A('function updateConversationTimestamps() {')
A('  document.querySelectorAll(".conv-item").forEach(function(el, i) {')
A('    if (conversations[i]) {')
A('      const ts = el.querySelector(".conv-timestamp");')
A('      if (ts) ts.textContent = getRelativeTime(conversations[i].createdAt || Date.now());')
A('    }')
A('  });')
A('}')
A('setInterval(updateConversationTimestamps, 30000);')
A('')
A('// ---- Show typing indicator in status bar ----')
A('function showTypingStatus() {')
A('  const el = document.getElementById("typingStatus");')
A('  if (el && isStreaming) el.classList.add("visible");')
A('  else if (el) el.classList.remove("visible");')
A('}')
A('setInterval(showTypingStatus, 500);')
A('')
A('// ---- Model config tips ----')
A('function getModelRecommendation() {')
A('  const model = settings.currentModel || "";')
A('  if (model.includes("3.2:3b")) return "Balanced speed and quality";')
A('  if (model.includes("3.2:1b")) return "Fast, lightweight responses";')
A('  if (model.includes("mistral")) return "Good for coding tasks";')
A('  if (model.includes("gemma")) return "Efficient and capable";')
A('  if (model.includes("phi")) return "Great for reasoning";')
A('  return "Custom model";')
A('}')
A('')
A('// ---- Initialize model recommendation display ----')
A('setInterval(function() {')
A('  const badge = document.getElementById("modelRateBadge");')
A('  if (badge) badge.title = getModelRecommendation();')
A('}, 3000);')
A('')
A('// ---- Chat input placeholder cycling ----')
A('const PLACEHOLDERS = [')
A('  "Message SXIGOai...",')
A('  "Ask me anything...",')
A('  "Type your question...",')
A('  "Send a message...",')
A('  "What do you want to know?..."')
A('];')
A('let phIndex = 0;')
A('setInterval(function() {')
A('  const input = document.getElementById("messageInput");')
A('  if (input && !document.activeElement === input) {')
A('    phIndex = (phIndex + 1) % PLACEHOLDERS.length;')
A('    input.placeholder = PLACEHOLDERS[phIndex];')
A('  }')
A('}, 5000);')
A('')
A('// ---- Final initialization flag ----')
A('window.SXIGOAI_VERSION = "2.0";')
A('window.SXIGOAI_FEATURES = {')
A('  glassmorphism: true,')
A('  rgbEffects: true,')
A('  voiceInput: true,')
A('  streaming: true,')
A('  themes: Object.keys(THEMES),')
A('  commandPalette: true,')
A('  compareView: true,')
A('  bookmarks: true,')
A('  search: true,')
A('  notifications: true,')
A('  dashboard: true,')
A('  export: true,')
A('  fileAttach: true,')
A('  reactions: true,')
A('  contextMenu: true,')
A('  autoBackup: true,')
A('  codePlayground: true,')
A('  accessibility: true,')
A('  fullscreen: true,')
A('  dragDrop: true,')
A('  sessionReporting: true,')
A('  modelCompare: true,')
A('  themeExport: true,')
A('  demoMode: true,')
A('  tutorial: true,')
A('  offlineDetection: true,')
A('  rateLimit: true,')
A('  autoRecovery: true')
A('};')
A('')
A('console.log("SXIGOai V2.0 fully loaded with " + Object.keys(window.SXIGOAI_FEATURES).length + " features");')
A('console.log("Server:", getServerUrl());')
A('console.log("Model:", settings.currentModel || "not set");')
A('console.log("Theme:", settings.theme || "ocean");')
A('console.log("Session started:", new Date(sessionStart).toLocaleString());')
A('')
A('// ---- Document ready check ----')
A('if (document.readyState === "loading") {')
A('  document.addEventListener("DOMContentLoaded", init);')
A('} else {')
A('  init();')
A('}')
A('')
A('</script>')

# Insert before </body>
insertion = '\n'.join(extra)
content = content.replace('</body>', insertion + '\n</body>')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n')
print(f'Total lines: {line_count}')
