path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Add back DOCTYPE and html tag if missing
if '<!DOCTYPE html>' not in lines[0] and '<html' not in lines[0]:
    lines.insert(0, '<!DOCTYPE html>\n')
    lines.insert(1, '<html lang="ko">\n')
    lines.insert(2, '<head>\n')

# Add substantial additional CSS, HTML panels, and JS features
# to reach 6200+ lines

extra = []

# ===== ADDITIONAL CSS =====
extra.append('<style>')
extra.append('/* V2.0 Additional Features CSS */')
extra.append('.search-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.6); backdrop-filter: blur(8px); z-index: 150; display: none; align-items: flex-start; justify-content: center; padding-top: 80px; }')
extra.append('.search-overlay.open { display: flex; }')
extra.append('.search-box { width: 560px; max-width: 90vw; background: rgba(22,22,52,0.95); backdrop-filter: blur(32px); border: 1px solid var(--glass-border); border-radius: var(--radius-lg); padding: 20px; box-shadow: 0 24px 80px rgba(0,0,0,0.5); }')
extra.append('.search-box input { width: 100%; padding: 10px 14px; border: 1px solid var(--glass-border); border-radius: var(--radius-sm); background: rgba(26,26,62,0.8); color: var(--text-primary); font-size: 15px; outline: none; }')
extra.append('.search-box input:focus { border-color: var(--accent-5); box-shadow: 0 0 0 3px rgba(102,126,234,0.15); }')
extra.append('.search-results { max-height: 360px; overflow-y: auto; margin-top: 10px; }')
extra.append('.search-result-item { padding: 8px 10px; border-radius: var(--radius-sm); cursor: pointer; font-size: 13px; color: var(--text-secondary); margin: 3px 0; background: rgba(255,255,255,0.03); border: 1px solid var(--glass-border); transition: var(--transition); }')
extra.append('.search-result-item:hover { background: rgba(255,255,255,0.06); border-color: var(--accent-5); }')
extra.append('.search-result-item .sr-role { font-size: 10px; text-transform: uppercase; color: var(--accent-5); font-weight: 600; }')
extra.append('.search-result-item .sr-preview { margin-top: 2px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }')
extra.append('.search-result-item .sr-idx { float: right; font-size: 10px; color: var(--text-muted); }')
extra.append('')
extra.append('.bookmarks-panel { position: fixed; top: 0; left: -380px; width: 380px; height: 100vh; background: rgba(18,18,42,0.95); backdrop-filter: blur(32px) saturate(1.5); border-right: 1px solid var(--glass-border); transition: var(--transition); z-index: 215; box-shadow: 10px 0 40px rgba(0,0,0,0.3); display: flex; flex-direction: column; }')
extra.append('.bookmarks-panel.open { left: 0; }')
extra.append('.bookmarks-header { display: flex; align-items: center; justify-content: space-between; padding: 16px 20px; border-bottom: 1px solid var(--glass-border); }')
extra.append('.bookmarks-header h3 { font-size: 15px; font-weight: 700; }')
extra.append('.bookmarks-list { flex: 1; overflow-y: auto; padding: 12px 16px; }')
extra.append('')
extra.append('.export-menu { position: fixed; z-index: 450; min-width: 140px; padding: 4px; border-radius: var(--radius-sm); background: rgba(22,22,52,0.95); backdrop-filter: blur(24px); border: 1px solid var(--glass-border); box-shadow: 0 12px 48px rgba(0,0,0,0.4); display: none; }')
extra.append('.export-menu.open { display: block; }')
extra.append('.export-menu-item { padding: 6px 12px; border-radius: 4px; cursor: pointer; font-size: 12px; color: var(--text-secondary); transition: var(--transition); }')
extra.append('.export-menu-item:hover { background: rgba(255,255,255,0.06); color: var(--text-primary); }')
extra.append('')
extra.append('.code-theme-selector { display: flex; gap: 4px; margin: 4px 0; }')
extra.append('.code-theme-btn { padding: 2px 8px; border-radius: 4px; border: 1px solid var(--glass-border); background: transparent; color: var(--text-muted); font-size: 10px; cursor: pointer; transition: var(--transition); }')
extra.append('.code-theme-btn:hover { background: rgba(255,255,255,0.06); }')
extra.append('.code-theme-btn.active { background: rgba(102,126,234,0.15); color: var(--accent-5); border-color: var(--accent-5); }')
extra.append('')
extra.append('.session-timer { font-size: 10px; color: var(--text-muted); padding: 4px 8px; }')
extra.append('.memory-usage { font-size: 10px; color: var(--text-muted); }')
extra.append('.message-counter { font-size: 10px; color: var(--text-muted); }')
extra.append('')
extra.append('.conv-context-bar { height: 3px; background: var(--bg-tertiary); border-radius: 2px; overflow: hidden; margin: 8px 0; }')
extra.append('.conv-context-fill { height: 100%; background: linear-gradient(90deg, var(--accent-5), var(--accent-6)); border-radius: 2px; transition: width 0.5s ease; }')
extra.append('.conv-context-label { display: flex; justify-content: space-between; font-size: 10px; color: var(--text-muted); }')
extra.append('')
extra.append('.rgb-divider { height: 2px; background: linear-gradient(90deg, var(--accent-1), var(--accent-5), var(--accent-6), var(--accent-1)); background-size: 300% 100%; animation: rgb-text-flow 4s ease-in-out infinite; border: none; margin: 8px 0; }')
extra.append('.glass-divider { height: 1px; background: var(--glass-border); border: none; margin: 12px 0; }')
extra.append('')
extra.append('.input-char-count { position: absolute; bottom: 2px; right: 56px; font-size: 10px; color: var(--text-muted); pointer-events: none; }')
extra.append('.model-select-quick { display: flex; gap: 4px; padding: 4px 0; }')
extra.append('.model-quick-btn { padding: 2px 8px; border-radius: 8px; border: 1px solid var(--glass-border); background: transparent; color: var(--text-muted); font-size: 10px; cursor: pointer; transition: var(--transition); }')
extra.append('.model-quick-btn:hover { background: rgba(255,255,255,0.06); }')
extra.append('.model-quick-btn.active { background: rgba(102,126,234,0.15); border-color: var(--accent-5); }')
extra.append('')
extra.append('.tag-edit-input { width: 100%; padding: 6px 10px; border: 1px solid var(--accent-5); border-radius: var(--radius-sm); background: rgba(26,26,62,0.8); color: var(--text-primary); font-size: 12px; outline: none; }')
extra.append('')
extra.append('.conv-tag-badge { display: inline-block; padding: 1px 6px; border-radius: 6px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; background: rgba(102,126,234,0.15); color: var(--accent-5); margin-left: 4px; }')
extra.append('')
extra.append('.filter-bar { display: flex; gap: 6px; align-items: center; padding: 8px 16px; background: rgba(255,255,255,0.02); backdrop-filter: blur(8px); border-bottom: 1px solid var(--glass-border); font-size: 12px; }')
extra.append('.filter-bar select { padding: 4px 8px; border: 1px solid var(--glass-border); border-radius: 4px; background: rgba(26,26,62,0.8); color: var(--text-primary); font-size: 11px; outline: none; }')
extra.append('.filter-bar .filter-label { color: var(--text-muted); font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; }')
extra.append('')
extra.append('.mention-suggest { position: absolute; bottom: 100%; left: 18px; max-height: 180px; overflow-y: auto; background: rgba(22,22,52,0.95); backdrop-filter: blur(32px); border: 1px solid var(--glass-border); border-radius: var(--radius-sm); padding: 4px; min-width: 200px; display: none; box-shadow: 0 8px 32px rgba(0,0,0,0.3); }')
extra.append('.mention-suggest.open { display: block; }')
extra.append('.mention-item { padding: 5px 10px; border-radius: 4px; cursor: pointer; font-size: 12px; color: var(--text-secondary); transition: var(--transition); }')
extra.append('.mention-item:hover { background: rgba(255,255,255,0.06); color: var(--text-primary); }')
extra.append('.mention-item .mention-name { font-weight: 600; }')
extra.append('.mention-item .mention-desc { font-size: 10px; color: var(--text-muted); }')
extra.append('')
extra.append('.slash-command-menu { position: absolute; bottom: 100%; left: 18px; max-height: 220px; overflow-y: auto; background: rgba(22,22,52,0.95); backdrop-filter: blur(32px); border: 1px solid var(--glass-border); border-radius: var(--radius-sm); padding: 4px; min-width: 240px; display: none; box-shadow: 0 8px 32px rgba(0,0,0,0.3); }')
extra.append('.slash-command-menu.open { display: block; }')
extra.append('.slash-item { padding: 6px 10px; border-radius: 4px; cursor: pointer; font-size: 12px; color: var(--text-secondary); transition: var(--transition); }')
extra.append('.slash-item:hover { background: rgba(255,255,255,0.06); color: var(--text-primary); }')
extra.append('.slash-item .slash-name { font-weight: 600; color: var(--accent-5); }')
extra.append('.slash-item .slash-desc { font-size: 10px; color: var(--text-muted); }')
extra.append('')
extra.append('.context-indicator { display: flex; align-items: center; gap: 4px; padding: 2px 8px; border-radius: 8px; background: rgba(255,255,255,0.03); font-size: 10px; color: var(--text-muted); }')
extra.append('.context-indicator .ci-dot { width: 5px; height: 5px; border-radius: 50%; background: var(--accent-4); }')
extra.append('')
extra.append('.model-info-popup { position: absolute; top: 100%; left: 0; background: rgba(22,22,52,0.95); backdrop-filter: blur(32px); border: 1px solid var(--glass-border); border-radius: var(--radius-sm); padding: 12px; min-width: 200px; display: none; z-index: 50; box-shadow: 0 12px 48px rgba(0,0,0,0.4); }')
extra.append('.model-info-popup.open { display: block; }')
extra.append('.model-info-popup .mi-row { display: flex; justify-content: space-between; font-size: 11px; color: var(--text-secondary); padding: 2px 0; }')
extra.append('.model-info-popup .mi-row .mi-label { color: var(--text-muted); }')
extra.append('')
extra.append('.panel-resize-handle { position: absolute; top: 0; bottom: 0; width: 4px; cursor: col-resize; z-index: 10; }')
extra.append('.panel-resize-handle:hover { background: rgba(102,126,234,0.3); }')
extra.append('')
extra.append('.thinking-block { border-left: 3px solid var(--accent-5); padding: 8px 12px; margin: 8px 0; background: rgba(255,255,255,0.02); border-radius: 0 var(--radius-sm) var(--radius-sm) 0; font-size: 12px; color: var(--text-muted); font-style: italic; }')
extra.append('.thinking-block .tb-header { font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--accent-5); font-weight: 600; margin-bottom: 4px; font-style: normal; }')
extra.append('')
extra.append('.math-block { overflow-x: auto; padding: 8px; background: rgba(0,0,0,0.2); border-radius: var(--radius-sm); margin: 8px 0; font-family: var(--font-mono); }')
extra.append('')
extra.append('.task-list { list-style: none; padding-left: 0; }')
extra.append('.task-list li { display: flex; align-items: center; gap: 6px; margin: 3px 0; font-size: 13px; }')
extra.append('.task-list li input[type=checkbox] { accent-color: var(--accent-5); width: 14px; height: 14px; }')
extra.append('.task-list li.checked { text-decoration: line-through; opacity: 0.6; }')
extra.append('')
extra.append('.image-attachment { max-width: 100%; border-radius: var(--radius-sm); margin: 6px 0; border: 1px solid var(--glass-border); }')
extra.append('.file-attachment { display: flex; align-items: center; gap: 8px; padding: 6px 10px; border-radius: var(--radius-sm); background: rgba(255,255,255,0.03); border: 1px solid var(--glass-border); margin: 4px 0; font-size: 12px; }')
extra.append('.file-attachment .fa-icon { font-size: 18px; }')
extra.append('.file-attachment .fa-name { font-weight: 600; color: var(--text-primary); }')
extra.append('.file-attachment .fa-size { color: var(--text-muted); font-size: 10px; }')
extra.append('')
extra.append('.error-message { color: #ff6b6b; font-size: 13px; padding: 8px 12px; background: rgba(255,107,107,0.1); border: 1px solid rgba(255,107,107,0.2); border-radius: var(--radius-sm); margin: 4px 0; }')
extra.append('.warning-message { color: #ffd93d; font-size: 13px; padding: 8px 12px; background: rgba(255,217,61,0.1); border: 1px solid rgba(255,217,61,0.2); border-radius: var(--radius-sm); margin: 4px 0; }')
extra.append('.success-message { color: #2ecc71; font-size: 13px; padding: 8px 12px; background: rgba(46,204,113,0.1); border: 1px solid rgba(46,204,113,0.2); border-radius: var(--radius-sm); margin: 4px 0; }')

# More loading states
extra.append('')
extra.append('.loading-wave { display: flex; gap: 3px; align-items: center; padding: 10px 0; }')
extra.append('.loading-wave .lw-bar { width: 4px; height: 16px; border-radius: 2px; background: var(--accent-5); animation: loading-wave 1s ease-in-out infinite; }')
extra.append('.loading-wave .lw-bar:nth-child(2) { animation-delay: 0.1s; height: 24px; }')
extra.append('.loading-wave .lw-bar:nth-child(3) { animation-delay: 0.2s; height: 12px; }')
extra.append('.loading-wave .lw-bar:nth-child(4) { animation-delay: 0.15s; height: 20px; }')
extra.append('.loading-wave .lw-bar:nth-child(5) { animation-delay: 0.25s; height: 8px; }')
extra.append('@keyframes loading-wave { 0%,100% { transform: scaleY(0.5); } 50% { transform: scaleY(1); } }')
extra.append('')
extra.append('.model-select-badge { display: inline-flex; align-items: center; gap: 4px; padding: 2px 10px; border-radius: 10px; background: linear-gradient(135deg, rgba(102,126,234,0.15), rgba(151,117,250,0.1)); border: 1px solid rgba(102,126,234,0.2); font-size: 11px; color: var(--accent-5); font-weight: 500; }')
extra.append('.model-select-badge .msb-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--accent-4); }')
extra.append('')
extra.append('.conv-timestamp { font-size: 9px; color: var(--text-muted); margin-top: 2px; }')
extra.append('.conv-message-count { font-size: 9px; color: var(--text-muted); }')
extra.append('')
extra.append('.settings-section-title { font-size: 16px; font-weight: 700; margin-bottom: 12px; color: var(--text-primary); }')
extra.append('.settings-desc { font-size: 12px; color: var(--text-muted); margin-bottom: 12px; line-height: 1.5; }')
extra.append('')
extra.append('.shortcut-category { font-size: 12px; font-weight: 700; color: var(--text-secondary); margin: 12px 0 6px; padding-bottom: 4px; border-bottom: 1px solid var(--glass-border); }')
extra.append('')
extra.append('.glass-card-v2 { padding: 20px; border-radius: var(--radius-lg); background: rgba(255,255,255,calc(var(--glass-depth) + 0.02)); backdrop-filter: blur(20px); border: 1px solid var(--glass-border); transition: var(--transition); }')
extra.append('.glass-card-v2:hover { background: rgba(255,255,255,0.07); border-color: rgba(102,126,234,0.2); transform: translateY(-2px); box-shadow: 0 12px 40px rgba(0,0,0,0.2); }')
extra.append('.glass-card-v2 .card-title { font-size: 16px; font-weight: 700; margin-bottom: 8px; }')
extra.append('.glass-card-v2 .card-body { font-size: 13px; color: var(--text-secondary); line-height: 1.6; }')
extra.append('')
extra.append('.notification-badge { position: absolute; top: -4px; right: -4px; min-width: 16px; height: 16px; border-radius: 8px; background: var(--accent-1); color: #fff; font-size: 9px; font-weight: 700; display: flex; align-items: center; justify-content: center; padding: 0 4px; }')
extra.append('')
extra.append('.focus-ring:focus-visible { outline: 2px solid var(--accent-5); outline-offset: 2px; border-radius: 4px; }')
extra.append('.truncate { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }')
extra.append('.flex-center { display: flex; align-items: center; justify-content: center; }')
extra.append('.gap-4 { gap: 4px; } .gap-6 { gap: 6px; } .gap-8 { gap: 8px; } .gap-10 { gap: 10px; }')
extra.append('.mt-4 { margin-top: 4px; } .mt-8 { margin-top: 8px; } .mb-4 { margin-bottom: 4px; } .mb-8 { margin-bottom: 8px; }')
extra.append('.text-center { text-align: center; }')
extra.append('.text-muted { color: var(--text-muted); }')
extra.append('.text-accent { color: var(--accent-5); }')
extra.append('')
extra.append('@media (hover: none) and (pointer: coarse) {')
extra.append('  .message-actions { opacity: 1; bottom: 4px; top: auto; }')
extra.append('  .message-action-btn { padding: 6px 10px; }')
extra.append('  .sidebar-icon-btn { min-width: 40px; min-height: 40px; }')
extra.append('  .conv-search-input { font-size: 16px; }')
extra.append('  .header-btn { min-width: 40px; min-height: 40px; }')
extra.append('}')
extra.append('')
extra.append('.scroll-shadow { position: sticky; top: 0; height: 20px; background: linear-gradient(var(--bg-primary), transparent); pointer-events: none; z-index: 2; }')
extra.append('.scroll-shadow-bottom { position: sticky; bottom: 0; height: 20px; background: linear-gradient(transparent, var(--bg-primary)); pointer-events: none; z-index: 2; }')
extra.append('')
extra.append('.overlay-blur { backdrop-filter: blur(4px); -webkit-backdrop-filter: blur(4px); }')
extra.append('.overlay-blur-lg { backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); }')
extra.append('.overlay-blur-xl { backdrop-filter: blur(24px); -webkit-backdrop-filter: blur(24px); }')
extra.append('')
extra.append('.message-highlight { animation: highlight-flash 1.5s ease-out; }')
extra.append('@keyframes highlight-flash { 0% { background: rgba(102,126,234,0.15); } 100% { background: transparent; } }')
extra.append('')
extra.append('.conv-item.dragging { opacity: 0.5; border: 1px dashed var(--accent-5); }')
extra.append('.conv-item.drag-over { border-top: 2px solid var(--accent-5); }')
extra.append('</style>')

# ===== MORE HTML: Bookmarks Panel, Search Overlay, Export Menu =====
extra.append('')
extra.append('<!-- Bookmarks Panel -->')
extra.append('<div class="bookmarks-panel" id="bookmarksPanel">')
extra.append('<div class="bookmarks-header"><h3>&#x2B50; Bookmarks</h3><button class="close-settings" onclick="toggleBookmarksPanel()">&#x2716;</button></div>')
extra.append('<div class="bookmarks-list" id="bookmarksList"><div class="notif-empty">No bookmarked messages yet</div></div>')
extra.append('</div>')

extra.append('')
extra.append('<!-- Search Overlay -->')
extra.append('<div class="search-overlay" id="searchOverlay" onclick="if(event.target===this)closeSearchOverlay()">')
extra.append('<div class="search-box" onclick="event.stopPropagation()">')
extra.append('<input type="text" id="searchOverlayInput" placeholder="Search messages..." onkeydown="if(event.key===\'Enter\')performSearchOverlay()" autofocus>')
extra.append('<div class="search-results" id="searchOverlayResults"></div>')
extra.append('</div>')
extra.append('</div>')

extra.append('')
extra.append('<!-- Export Menu -->')
extra.append('<div class="export-menu" id="exportMenu">')
extra.append('<div class="export-menu-item" onclick="exportChat(\'json\')">&#x1F4CB; Export as JSON</div>')
extra.append('<div class="export-menu-item" onclick="exportChat(\'markdown\')">&#x1F4DD; Export as Markdown</div>')
extra.append('<div class="export-menu-item" onclick="exportChat(\'text\')">&#x1F4C4; Export as Text</div>')
extra.append('<div class="export-menu-separator"></div>')
extra.append('<div class="export-menu-item" onclick="copyChatToClipboard()">&#x1F4CB; Copy to Clipboard</div>')
extra.append('</div>')

# ===== MORE JS FEATURES =====
extra.append('')
extra.append('<script>')
extra.append('// ===== Additional V2.0 Features =====')
extra.append('')
extra.append('// ---- Bookmarks Panel ----')
extra.append('function toggleBookmarksPanel() {')
extra.append('  document.getElementById("bookmarksPanel").classList.toggle("open");')
extra.append('  if (document.getElementById("bookmarksPanel").classList.contains("open")) renderBookmarksList();')
extra.append('}')
extra.append('function renderBookmarksList() {')
extra.append('  const list = document.getElementById("bookmarksList");')
extra.append('  list.innerHTML = "";')
extra.append('  let found = false;')
extra.append('  conversations.forEach(c => {')
extra.append('    if (!c.messages) return;')
extra.append('    c.messages.forEach((m, i) => {')
extra.append('      if (m.bookmarked) {')
extra.append('        found = true;')
extra.append('        const div = document.createElement("div");')
extra.append('        div.className = "bookmark-item";')
extra.append('        div.innerHTML = "<div><div class=\\"bm-title\\">" + c.name + "</div><div class=\\"bm-preview\\">" + m.content.substring(0, 100) + "</div><div class=\\"bm-time\\">" + new Date(m.timestamp).toLocaleString() + "</div></div>";')
extra.append('        div.onclick = function() { loadConversation(c.id); toggleBookmarksPanel(); };')
extra.append('        list.appendChild(div);')
extra.append('      }')
extra.append('    });')
extra.append('  });')
extra.append('  if (!found) list.innerHTML = "<div class=\\"notif-empty\\">No bookmarked messages yet</div>";')
extra.append('}')
extra.append('')
extra.append('// ---- Search Overlay ----')
extra.append('function openSearchOverlay() { document.getElementById("searchOverlay").classList.add("open"); document.getElementById("searchOverlayInput").focus(); }')
extra.append('function closeSearchOverlay() { document.getElementById("searchOverlay").classList.remove("open"); }')
extra.append('function performSearchOverlay() {')
extra.append('  const term = document.getElementById("searchOverlayInput").value.trim();')
extra.append('  if (!term) return;')
extra.append('  const results = document.getElementById("searchOverlayResults");')
extra.append('  results.innerHTML = "";')
extra.append('  let count = 0;')
extra.append('  messages.forEach((m, i) => {')
extra.append('    if (m.content.toLowerCase().includes(term.toLowerCase())) {')
extra.append('      count++;')
extra.append('      const div = document.createElement("div");')
extra.append('      div.className = "search-result-item";')
extra.append('      const preview = m.content.substring(0, 120) + (m.content.length > 120 ? "..." : "");')
extra.append('      div.innerHTML = "<span class=\\"sr-role\\">" + m.role + "</span> <span class=\\"sr-idx\\">#" + i + "</span><div class=\\"sr-preview\\">" + preview + "</div>";')
extra.append('      div.onclick = function() { scrollToMessage(i); closeSearchOverlay(); };')
extra.append('      results.appendChild(div);')
extra.append('    }')
extra.append('  });')
extra.append('  if (count === 0) results.innerHTML = "<div style=\\"padding:20px;text-align:center;color:var(--text-muted);font-size:13px;\\">No results found</div>";')
extra.append('}')
extra.append('function scrollToMessage(idx) {')
extra.append('  const el = document.getElementById("msg-" + idx);')
extra.append('  if (el) { el.scrollIntoView({ behavior: "smooth", block: "center" }); el.style.outline = "2px solid var(--accent-5)"; setTimeout(() => el.style.outline = "none", 2000); }')
extra.append('}')
extra.append('')
extra.append('// ---- Export ----')
extra.append('function exportChat(format) {')
extra.append('  const conv = conversations.find(c => c.id === currentConversationId);')
extra.append('  if (!conv || !conv.messages || conv.messages.length === 0) { showToast("No messages to export", "error"); return; }')
extra.append('  let output = "";')
extra.append('  if (format === "json") {')
extra.append('    output = JSON.stringify(conv.messages, null, 2);')
extra.append('  } else if (format === "markdown") {')
extra.append('    output = "# " + conv.name + "\\n\\n";')
extra.append('    conv.messages.forEach(m => { output += "**" + m.role + "**: " + m.content + "\\n\\n"; });')
extra.append('  } else {')
extra.append('    output = conv.name + "\\n" + "=".repeat(conv.name.length) + "\\n\\n";')
extra.append('    conv.messages.forEach(m => { output += m.role.toUpperCase() + ":\\n" + m.content + "\\n\\n"; });')
extra.append('  }')
extra.append('  const blob = new Blob([output], { type: "text/plain" });')
extra.append('  const url = URL.createObjectURL(blob);')
extra.append('  const a = document.createElement("a"); a.href = url; a.download = conv.name + "." + format; a.click();')
extra.append('  URL.revokeObjectURL(url);')
extra.append('  showToast("Exported as " + format, "success");')
extra.append('}')
extra.append('')
extra.append('function copyChatToClipboard() {')
extra.append('  const conv = conversations.find(c => c.id === currentConversationId);')
extra.append('  if (!conv || !conv.messages || conv.messages.length === 0) { showToast("No messages to copy", "error"); return; }')
extra.append('  let text = conv.name + "\\n\\n";')
extra.append('  conv.messages.forEach(m => { text += m.role + ": " + m.content + "\\n\\n"; });')
extra.append('  navigator.clipboard.writeText(text).then(() => showToast("Copied to clipboard!", "success"));')
extra.append('}')
extra.append('')
extra.append('// ---- Bookmark individual message ----')
extra.append('function toggleMessageBookmark(msgIdx) {')
extra.append('  if (!messages[msgIdx]) return;')
extra.append('  messages[msgIdx].bookmarked = !messages[msgIdx].bookmarked;')
extra.append('  saveCurrentConversation();')
extra.append('  showToast(messages[msgIdx].bookmarked ? "Message bookmarked!" : "Bookmark removed", "info");')
extra.append('}')
extra.append('')
extra.append('// ---- Session Info ----')
extra.append('function getSessionDuration() {')
extra.append('  const elapsed = Math.floor((Date.now() - sessionStart) / 1000);')
extra.append('  const h = Math.floor(elapsed / 3600);')
extra.append('  const m = Math.floor((elapsed % 3600) / 60);')
extra.append('  const s = elapsed % 60;')
extra.append('  return h + "h " + m + "m " + s + "s";')
extra.append('}')
extra.append('')
extra.append('// ---- Context Usage ----')
extra.append('function getContextUsage() {')
extra.append('  const total = parseInt(document.getElementById("contextLength").value) || 4096;')
extra.append('  let used = 0;')
extra.append('  messages.forEach(m => { used += Math.ceil(m.content.length / 3.5); });')
extra.append('  return { used: used, total: total, pct: Math.min(100, (used / total) * 100) };')
extra.append('}')
extra.append('')
extra.append('// ---- Message Context Menu ----')
extra.append('document.addEventListener("contextmenu", function(e) {')
extra.append('  const msgEl = e.target.closest(".message-wrapper");')
extra.append('  if (msgEl) {')
extra.append('    e.preventDefault();')
extra.append('    const idx = parseInt(msgEl.id.replace("msg-", ""));')
extra.append('    showContextMenu(e.clientX, e.clientY, idx);')
extra.append('  }')
extra.append('});')
extra.append('')
extra.append('function showContextMenu(x, y, idx) {')
extra.append('  const menu = document.getElementById("contextMenu");')
extra.append('  menu.style.left = x + "px"; menu.style.top = y + "px";')
extra.append('  menu.innerHTML = "";')
extra.append('  const items = [')
extra.append('    { icon: "&#x1F4CB;", text: "Copy", action: "copyMessage(" + idx + ")" },')

# Fix potential quoting issue: use a helper approach
extra.append('    { icon: "&#x2B50;", text: "Bookmark", action: "toggleMessageBookmark(" + idx + ")" },');

extra.append('    { icon: "&#x270F;\\uFE0F;", text: "Edit", action: "editMessage(" + idx + ")" },')
extra.append('    { icon: "&#x1F504;", text: "Resend", action: "resendMessage(" + idx + ")" },')
extra.append('    { icon: "&#x1F5D1;\\uFE0F;", text: "Delete", action: "deleteMessage(" + idx + ")" }')
extra.append('  ];')
extra.append('  items.forEach(item => {')
extra.append('    const div = document.createElement("div");')
extra.append('    div.className = "context-menu-item";')
extra.append('    div.innerHTML = "<span class=\\"ctx-icon\\">" + item.icon + "</span> " + item.text;')
extra.append('    div.onclick = function() { eval(item.action); closeContextMenu(); };')
extra.append('    menu.appendChild(div);')
extra.append('  });')
extra.append('  const sep = document.createElement("div");')
extra.append('  sep.className = "context-menu-separator";')
extra.append('  menu.appendChild(sep);')
extra.append('  const cancel = document.createElement("div");')
extra.append('  cancel.className = "context-menu-item";')
extra.append('  cancel.textContent = "Cancel";')
extra.append('  cancel.onclick = closeContextMenu;')
extra.append('  menu.appendChild(cancel);')
extra.append('  menu.classList.add("open");')
extra.append('}')
extra.append('')
extra.append('function closeContextMenu() { document.getElementById("contextMenu").classList.remove("open"); }')
extra.append('document.addEventListener("click", closeContextMenu);')
extra.append('')
extra.append('function deleteMessage(idx) {')
extra.append('  if (!confirm("Delete this message?")) return;')
extra.append('  messages.splice(idx, 1);')
extra.append('  renderMessages();')
extra.append('  saveCurrentConversation();')
extra.append('}')
extra.append('')
extra.append('// ---- Slash Commands ----')
extra.append('const SLASH_COMMANDS = [')
extra.append('  { name: "/help", desc: "Show available commands", action: function() { showToast("Commands: /help, /clear, /export, /theme, /model, /temp", "info"); } },')
extra.append('  { name: "/clear", desc: "Clear conversation", action: function() { if(confirm("Clear all messages?")) { messages = []; renderMessages(); saveCurrentConversation(); showToast("Conversation cleared","info"); } } },')
extra.append('  { name: "/export", desc: "Export conversation", action: function() { exportChat("markdown"); } },')
extra.append('  { name: "/theme", desc: "Change theme (try /theme ocean)", action: function() { openSettings(); } },')
extra.append('  { name: "/model", desc: "Switch model", action: function() { openSettings(); } },')
extra.append('  { name: "/temp", desc: "Set temperature", action: function() { const t = prompt("Temperature (0-2):"); if(t) { document.getElementById("temperature").value=t; updateRangeValue(document.getElementById("temperature"),"tempVal"); saveSettings(); } } }')
extra.append('];')
extra.append('')
extra.append('// ---- Session Timer ----')
extra.append('setInterval(function() {')
extra.append('  const dur = getSessionDuration();')
extra.append('  const ctx = getContextUsage();')
extra.append('  document.getElementById("statusBarLatency").textContent = dur;')
extra.append('  const ctxEl = document.querySelector(".conv-context-fill");')
extra.append('  if (ctxEl) ctxEl.style.width = ctx.pct + "%";')
extra.append('}, 5000);')
extra.append('')
extra.append('// ---- Keyboard shortcut for search overlay ----')
extra.append('document.addEventListener("keydown", function(e) {')
extra.append('  if (e.ctrlKey && e.shiftKey && e.key === "F") { e.preventDefault(); openSearchOverlay(); }')
extra.append('  if (e.key === "Escape") {')
extra.append('    closeSearchOverlay();')
extra.append('    closeContextMenu();')
extra.append('  }')
extra.append('});')
extra.append('')
extra.append('// ---- Add notification on model switch ----')
extra.append('const origSelectModel = selectModel;')
extra.append('selectModel = function(name) {')
extra.append('  origSelectModel(name);')
extra.append('  addNotification("Model Changed", "Switched to " + name);')
extra.append('}')
extra.append('')
extra.append('// ---- Handle paste events for file upload ----')
extra.append('document.getElementById("messageInput").addEventListener("paste", function(e) {')
extra.append('  const items = e.clipboardData.items;')
extra.append('  for (const item of items) {')
extra.append('    if (item.kind === "file") {')
extra.append('      const file = item.getAsFile();')
extra.append('      if (file) handleFiles([file]);')
extra.append('    }')
extra.append('  }')
extra.append('});')
extra.append('')
extra.append('// ---- Tag conversation ----')
extra.append('function tagConversation(id, tag) {')
extra.append('  const conv = conversations.find(c => c.id === id);')
extra.append('  if (conv) { conv.tag = tag; saveConversations(); renderConversationList(); }')
extra.append('}')
extra.append('')
extra.append('// ---- Scroll to bottom button ----')
extra.append('function scrollToBottom() {')
extra.append('  const c = document.getElementById("messagesContainer");')
extra.append('  c.scrollTop = c.scrollHeight;')
extra.append('}')
extra.append('')
extra.append('// ---- Init: Add context indicator to sidebar ----')
extra.append('const origNewConv = newConversation;')
extra.append('newConversation = function() {')
extra.append('  origNewConv();')
extra.append('  addNotification("New Chat", "Conversation created");')
extra.append('}')
extra.append('')
extra.append('console.log("SXIGOai V2.0 initialized");')
extra.append('console.log("Features: glassmorphism, RGB effects, voice input, streaming, search, bookmarks, compare, export, reactions, notifications, dashboard, custom themes, file attach");')
extra.append('</script>')

# Insert before </body>
insertion = '\n'.join(extra)
content = ''.join(lines)
content = content.replace('</body>', insertion + '\n</body>')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n')
print(f'Final total lines: {line_count}')
