path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

lines = []
def L(s):
    lines.append(s)

# ~1000 more lines of CSS + JS
L('<style>')
L('/* === V2.0 Complete Keyframe Library === */')
L('@keyframes fadeIn { 0% { opacity: 0; } 100% { opacity: 1; } }')
L('@keyframes fadeOut { 0% { opacity: 1; } 100% { opacity: 0; } }')
L('@keyframes slideInUp { 0% { transform: translateY(20px); opacity: 0; } 100% { transform: translateY(0); opacity: 1; } }')
L('@keyframes slideInDown { 0% { transform: translateY(-20px); opacity: 0; } 100% { transform: translateY(0); opacity: 1; } }')
L('@keyframes slideInLeft { 0% { transform: translateX(20px); opacity: 0; } 100% { transform: translateX(0); opacity: 1; } }')
L('@keyframes slideInRight { 0% { transform: translateX(-20px); opacity: 0; } 100% { transform: translateX(0); opacity: 1; } }')
L('@keyframes scaleIn { 0% { transform: scale(0.8); opacity: 0; } 100% { transform: scale(1); opacity: 1; } }')
L('@keyframes scaleOut { 0% { transform: scale(1); opacity: 1; } 100% { transform: scale(0.8); opacity: 0; } }')
L('@keyframes rotateIn { 0% { transform: rotate(-180deg); opacity: 0; } 100% { transform: rotate(0); opacity: 1; } }')
L('@keyframes rotateOut { 0% { transform: rotate(0); opacity: 1; } 100% { transform: rotate(180deg); opacity: 0; } }')
L('@keyframes flipInX { 0% { transform: perspective(400px) rotateX(90deg); opacity: 0; } 40% { transform: perspective(400px) rotateX(-20deg); } 60% { transform: perspective(400px) rotateX(10deg); } 80% { transform: perspective(400px) rotateX(-5deg); } 100% { transform: perspective(400px) rotateX(0); opacity: 1; } }')
L('@keyframes flipInY { 0% { transform: perspective(400px) rotateY(90deg); opacity: 0; } 40% { transform: perspective(400px) rotateY(-20deg); } 60% { transform: perspective(400px) rotateY(10deg); } 80% { transform: perspective(400px) rotateY(-5deg); } 100% { transform: perspective(400px) rotateY(0); opacity: 1; } }')
L('@keyframes bounceIn { 0% { transform: scale(0.1); opacity: 0; } 60% { transform: scale(1.2); opacity: 1; } 80% { transform: scale(0.9); } 100% { transform: scale(1); } }')
L('@keyframes bounceOut { 0% { transform: scale(1); } 25% { transform: scale(0.95); } 50% { opacity: 1; transform: scale(1.1); } 100% { opacity: 0; transform: scale(0.3); } }')
L('@keyframes bounceInUp { 0% { opacity: 0; transform: translateY(2000px); } 60% { opacity: 1; transform: translateY(-30px); } 80% { transform: translateY(10px); } 100% { transform: translateY(0); } }')
L('@keyframes bounceInDown { 0% { opacity: 0; transform: translateY(-2000px); } 60% { opacity: 1; transform: translateY(30px); } 80% { transform: translateY(-10px); } 100% { transform: translateY(0); } }')
L('@keyframes bounceInLeft { 0% { opacity: 0; transform: translateX(-2000px); } 60% { opacity: 1; transform: translateX(30px); } 80% { transform: translateX(-10px); } 100% { transform: translateX(0); } }')
L('@keyframes bounceInRight { 0% { opacity: 0; transform: translateX(2000px); } 60% { opacity: 1; transform: translateX(-30px); } 80% { transform: translateX(10px); } 100% { transform: translateX(0); } }')
L('@keyframes lightSpeedIn { 0% { transform: translateX(100%) skewX(-30deg); opacity: 0; } 60% { transform: translateX(-20%) skewX(30deg); opacity: 1; } 80% { transform: translateX(0%) skewX(-15deg); } 100% { transform: translateX(0%) skewX(0); } }')
L('@keyframes lightSpeedOut { 0% { transform: translateX(0%) skewX(0); opacity: 1; } 100% { transform: translateX(100%) skewX(-30deg); opacity: 0; } }')
L('@keyframes rollIn { 0% { opacity: 0; transform: translateX(-100%) rotate(-120deg); } 100% { opacity: 1; transform: translateX(0px) rotate(0deg); } }')
L('@keyframes rollOut { 0% { opacity: 1; transform: translateX(0px) rotate(0deg); } 100% { opacity: 0; transform: translateX(100%) rotate(120deg); } }')
L('@keyframes zoomIn { 0% { opacity: 0; transform: scale3d(0.3, 0.3, 0.3); } 50% { opacity: 1; } }')
L('@keyframes zoomOut { 0% { opacity: 1; } 50% { opacity: 0; transform: scale3d(0.3, 0.3, 0.3); } 100% { opacity: 0; } }')
L('@keyframes hinge { 0% { transform-origin: top left; animation-timing-function: ease-in-out; } 20%,60% { transform: rotate(80deg); transform-origin: top left; } 40% { transform: rotate(60deg); } 80% { transform: rotate(60deg) translateY(0); opacity: 1; } 100% { transform: translateY(700px); opacity: 0; } }')
L('@keyframes jackInTheBox { 0% { opacity: 0; transform: scale(0.1) rotate(30deg); transform-origin: center bottom; } 50% { transform: rotate(-10deg); } 70% { transform: rotate(3deg); } 100% { opacity: 1; transform: scale(1); } }')
L('@keyframes attentionBounce { 0%,100% { transform: translateY(0); } 10%,30%,50%,70%,90% { transform: translateY(-10px); } 20%,40%,60%,80% { transform: translateY(10px); } }')
L('@keyframes attentionFlash { 0%,50%,100% { opacity: 1; } 25%,75% { opacity: 0; } }')
L('@keyframes attentionPulse { 0%,100% { transform: scale(1); } 50% { transform: scale(1.05); } }')
L('@keyframes attentionRubberBand { 0%,100% { transform: scale(1); } 30% { transform: scaleX(1.25) scaleY(0.75); } 40% { transform: scaleX(0.75) scaleY(1.25); } 60% { transform: scaleX(1.15) scaleY(0.85); } }')
L('@keyframes attentionShake { 0%,100% { transform: translateX(0); } 10%,30%,50%,70%,90% { transform: translateX(-10px); } 20%,40%,60%,80% { transform: translateX(10px); } }')
L('@keyframes attentionHeadShake { 0%,100% { transform: translateX(0) rotate(0); } 6.5% { transform: translateX(-6px) rotateY(-9deg); } 18.5% { transform: translateX(5px) rotateY(7deg); } 31.5% { transform: translateX(-3px) rotateY(-5deg); } 43.5% { transform: translateX(2px) rotateY(3deg); } 50% { transform: translateX(0) rotate(0); } }')
L('@keyframes attentionSwing { 20% { transform: rotate(15deg); } 40% { transform: rotate(-10deg); } 60% { transform: rotate(5deg); } 80% { transform: rotate(-5deg); } 100% { transform: rotate(0deg); } }')
L('@keyframes attentionTada { 0%,100% { transform: scale(1) rotate(0); } 10%,20% { transform: scale(0.9) rotate(-3deg); } 30%,50%,70%,90% { transform: scale(1.1) rotate(3deg); } 40%,60%,80% { transform: scale(1.1) rotate(-3deg); } }')
L('@keyframes attentionWobble { 0%,100% { transform: translateX(0%); transform-origin: top; } 15% { transform: translateX(-30%) rotate(6deg); } 30% { transform: translateX(15%) rotate(-3deg); } 45% { transform: translateX(-15%) rotate(3deg); } 60% { transform: translateX(10%) rotate(-2deg); } 75% { transform: translateX(-5%) rotate(1deg); } }')
L('@keyframes attentionJello { 0%,100% { transform: scaleX(1); } 25% { transform: scaleX(1.05); } 50% { transform: scaleX(0.95); } 75% { transform: scaleX(1.05); } }')

L('<style>')
L('/* === V2.0 CSS Animation Utility Classes === */')
animations = ['fadeIn', 'fadeOut', 'slideInUp', 'slideInDown', 'slideInLeft', 'slideInRight',
              'scaleIn', 'scaleOut', 'rotateIn', 'rotateOut', 'flipInX', 'flipInY',
              'bounceIn', 'bounceOut', 'bounceInUp', 'bounceInDown', 'bounceInLeft', 'bounceInRight',
              'lightSpeedIn', 'lightSpeedOut', 'rollIn', 'rollOut', 'zoomIn', 'zoomOut',
              'hinge', 'jackInTheBox',
              'attentionBounce', 'attentionFlash', 'attentionPulse', 'attentionRubberBand',
              'attentionShake', 'attentionHeadShake', 'attentionSwing', 'attentionTada',
              'attentionWobble', 'attentionJello']
for a in animations:
    name = a[0].lower() + a[1:] if a[0].isupper() else a
    L(f'.animate__{name} {{ animation-name: {a}; animation-duration: 1s; animation-fill-mode: both; }}')
    L(f'.animate__{name}-fast {{ animation-name: {a}; animation-duration: 0.5s; animation-fill-mode: both; }}')
    L(f'.animate__{name}-slow {{ animation-name: {a}; animation-duration: 2s; animation-fill-mode: both; }}')
    L(f'.animate__{name}-repeat {{ animation-name: {a}; animation-duration: 1s; animation-iteration-count: infinite; }}')

L('</style>')

# JS feature: comprehensive animation helper
L('<script>')
L('// ===== SXIGOai V2.0 Animation System =====')
L('function animateElement(el, animationName, duration) {')
L('  duration = duration || "1s";')
L('  el.style.animationName = animationName;')
L('  el.style.animationDuration = duration;')
L('  el.style.animationFillMode = "both";')
L('  el.addEventListener("animationend", function handler() {')
L('    el.style.animationName = "";')
L('    el.removeEventListener("animationend", handler);')
L('  });')
L('}')
L('')
L('function animateCSS(el, animation, prefix) {')
L('  prefix = prefix || "animate__";')
L('  return new Promise(function(resolve) {')
L('    const animationName = prefix + animation;')
L('    el.classList.add(animationName);')
L('    function handleAnimationEnd() {')
L('      el.classList.remove(animationName);')
L('      resolve();')
L('    }')
L('    el.addEventListener("animationend", handleAnimationEnd, { once: true });')
L('  });')
L('}')
L('')
L('function shakeElement(el) { animateElement(el, "attentionShake", "0.5s"); }')
L('function pulseElement(el) { animateElement(el, "attentionPulse", "1s"); }')
L('function bounceElement(el) { animateElement(el, "bounceIn", "0.6s"); }')
L('function flashElement(el) { animateElement(el, "attentionFlash", "0.8s"); }')
L('function fadeInElement(el) { animateElement(el, "fadeIn", "0.3s"); }')
L('function slideInElement(el) { animateElement(el, "slideInUp", "0.4s"); }')
L('')
L('// ---- Confetti effect ----')
L('function showConfetti() {')
L('  for (let i = 0; i < 50; i++) {')
L('    const confetti = document.createElement("div");')
L('    confetti.style.cssText = "position:fixed;width:8px;height:8px;z-index:9999;pointer-events:none;top:-10px;left:" + (Math.random() * 100) + "vw;background:" + ["#ff6b6b","#ffd93d","#6bcb77","#4d96ff","#9b59b6","#ff9ff3","#feca57"][Math.floor(Math.random() * 7)] + ";border-radius:" + (Math.random() > 0.5 ? "50%" : "2px") + ";animation:confetti-fall " + (2 + Math.random() * 3) + "s ease-out forwards;animation-delay:" + (Math.random() * 2) + "s;";')
L('    document.body.appendChild(confetti);')
L('    setTimeout(function() { confetti.remove(); }, 5000);')
L('  }')
L('}')
L('')
L('// ---- Typewriter effect ----')
L('function typewriterEffect(el, text, speed) {')
L('  speed = speed || 30;')
L('  el.textContent = "";')
L('  let i = 0;')
L('  function type() {')
L('    if (i < text.length) {')
L('      el.textContent += text.charAt(i);')
L('      i++;')
L('      setTimeout(type, speed);')
L('    }')
L('  }')
L('  type();')
L('}')
L('')
L('// ---- Utility: debounce ----')
L('function debounce(func, wait) {')
L('  let timeout;')
L('  return function executedFunction() {')
L('    const context = this;')
L('    const args = arguments;')
L('    clearTimeout(timeout);')
L('    timeout = setTimeout(function() { func.apply(context, args); }, wait || 300);')
L('  };')
L('}')
L('')
L('// ---- Utility: throttle ----')
L('function throttle(func, limit) {')
L('  let inThrottle;')
L('  return function() {')
L('    const args = arguments;')
L('    const context = this;')
L('    if (!inThrottle) {')
L('      func.apply(context, args);')
L('      inThrottle = true;')
L('      setTimeout(function() { inThrottle = false; }, limit || 300);')
L('    }')
L('  };')
L('}')
L('')
L('// ---- Format bytes ----')
L('function formatBytes(bytes) {')
L('  if (bytes === 0) return "0 B";')
L('  const k = 1024;')
L('  const sizes = ["B", "KB", "MB", "GB"];')
L('  const i = Math.floor(Math.log(bytes) / Math.log(k));')
L('  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];')
L('}')
L('')
L('// ---- Detect browser ----')
L('function detectBrowser() {')
L('  const ua = navigator.userAgent;')
L('  if (ua.includes("Chrome")) return "Chrome";')
L('  if (ua.includes("Firefox")) return "Firefox";')
L('  if (ua.includes("Safari")) return "Safari";')
L('  if (ua.includes("Edge")) return "Edge";')
L('  return "Unknown";')
L('}')
L('')
L('// ---- OS detection ----')
L('function detectOS() {')
L('  const platform = navigator.platform;')
L('  if (platform.includes("Win")) return "Windows";')
L('  if (platform.includes("Mac")) return "macOS";')
L('  if (platform.includes("Linux")) return "Linux";')
L('  if (platform.includes("iPhone") || platform.includes("iPad")) return "iOS";')
L('  if (platform.includes("Android")) return "Android";')
L('  return "Unknown";')
L('}')
L('')
L('// ---- SXIGOai V2.0 browser and OS info ----')
L('console.log("Browser:", detectBrowser());')
L('console.log("OS:", detectOS());')
L('console.log("Features: Glassmorphism, RGB Effects, Streaming, Voice, Themes, Dashboard, Compare, Bookmarks, Search, Export, Notifications, File Attach, Code Playground, Command Palette, Fullscreen, Auto Backup, Accessibility");')
L('')
L('</script>')

insertion = '\n'.join(lines)
content = content.replace('</body>', insertion + '\n</body>')

last_body = content.rfind('</body>')
last_html = content.rfind('</html>')
if last_body > last_html:
    content = content[:last_body + 7] + '\n</html>\n'

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n')
print(f'Total lines: {line_count}')
print(f'Target: 6200')
print(f'Remaining: {6200 - line_count}')
