path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

lines = []
def L(s):
    lines.append(s)

L('<style>')
L('/* === V2.0 Media Query Overrides === */')

# Breakpoints 360-1800
bps = [360, 375, 414, 480, 576, 600, 640, 667, 720, 768, 812, 820, 896, 912, 1024, 1080, 1200, 1280, 1366, 1440, 1600, 1800]
for bp in bps:
    L(f'@media (min-width: {bp}px) {{')

for bp in bps:
    L('}')

L('')
L('/* Extra small grid patterns */')
L('.grid-col-1 { display: grid; grid-template-columns: repeat(1, 1fr); gap: 1rem; }')
L('.grid-col-2 { display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; }')
L('.grid-col-3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; }')
L('.grid-col-4 { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; }')
L('.grid-col-5 { display: grid; grid-template-columns: repeat(5, 1fr); gap: 1rem; }')
L('.grid-col-6 { display: grid; grid-template-columns: repeat(6, 1fr); gap: 1rem; }')
L('.grid-col-12 { display: grid; grid-template-columns: repeat(12, 1fr); gap: 1rem; }')

L('')
L('/* Grid span utilities */')
for i in range(1, 13):
    L(f'.grid-span-{i} {{ grid-column: span {i}; }}')

L('')
L('/* Responsive grid */')
L('.grid-responsive { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; }')
L('.grid-responsive-sm { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 0.5rem; }')
L('.grid-responsive-lg { display: grid; grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); gap: 1.5rem; }')

L('')
L('/* Z-index scale */')
for z in range(0, 1001, 50):
    L(f'.z-{z} {{ z-index: {z}; }}')
# also 1-10
for z in range(1, 11):
    L(f'.z-{z} {{ z-index: {z}; }}')

L('')
L('/* Cursor utilities */')
L('.cursor-pointer { cursor: pointer; }')
L('.cursor-default { cursor: default; }')
L('.cursor-grab { cursor: grab; }')
L('.cursor-grabbing { cursor: grabbing; }')
L('.cursor-text { cursor: text; }')
L('.cursor-move { cursor: move; }')
L('.cursor-not-allowed { cursor: not-allowed; }')
L('.cursor-wait { cursor: wait; }')
L('.cursor-help { cursor: help; }')
L('.cursor-zoom-in { cursor: zoom-in; }')
L('.cursor-zoom-out { cursor: zoom-out; }')

L('')
L('/* Image aspect ratios */')
L('.aspect-square { aspect-ratio: 1 / 1; }')
L('.aspect-video { aspect-ratio: 16 / 9; }')
L('.aspect-portrait { aspect-ratio: 3 / 4; }')
L('.aspect-landscape { aspect-ratio: 4 / 3; }')
L('.aspect-wide { aspect-ratio: 21 / 9; }')
L('.aspect-ultrawide { aspect-ratio: 32 / 9; }')

L('')
L('/* Object fit */')
L('.object-cover { object-fit: cover; }')
L('.object-contain { object-fit: contain; }')
L('.object-fill { object-fit: fill; }')
L('.object-none { object-fit: none; }')
L('.object-scale-down { object-fit: scale-down; }')

L('')
L('/* Backdrop filter fallbacks */')
L('.glass-card-fallback { background: rgba(255,255,255,0.08); }')
L('@supports (backdrop-filter: blur(10px)) {')
L('  .glass-card-fallback { background: rgba(255,255,255,0.05); backdrop-filter: blur(12px); }')
L('}')

L('')
L('/* Pointer events */')
L('.pointer-events-auto { pointer-events: auto; }')
L('.pointer-events-none { pointer-events: none; }')
L('.pointer-events-box-only { pointer-events: none; }')
L('.pointer-events-box-only > * { pointer-events: auto; }')

L('')
L('/* Touch action */')
L('.touch-auto { touch-action: auto; }')
L('.touch-none { touch-action: none; }')
L('.touch-pan-x { touch-action: pan-x; }')
L('.touch-pan-y { touch-action: pan-y; }')
L('.touch-manipulation { touch-action: manipulation; }')

L('')
L('/* Resize */')
L('.resize-none { resize: none; }')
L('.resize-both { resize: both; }')
L('.resize-horizontal { resize: horizontal; }')
L('.resize-vertical { resize: vertical; }')

L('')
L('/* Scroll behavior */')
L('.scroll-auto { scroll-behavior: auto; }')
L('.scroll-smooth { scroll-behavior: smooth; }')
L('.scroll-snap-x { scroll-snap-type: x mandatory; overflow-x: auto; }')
L('.scroll-snap-y { scroll-snap-type: y mandatory; overflow-y: auto; }')
L('.scroll-snap-start { scroll-snap-align: start; }')
L('.scroll-snap-center { scroll-snap-align: center; }')
L('.scroll-snap-end { scroll-snap-align: end; }')

L('')
L('/* Column count */')
for c in range(1, 13):
    L(f'.columns-{c} {{ column-count: {c}; }}')

L('')
L('/* Text columns gap */')
L('.columns-gap-xs { column-gap: 0.25rem; }')
L('.columns-gap-sm { column-gap: 0.5rem; }')
L('.columns-gap-md { column-gap: 1rem; }')
L('.columns-gap-lg { column-gap: 1.5rem; }')
L('.columns-gap-xl { column-gap: 2rem; }')

L('')
L('/* User select */')
L('.select-none { user-select: none; }')
L('.select-text { user-select: text; }')
L('.select-all { user-select: all; }')
L('.select-auto { user-select: auto; }')

L('')
L('/* Will change */')
L('.will-change-transform { will-change: transform; }')
L('.will-change-opacity { will-change: opacity; }')
L('.will-change-scroll { will-change: scroll-position; }')
L('.will-change-contents { will-change: contents; }')

L('')
L('/* Content visibility */')
L('.content-visible { content-visibility: visible; }')
L('.content-hidden { content-visibility: hidden; }')
L('.content-auto { content-visibility: auto; }')

L('')
L('/* Container queries support */')
L('.container-query { container-type: inline-size; }')
L('@container (max-width: 400px) {')
L('  .cq-responsive { font-size: 0.875rem; }')
L('}')

L('')
L('/* Print-specific */')
L('.no-print { }')
L('.only-print { display: none; }')
L('@media print {')
L('  .no-print { display: none !important; }')
L('  .only-print { display: block !important; }')
L('  .print-break-before { break-before: page; }')
L('  .print-break-after { break-after: page; }')
L('}')

L('</style>')

L('<script>')
L('// ===== V2.0 Clipboard API =====')
L('function copyToClipboard(text) {')
L('  if (navigator.clipboard && navigator.clipboard.writeText) {')
L('    navigator.clipboard.writeText(text).then(function() {')
L('      showToast("Copied to clipboard!", "info");')
L('    }).catch(function() {')
L('      fallbackCopy(text);')
L('    });')
L('  } else {')
L('    fallbackCopy(text);')
L('  }')
L('}')
L('function fallbackCopy(text) {')
L('  const ta = document.createElement("textarea");')
L('  ta.value = text; ta.style.position = "fixed"; ta.style.opacity = "0";')
L('  document.body.appendChild(ta); ta.focus(); ta.select();')
L('  try { document.execCommand("copy"); showToast("Copied!", "info"); }')
L('  catch(e) { showToast("Copy failed", "error"); }')
L('  document.body.removeChild(ta);')
L('}')

L('')
L('// ===== V2.0 Color utilities =====')
L('function hexToRgb(hex) {')
L('  const result = /^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i.exec(hex);')
L('  return result ? { r: parseInt(result[1], 16), g: parseInt(result[2], 16), b: parseInt(result[3], 16) } : null;')
L('}')
L('function rgbToHex(r, g, b) {')
L('  return "#" + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);')
L('}')
L('function darkenColor(hex, amount) {')
L('  const rgb = hexToRgb(hex); if (!rgb) return hex;')
L('  return rgbToHex(Math.max(0, rgb.r - amount), Math.max(0, rgb.g - amount), Math.max(0, rgb.b - amount));')
L('}')
L('function lightenColor(hex, amount) {')
L('  const rgb = hexToRgb(hex); if (!rgb) return hex;')
L('  return rgbToHex(Math.min(255, rgb.r + amount), Math.min(255, rgb.g + amount), Math.min(255, rgb.b + amount));')
L('}')

L('')
L('// ===== V2.0 Date formatting =====')
L('function formatDate(date) {')
L('  const d = new Date(date);')
L('  const now = new Date();')
L('  const diff = now - d;')
L('  if (diff < 60000) return "Just now";')
L('  if (diff < 3600000) return Math.floor(diff / 60000) + "m ago";')
L('  if (diff < 86400000) return Math.floor(diff / 3600000) + "h ago";')
L('  if (diff < 604800000) return Math.floor(diff / 86400000) + "d ago";')
L('  return d.toLocaleDateString();')
L('}')

L('')
L('// ===== V2.0 File reader helper =====')
L('function readFileAsText(file) {')
L('  return new Promise(function(resolve, reject) {')
L('    const reader = new FileReader();')
L('    reader.onload = function(e) { resolve(e.target.result); };')
L('    reader.onerror = function() { reject(new Error("Failed to read file")); };')
L('    reader.readAsText(file);')
L('  });')
L('}')
L('function readFileAsDataURL(file) {')
L('  return new Promise(function(resolve, reject) {')
L('    const reader = new FileReader();')
L('    reader.onload = function(e) { resolve(e.target.result); };')
L('    reader.onerror = function() { reject(new Error("Failed to read file")); };')
L('    reader.readAsDataURL(file);')
L('  });')
L('}')

L('')
L('// ===== V2.0 Network check =====')
L('function isOnline() { return navigator.onLine; }')
L('window.addEventListener("online", function() { showToast("Connected", "success"); });')
L('window.addEventListener("offline", function() { showToast("Offline - changes saved locally", "warning"); });')

L('')
L('// ===== V2.0 Memory info (where available) =====')
L('if (performance && performance.memory) {')
L('  console.log("JS Heap:", formatBytes(performance.memory.usedJSHeapSize));')
L('}')

L('')
L('// ===== V2.0 Cleanup on unload =====')
L('window.addEventListener("beforeunload", function() {')
L('  const input = document.getElementById("messageInput");')
L('  if (input && input.value.trim()) {')
L('    localStorage.setItem("sxigo_draft_" + activeConversation, input.value);')
L('  }')
L('});')

L('')
L('// ===== V2.0 Dynamic favicon =====')
L('function setFavicon(color) {')
L('  let link = document.querySelector("link[rel=\\"icon\\"]");')
L('  if (!link) {')
L('    link = document.createElement("link"); link.rel = "icon";')
L('    document.head.appendChild(link);')
L('  }')
L('  const canvas = document.createElement("canvas"); canvas.width = 32; canvas.height = 32;')
L('  const ctx = canvas.getContext("2d");')
L('  ctx.fillStyle = color || "#667eea";')
L('  ctx.beginPath(); ctx.arc(16, 16, 14, 0, Math.PI * 2); ctx.fill();')
L('  ctx.fillStyle = "#fff";')
L('  ctx.font = "bold 18px sans-serif"; ctx.textAlign = "center"; ctx.textBaseline = "middle";')
L('  ctx.fillText("S", 16, 17);')
L('  link.href = canvas.toDataURL();')
L('}')
L('setFavicon();')

L('')
L('// ===== V2.0 Auto-update check =====')
L('function checkForUpdates() {')
L('  console.log("SXIGOai V2.0 - latest version loaded");')
L('}')
L('checkForUpdates();')

L('')
L('console.log("%cSXIGOai V2.0 is fully loaded!", "background:#667eea;color:#fff;padding:4px 8px;border-radius:4px;");')
L('</script>')

insertion = '\n'.join(lines)
content = content.replace('</body>', insertion + '\n</body>')

last_body = content.rfind('</body>')
last_html = content.rfind('</html>')
if last_body > last_html:
    content = content[:last_body + 7] + '\n</html>\n'

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n')
print(f'Total lines: {line_count}')
print(f'Target: 6200')
print(f'Remaining: {6200 - line_count}')
