path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

extra = []
def A(s):
    extra.append(s)

# ===== MORE HTML PANELS =====
A('')
A('<!-- Context Usage Bar -->')
A('<div class="context-usage" id="contextUsageBar">')
A('  <span>&#x1F4CA; Context</span>')
A('  <div class="cu-bar"><div class="cu-fill" id="contextUsageFill" style="width:0%"></div></div>')
A('  <span id="contextUsageText">0 / 4096</span>')
A('</div>')

A('')
A('<!-- Scroll To Bottom Button -->')
A('<button class="scroll-to-bottom-btn" id="scrollToBottomBtn" onclick="scrollToBottom()">&#x2193;</button>')

A('')
A('<!-- Typing Status -->')
A('<div class="typing-status" id="typingStatus">SXIGOai is typing...</div>')

A('')
A('<!-- Command Palette -->')
A('<div class="command-palette" id="commandPalette">')
A('  <input type="text" id="cpInput" placeholder="Type a command..." onkeydown="handleCommandPaletteKey(event)">')
A('  <div class="cp-results" id="cpResults"></div>')
A('</div>')

A('')
A('<!-- Context Menu -->')
A('<div class="context-menu" id="contextMenu"></div>')

A('')
A('<!-- Emoji Picker -->')
A('<div class="modal-overlay" id="emojiPickerOverlay" onclick="closeEmojiPicker()">')
A('  <div class="modal" style="max-width:320px;" onclick="event.stopPropagation()">')
A('    <div class="modal-header"><h3>&#x1F600; Emoji</h3><button class="modal-close-btn" onclick="closeEmojiPicker()">&#x2716;</button></div>')
A('    <div class="emoji-picker-grid" id="emojiGrid"></div>')
A('  </div>')
A('</div>')

# ===== JS FOR ALL FEATURES =====
A('')
A('<script>')
A('// ===== V2.0 Extended Features =====')
A('')
A('// ---- Context Usage ----')
A('function updateContextUsage() {')
A('  const ctx = getContextUsage();')
A('  const fill = document.getElementById("contextUsageFill");')
A('  const text = document.getElementById("contextUsageText");')
A('  if (fill) fill.style.width = ctx.pct + "%";')
A('  if (text) text.textContent = Math.round(ctx.used) + " / " + ctx.total;')
A('}')
A('setInterval(updateContextUsage, 3000);')
A('')
A('// ---- Scroll To Bottom ----')
A('const msgContainer = document.getElementById("messagesContainer");')
A('if (msgContainer) {')
A('  msgContainer.addEventListener("scroll", function() {')
A('    const btn = document.getElementById("scrollToBottomBtn");')
A('    const isNearBottom = this.scrollHeight - this.scrollTop - this.clientHeight < 100;')
A('    if (btn) btn.classList.toggle("visible", !isNearBottom);')
A('  });')
A('}')
A('')
A('// ---- Command Palette ----')
A('const COMMANDS = [')
A('  { icon: "&#x1F4DD;", title: "New Chat", desc: "Start a new conversation", shortcut: "Ctrl+N", action: newConversation },')
A('  { icon: "&#x1F50D;", title: "Search Messages", desc: "Search in current conversation", shortcut: "Ctrl+F", action: searchMessages },')
A('  { icon: "&#x1F4E5;", title: "Pull Model", desc: "Download a new model", shortcut: "Ctrl+P", action: openPullModel },')
A('  { icon: "&#x2699;\\uFE0F;", title: "Settings", desc: "Open settings panel", shortcut: "Ctrl+,", action: openSettings },')
A('  { icon: "&#x1F4CA;", title: "Dashboard", desc: "View session statistics", shortcut: "", action: openDashboard },')
A('  { icon: "&#x1F514;", title: "Notifications", desc: "View notifications", shortcut: "", action: toggleNotifications },')
A('  { icon: "&#x1F4CB;", title: "Compare Models", desc: "Compare responses from two models", shortcut: "", action: openCompare },')
A('  { icon: "&#x1F3A4;", title: "Voice Input", desc: "Toggle voice recognition", shortcut: "Ctrl+M", action: toggleVoice },')
A('  { icon: "&#x2B50;", title: "Bookmarks", desc: "View bookmarked messages", shortcut: "", action: toggleBookmarksPanel },')
A('  { icon: "&#x1F4C4;", title: "Export Chat", desc: "Export conversation", shortcut: "", action: function() { exportChat("markdown"); } },')
A('  { icon: "&#x1F504;", title: "Refresh Models", desc: "Refresh available models list", shortcut: "", action: refreshModels },')
A('  { icon: "&#x2328;", title: "Keyboard Shortcuts", desc: "View all keyboard shortcuts", shortcut: "", action: openShortcuts },')
A('  { icon: "&#x1F3D7;\\uFE0F;", title: "Toggle Sidebar", desc: "Show/hide sidebar", shortcut: "Ctrl+B", action: toggleSidebar },')
A('  { icon: "&#x1F50C;", title: "Toggle Dark Mode", desc: "Toggle dark room overlay", shortcut: "", action: function() { document.getElementById("darkRoomOverlay").classList.toggle("open"); } }')
A('];')
A('')
A('document.addEventListener("keydown", function(e) {')
A('  if (e.ctrlKey && e.shiftKey && e.key === "P") {')
A('    e.preventDefault();')
A('    openCommandPalette();')
A('  }')
A('});')
A('')
A('function openCommandPalette() {')
A('  document.getElementById("commandPalette").classList.add("open");')
A('  document.getElementById("cpInput").value = "";')
A('  document.getElementById("cpInput").focus();')
A('  renderCommands("");')
A('}')
A('function closeCommandPalette() { document.getElementById("commandPalette").classList.remove("open"); }')
A('')
A('function renderCommands(filter) {')
A('  const results = document.getElementById("cpResults");')
A('  results.innerHTML = "";')
A('  const filtered = COMMANDS.filter(c => c.title.toLowerCase().includes(filter.toLowerCase()) || c.desc.toLowerCase().includes(filter.toLowerCase()));')
A('  filtered.forEach(cmd => {')
A('    const div = document.createElement("div");')
A('    div.className = "cp-item";')
A('    div.innerHTML = "<span class=\\"cp-icon\\">" + cmd.icon + "</span><div><div class=\\"cp-title\\">" + cmd.title + "</div><div class=\\"cp-desc\\">" + cmd.desc + "</div></div>" + (cmd.shortcut ? "<span class=\\"cp-shortcut\\">" + cmd.shortcut + "</span>" : "");')
A('    div.onclick = function() { closeCommandPalette(); cmd.action(); };')
A('    results.appendChild(div);')
A('  });')
A('  if (filtered.length === 0) results.innerHTML = "<div style=\\"padding:20px;text-align:center;color:var(--text-muted);font-size:13px;\\">No commands found</div>";')
A('}')
A('')
A('function handleCommandPaletteKey(e) {')
A('  if (e.key === "Escape") closeCommandPalette();')
A('  if (e.key === "Enter") {')
A('    const first = document.querySelector("#cpResults .cp-item");')
A('    if (first) { first.click(); }')
A('  }')
A('  renderCommands(e.target.value);')
A('}')
A('')
A('// ---- Emoji Picker ----')
A('const EMOJIS = ["&#x1F600;","&#x1F601;","&#x1F602;","&#x1F603;","&#x1F604;","&#x1F605;","&#x1F606;","&#x1F609;","&#x1F60A;","&#x1F60B;","&#x1F60C;","&#x1F60D;","&#x1F60E;","&#x1F60F;","&#x1F610;","&#x1F611;","&#x1F612;","&#x1F613;","&#x1F614;","&#x1F615;","&#x1F616;","&#x1F617;","&#x1F618;","&#x1F619;","&#x1F61A;","&#x1F61B;","&#x1F61C;","&#x1F61D;","&#x1F61E;","&#x1F61F;","&#x1F620;","&#x1F621;","&#x1F622;","&#x1F623;","&#x1F624;","&#x1F625;","&#x2764;\\uFE0F;","&#x1F49B;","&#x1F49A;","&#x1F499;","&#x1F49C;","&#x1F5A4;","&#x1F494;","&#x1F495;","&#x1F49E;","&#x1F493;","&#x1F497;","&#x1F496;","&#x1F498;","&#x1F4AF;","&#x1F4AA;","&#x1F44D;","&#x1F44E;","&#x1F44C;","&#x1F44F;","&#x1F44A;","&#x1F48B;","&#x1F48C;","&#x1F389;","&#x1F388;","&#x1F380;","&#x2B50;","&#x1F31F;","&#x1F525;","&#x1F4A1;","&#x1F4A2;","&#x1F4A3;","&#x1F4A4;","&#x1F4A5;","&#x1F4A6;","&#x1F4A7;","&#x1F4A8;","&#x1F4A9;","&#x1F4AA;"];')
A('')
A('function openEmojiPicker() {')
A('  const grid = document.getElementById("emojiGrid");')
A('  grid.innerHTML = "";')
A('  EMOJIS.forEach(e => {')
A('    const btn = document.createElement("div");')
A('    btn.className = "ep-emoji";')
A('    btn.innerHTML = e;')
A('    btn.onclick = function() {')
A('      const input = document.getElementById("messageInput");')
A('      input.value += e.replace(/&#x([0-9A-F]+);/gi, function(_, code) { return String.fromCodePoint(parseInt(code, 16)); });')
A('      autoResize(input);')
A('      input.focus();')
A('      closeEmojiPicker();')
A('    };')
A('    grid.appendChild(btn);')
A('  });')
A('  document.getElementById("emojiPickerOverlay").classList.add("open");')
A('}')
A('function closeEmojiPicker() { document.getElementById("emojiPickerOverlay").classList.remove("open"); }')
A('')
A('// ---- Fullscreen ----')
A('function toggleFullscreen() {')
A('  if (document.fullscreenElement) document.exitFullscreen();')
A('  else document.documentElement.requestFullscreen();')
A('}')
A('')
A('// ---- Message Bookmark integration ----')
A('const origRenderMessages = renderMessages;')
A('renderMessages = function(stb) {')
A('  origRenderMessages(stb);')
A('  updateContextUsage();')
A('}')
A('')
A('// ---- Session stats update ----')
A('const origInit = init;')
A('init = function() {')
A('  origInit();')
A('  buildEmojiPicker();')
A('  setInterval(function() {')
A('    const elapsed = Math.floor((Date.now() - (window.sessionStart || Date.now())) / 1000);')
A('    const h = Math.floor(elapsed / 3600);')
A('    const m = Math.floor((elapsed % 3600) / 60);')
A('    const s = elapsed % 60;')
A('    const dur = h + "h " + m + "m " + s + "s";')
A('    const se = document.querySelector(".session-timer");')
A('    if (se) se.textContent = "Session: " + dur;')
A('  }, 1000);')
A('}')
A('')
A('function buildEmojiPicker() {}')
A('')
A('// ---- Welcome tips rotation ----')
A('const TIPS = ["Try asking about quantum computing", "You can use /commands in the input", "Press Ctrl+P to pull a new model", "Press Ctrl+Shift+P for command palette", "You can attach files by dragging them", "Try comparing two models with the compare view", "Bookmark important messages with the star icon", "Export your conversations as Markdown or JSON", "Voice input works in Chrome-based browsers", "Customize themes in the settings panel"];')
A('')
A('setInterval(function() {')
A('  const tipEl = document.querySelector(".welcome-tip");')
A('  if (tipEl && TIPS.length > 0) {')
A('    const tip = TIPS[Math.floor(Math.random() * TIPS.length)];')
A('    tipEl.textContent = "&#x1F4A1; Tip: " + tip;')
A('  }')
A('}, 15000);')
A('')
A('// ---- Auto-scroll behavior improvements ----')
A('const origSendMessage = sendMessage;')
A('sendMessage = async function() {')
A('  await origSendMessage();')
A('  updateContextUsage();')
A('}')
A('')
A('// ---- Conversation search improvement ----')
A('const origFilterConversations = filterConversations;')
A('filterConversations = function(val) {')
A('  origFilterConversations(val);')
A('}')
A('')
A('// ---- Link detection and auto-linking ----')
A('document.addEventListener("click", function(e) {')
A('  const target = e.target.closest("a");')
A('  if (target && target.href && target.href.startsWith("http")) {')
A('    e.preventDefault();')
A('    window.open(target.href, "_blank", "noopener");')
A('  }')
A('});')
A('')
A('// ---- Model switching from sidebar ----')
A('function quickModelSelect(name) {')
A('  selectModel(name);')
A('  showToast("Switched to " + name, "success");')
A('}')
A('')
A('// ---- Conversation drag reorder (simple) ----')
A('let dragConvId = null;')
A('function startConvDrag(id) { dragConvId = id; }')
A('function endConvDrag() {')
A('  if (dragConvId) {')
A('    const idx = conversations.findIndex(c => c.id === dragConvId);')
A('    if (idx > 0) {')
A('      const item = conversations.splice(idx, 1)[0];')
A('      conversations.splice(idx - 1, 0, item);')
A('      saveConversations();')
A('      renderConversationList();')
A('    }')
A('  }')
A('  dragConvId = null;')
A('}')
A('')
A('// ---- Scroll to top of conversation ----')
A('function scrollToTop() {')
A('  const c = document.getElementById("messagesContainer");')
A('  if (c) c.scrollTop = 0;')
A('}')
A('')
A('// ---- Copy message with formatting ----')
A('function copyMessageRich(idx) {')
A('  const msg = messages[idx];')
A('  if (!msg) return;')
A('  const text = msg.role.toUpperCase() + ":\\n" + msg.content + "\\n\\n-- " + new Date(msg.timestamp).toLocaleString();')
A('  navigator.clipboard.writeText(text);')
A('  showToast("Copied with formatting", "success");')
A('}')
A('')
A('// ---- Handle window focus/blur for connection ----')
A('document.addEventListener("visibilitychange", function() {')
A('  if (!document.hidden) {')
A('    checkServerHealth();')
A('  }')
A('});')
A('')
A('// ---- Persistent notifications for background events ----')
A('if ("Notification" in window) {')
A('  Notification.requestPermission();')
A('}')
A('')
A('function sendBrowserNotification(title, body) {')
A('  if ("Notification" in window && Notification.permission === "granted") {')
A('    new Notification(title, { body: body, icon: "" });')
A('  }')
A('}')
A('')
A('// ---- Message groups (auto-group consecutive messages) ----')
A('function getMessageGroups() {')
A('  const groups = [];')
A('  let current = null;')
A('  messages.forEach((m, i) => {')
A('    if (!current || current.role !== m.role) {')
A('      current = { role: m.role, indices: [i], messages: [m] };')
A('      groups.push(current);')
A('    } else {')
A('      current.indices.push(i);')
A('      current.messages.push(m);')
A('    }')
A('  });')
A('  return groups;')
A('}')
A('')
A('// ---- Code block enhancements ----')
A('document.addEventListener("click", function(e) {')
A('  const btn = e.target.closest(".code-block-header button");')
A('  if (btn) {')
A('    const pre = btn.closest("pre");')
A('    if (pre) {')
A('      const code = pre.querySelector("code");')
A('      if (code) {')
A('        navigator.clipboard.writeText(code.textContent);')
A('        btn.textContent = "Copied!";')
A('        setTimeout(() => { btn.textContent = "Copy"; }, 2000);')
A('      }')
A('    }')
A('  }')
A('});')
A('')
A('// ---- Auto-resize sidebar ----')
A('let sidebarWidth = 280;')
A('function initSidebarResize() {')
A('  const sidebar = document.getElementById("sidebar");')
A('  const handle = document.createElement("div");')
A('  handle.className = "panel-resize-handle";')
A('  handle.style.right = "0";')
A('  sidebar.style.position = "relative";')
A('  sidebar.appendChild(handle);')
A('  let isResizing = false;')
A('  handle.addEventListener("mousedown", function(e) {')
A('    isResizing = true;')
A('    document.body.style.cursor = "col-resize";')
A('    document.body.style.userSelect = "none";')
A('  });')
A('  document.addEventListener("mousemove", function(e) {')
A('    if (!isResizing) return;')
A('    const w = Math.max(200, Math.min(500, e.clientX));')
A('    sidebar.style.width = w + "px";')
A('    sidebarWidth = w;')
A('  });')
A('  document.addEventListener("mouseup", function() {')
A('    isResizing = false;')
A('    document.body.style.cursor = "";')
A('    document.body.style.userSelect = "";')
A('  });')
A('}')
A('')
A('setTimeout(initSidebarResize, 1000);')
A('')
A('// ---- Tab completion for model names ----')
A('const modelNameCache = [];')
A('async function buildModelCache() {')
A('  try {')
A('    const res = await fetch(getServerUrl() + "/api/tags", { signal: AbortSignal.timeout(3000) });')
A('    const data = await res.json();')
A('    (data.models || []).forEach(m => { if (!modelNameCache.includes(m.name)) modelNameCache.push(m.name); });')
A('  } catch(e) {}')
A('}')
A('setTimeout(buildModelCache, 5000);')
A('')
A('// ---- Welcome message stats ----')
A('function updateWelcomeStats() {')
A('  const el = document.getElementById("welcomeStats");')
A('  if (!el) return;')
A('  el.innerHTML = "&#x1F4CA; " + totalMessages + " msgs | &#x1F4E5; " + totalTokens + " tok | &#x1F504; " + modelNameCache.length + " models";')
A('}')
A('')
A('// ---- Close modals with Escape ----')
A('document.addEventListener("keydown", function(e) {')
A('  if (e.key === "Escape") {')
A('    closeCommandPalette();')
A('    closeEmojiPicker();')
A('    closeContextMenu();')
A('    if (document.getElementById("searchOverlay").classList.contains("open")) closeSearchOverlay();')
A('  }')
A('});')
A('')
A('// ---- Auto-save draft ----')
A('let draftTimeout = null;')
A('document.getElementById("messageInput").addEventListener("input", function() {')
A('  clearTimeout(draftTimeout);')
A('  draftTimeout = setTimeout(function() {')
A('    const text = document.getElementById("messageInput").value;')
A('    if (currentConversationId && text) {')
A('      localStorage.setItem("sxigo_draft_" + currentConversationId, text);')
A('    }')
A('  }, 1000);')
A('});')
A('')
A('function loadDraft() {')
A('  if (!currentConversationId) return;')
A('  const draft = localStorage.getItem("sxigo_draft_" + currentConversationId);')
A('  if (draft) {')
A('    document.getElementById("messageInput").value = draft;')
A('    autoResize(document.getElementById("messageInput"));')
A('  }')
A('}')
A('')
A('const origLoadConv = loadConversation;')
A('loadConversation = function(id) {')
A('  origLoadConv(id);')
A('  setTimeout(loadDraft, 100);')
A('}')
A('')
A('// ---- Memory usage (approximate) ----')
A('function estimateMemoryUsage() {')
A('  const size = new Blob([JSON.stringify(conversations)]).size;')
A('  return (size / 1024).toFixed(1) + " KB";')
A('}')
A('')
A('setInterval(function() {')
A('  const el = document.querySelector(".memory-usage");')
A('  if (el) el.textContent = "Mem: " + estimateMemoryUsage();')
A('}, 30000);')
A('')
A('// ---- Export all conversations ----')
A('function exportAllConversations() {')
A('  const data = JSON.stringify(conversations, null, 2);')
A('  const blob = new Blob([data], { type: "application/json" });')
A('  const url = URL.createObjectURL(blob);')
A('  const a = document.createElement("a"); a.href = url; a.download = "sxigo_conversations_backup.json"; a.click();')
A('  URL.revokeObjectURL(url);')
A('  showToast("All conversations exported!", "success");')
A('}')
A('')
A('// ---- Import conversations ----')
A('function importConversations() {')
A('  const input = document.createElement("input");')
A('  input.type = "file"; input.accept = ".json";')
A('  input.onchange = function(e) {')
A('    const file = e.target.files[0];')
A('    if (!file) return;')
A('    const reader = new FileReader();')
A('    reader.onload = function(ev) {')
A('      try {')
A('        const data = JSON.parse(ev.target.result);')
A('        if (Array.isArray(data)) {')
A('          conversations = conversations.concat(data);')
A('          saveConversations();')
A('          renderConversationList();')
A('          showToast("Imported " + data.length + " conversations!", "success");')
A('        }')
A('      } catch(err) { showToast("Invalid file format", "error"); }')
A('    };')
A('    reader.readAsText(file);')
A('  };')
A('  input.click();')
A('}')
A('')
A('// ---- Query parameters support ----')
A('function parseQueryParams() {')
A('  const params = new URLSearchParams(window.location.search);')
A('  const prompt = params.get("prompt");')
A('  const model = params.get("model");')
A('  if (model) { selectModel(model); }')
A('  if (prompt) {')
A('    setTimeout(function() {')
A('      document.getElementById("messageInput").value = prompt;')
A('      sendMessage();')
A('    }, 500);')
A('  }')
A('}')
A('')
A('setTimeout(parseQueryParams, 1000);')
A('')
A('// ---- Dynamic greeting based on time ----')
A('function getTimeGreeting() {')
A('  const h = new Date().getHours();')
A('  if (h < 12) return "Good morning";')
A('  if (h < 18) return "Good afternoon";')
A('  return "Good evening";')
A('}')
A('')
A('// ---- Chat history navigation ----')
A('let messageHistory = [];')
A('let historyIndex = -1;')
A('document.getElementById("messageInput").addEventListener("keydown", function(e) {')
A('  if (e.key === "ArrowUp" && !e.shiftKey && !e.ctrlKey) {')
A('    if (messageHistory.length === 0) {')
A('      messageHistory = messages.filter(m => m.role === "user").map(m => m.content);')
A('    }')
A('    if (messageHistory.length > 0) {')
A('      historyIndex = Math.min(historyIndex + 1, messageHistory.length - 1);')
A('      this.value = messageHistory[messageHistory.length - 1 - historyIndex] || "";')
A('      autoResize(this);')
A('    }')
A('  }')
A('  if (e.key === "ArrowDown") {')
A('    if (historyIndex > 0) {')
A('      historyIndex--;')
A('      this.value = messageHistory[messageHistory.length - 1 - historyIndex] || "";')
A('    } else {')
A('      historyIndex = -1;')
A('      this.value = "";')
A('    }')
A('    autoResize(this);')
A('  }')
A('});')
A('')
A('// ---- Window resize handling ----')
A('let resizeTimeout;')
A('window.addEventListener("resize", function() {')
A('  clearTimeout(resizeTimeout);')
A('  resizeTimeout = setTimeout(function() {')
A('    if (window.innerWidth > 768) {')
A('      document.querySelector(".app-container").classList.remove("sidebar-open");')
A('    }')
A('    if (window.innerWidth > 480) {')
A('      document.querySelector(".status-bar").style.display = "";')
A('    }')
A('  }, 200);')
A('});')
A('')
A('// ---- Network status ----')
A('window.addEventListener("online", function() {')
A('  updateConnectionStatus(true);')
A('  showToast("Back online", "success");')
A('  checkServerHealth();')
A('});')
A('window.addEventListener("offline", function() {')
A('  updateConnectionStatus(false);')
A('  showToast("You are offline", "error");')
A('});')
A('')
A('// ---- Streaming error handling improvement ----')
A('const origFetch = window.fetch;')
A('window.fetch = function(url, options) {')
A('  if (typeof url === "string" && (url.includes("/api/chat") || url.includes("/api/generate"))) {')
A('    const controller = options && options.signal ? options.signal : null;')
A('    const timeout = setTimeout(function() {')
A('      if (controller && !controller.aborted) {')
A('        try { controller.abort(); } catch(e) {}')
A('        showToast("Request timed out after 120 seconds", "error");')
A('      }')
A('    }, 120000);')
A('    return origFetch(url, options).then(function(res) {')
A('      clearTimeout(timeout);')
A('      return res;')
A('    }).catch(function(err) {')
A('      clearTimeout(timeout);')
A('      throw err;')
A('    });')
A('  }')
A('  return origFetch(url, options);')
A('};')
A('')
A('// ---- Custom CSS injection ----')
A('function injectCustomCSS(css) {')
A('  const style = document.createElement("style");')
A('  style.textContent = css;')
A('  document.head.appendChild(style);')
A('}')
A('')
A('// ---- Auto theme based on system preference ----')
A('const darkModeMedia = window.matchMedia("(prefers-color-scheme: dark)");')
A('if (darkModeMedia.matches) {')
A('  document.documentElement.style.setProperty("--bg-primary", "#0a0a1a");')
A('} else {')
A('  document.documentElement.style.setProperty("--bg-primary", "#1a1a2e");')
A('}')
A('')
A('// ---- Session statistics in status bar ----')
A('setInterval(function() {')
A('  const elapsed = Math.floor((Date.now() - sessionStart) / 1000);')
A('  const h = Math.floor(elapsed / 3600);')
A('  const m = Math.floor((elapsed % 3600) / 60);')
A('  const s = elapsed % 60;')
A('  const dot = document.getElementById("statusBarDot");')
A('  if (dot) {')
A('    dot.style.animation = "pulse-dot 2s ease-in-out infinite";')
A('  }')
A('}, 10000);')
A('')
A('// ---- Complete ----')
A('console.log("SXIGOai V2.0 - All features loaded");')
A('console.log("Available commands: Ctrl+Shift+P to open command palette");')
A('</script>')

# Insert before </body>
insertion = '\n'.join(extra)
content = content.replace('</body>', insertion + '\n</body>')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n')
print(f'Total lines after extended features: {line_count}')
