path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

extra = []

def A(s):
    extra.append(s)

# ===== EXTRA CSS =====
A('<style>')
A('/* === V2.0 Advanced Features CSS === */')
A('')
A('.fullscreen-toggle { position: fixed; bottom: 32px; left: 32px; z-index: 50; width: 36px; height: 36px; border-radius: 50%; border: 1px solid var(--glass-border); background: rgba(255,255,255,0.04); backdrop-filter: blur(12px); color: var(--text-muted); cursor: pointer; font-size: 14px; display: flex; align-items: center; justify-content: center; transition: var(--transition); }')
A('.fullscreen-toggle:hover { background: rgba(255,255,255,0.1); color: var(--text-primary); }')
A('')
A('.conv-badge { display: inline-flex; align-items: center; gap: 4px; padding: 1px 8px; border-radius: 8px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; background: rgba(102,126,234,0.12); color: var(--accent-5); }')
A('.conv-badge.code { background: rgba(46,204,113,0.12); color: #2ecc71; }')
A('.conv-badge.work { background: rgba(255,107,107,0.12); color: #ff6b6b; }')
A('.conv-badge.chat { background: rgba(102,126,234,0.12); color: var(--accent-5); }')
A('')
A('.typing-text { display: inline; }')
A('.typing-text::after { content: "|"; animation: cursor-blink 0.8s step-end infinite; }')
A('@keyframes cursor-blink { 50% { opacity: 0; } }')
A('')
A('.msg-search-highlight { background: rgba(255,217,61,0.25); border-radius: 2px; padding: 0 2px; }')
A('.msg-search-highlight.active { background: rgba(255,217,61,0.45); }')
A('')
A('.loading-overlay { position: absolute; inset: 0; background: rgba(0,0,0,0.3); backdrop-filter: blur(2px); display: flex; align-items: center; justify-content: center; z-index: 20; border-radius: var(--radius-lg); }')
A('.loading-overlay .spinner { width: 28px; height: 28px; border-width: 3px; }')
A('')
A('.model-select-modal { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 6px; max-height: 300px; overflow-y: auto; }')
A('.model-select-modal .msm-item { padding: 8px 12px; border-radius: var(--radius-sm); border: 1px solid var(--glass-border); background: rgba(255,255,255,0.03); cursor: pointer; transition: var(--transition); font-size: 12px; }')
A('.model-select-modal .msm-item:hover { background: rgba(255,255,255,0.06); border-color: var(--accent-5); }')
A('.model-select-modal .msm-item .msm-name { font-weight: 600; color: var(--text-primary); }')
A('.model-select-modal .msm-item .msm-detail { font-size: 10px; color: var(--text-muted); }')
A('')
A('.reaction-picker { display: none; position: absolute; bottom: 100%; right: 0; background: rgba(22,22,52,0.95); backdrop-filter: blur(24px); border: 1px solid var(--glass-border); border-radius: var(--radius-sm); padding: 4px; box-shadow: 0 8px 32px rgba(0,0,0,0.3); }')
A('.reaction-picker.open { display: flex; gap: 2px; }')
A('.reaction-picker .rp-btn { width: 30px; height: 30px; border-radius: 6px; border: none; background: transparent; cursor: pointer; font-size: 16px; transition: var(--transition); }')
A('.reaction-picker .rp-btn:hover { background: rgba(255,255,255,0.06); transform: scale(1.2); }')
A('')
A('.context-usage { padding: 4px 12px; font-size: 10px; color: var(--text-muted); display: flex; align-items: center; gap: 6px; }')
A('.context-usage .cu-bar { flex: 1; height: 3px; background: var(--bg-tertiary); border-radius: 2px; overflow: hidden; }')
A('.context-usage .cu-fill { height: 100%; background: linear-gradient(90deg, var(--accent-4), var(--accent-5), var(--accent-6)); border-radius: 2px; transition: width 0.5s ease; }')
A('')
A('.emoji-list { display: grid; grid-template-columns: repeat(8, 1fr); gap: 2px; max-height: 200px; overflow-y: auto; }')
A('.emoji-list .emoji-btn { width: 32px; height: 32px; border-radius: 6px; border: none; background: transparent; cursor: pointer; font-size: 18px; display: flex; align-items: center; justify-content: center; transition: var(--transition); }')
A('.emoji-list .emoji-btn:hover { background: rgba(255,255,255,0.06); transform: scale(1.15); }')
A('')
A('.split-view { display: flex; height: 100%; }')
A('.split-view .sv-pane { flex: 1; overflow-y: auto; padding: 12px; border-right: 1px solid var(--glass-border); }')
A('.split-view .sv-pane:last-child { border-right: none; }')
A('.split-view .sv-pane .sv-header { font-size: 11px; font-weight: 600; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; padding-bottom: 6px; border-bottom: 1px solid var(--glass-border); }')
A('')
A('.notification-item { position: relative; }')
A('.notification-item .notif-dismiss { position: absolute; top: 4px; right: 4px; background: none; border: none; color: var(--text-muted); cursor: pointer; font-size: 12px; padding: 2px; }')
A('.notification-item .notif-dismiss:hover { color: var(--text-primary); }')
A('')
A('.tooltip { position: relative; }')
A('.tooltip::after { content: attr(data-tooltip); position: absolute; bottom: calc(100% + 6px); left: 50%; transform: translateX(-50%); padding: 4px 10px; border-radius: 4px; background: rgba(0,0,0,0.8); color: #fff; font-size: 10px; white-space: nowrap; opacity: 0; pointer-events: none; transition: opacity 0.2s; }')
A('.tooltip:hover::after { opacity: 1; }')
A('')
A('.tab-bar { display: flex; gap: 2px; background: rgba(255,255,255,0.03); border-radius: var(--radius-sm); padding: 3px; margin-bottom: 12px; }')
A('.tab-bar .tab { flex: 1; padding: 6px 12px; text-align: center; border-radius: 6px; cursor: pointer; font-size: 12px; font-weight: 500; color: var(--text-muted); transition: var(--transition); border: none; background: none; }')
A('.tab-bar .tab:hover { color: var(--text-secondary); }')
A('.tab-bar .tab.active { background: var(--bg-tertiary); color: var(--text-primary); }')
A('')
A('.sidebar-section-title { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: var(--text-muted); padding: 8px 16px 4px; font-weight: 600; }')
A('')
A('.panel-header-actions { display: flex; gap: 4px; }')
A('.panel-header-actions button { width: 28px; height: 28px; border: 1px solid var(--glass-border); border-radius: 6px; background: rgba(255,255,255,0.04); color: var(--text-muted); cursor: pointer; transition: var(--transition); font-size: 12px; display: flex; align-items: center; justify-content: center; }')
A('.panel-header-actions button:hover { background: rgba(255,255,255,0.1); color: var(--text-primary); }')
A('')
A('.command-palette { position: fixed; top: 80px; left: 50%; transform: translateX(-50%); width: 560px; max-width: 90vw; z-index: 350; background: rgba(18,18,42,0.95); backdrop-filter: blur(32px) saturate(1.5); border: 1px solid var(--glass-border); border-radius: var(--radius-lg); box-shadow: 0 24px 80px rgba(0,0,0,0.5); display: none; }')
A('.command-palette.open { display: block; }')
A('.command-palette input { width: 100%; padding: 14px 18px; border: none; background: transparent; color: var(--text-primary); font-size: 16px; outline: none; border-bottom: 1px solid var(--glass-border); }')
A('.command-palette input::placeholder { color: var(--text-muted); }')
A('.command-palette .cp-results { max-height: 320px; overflow-y: auto; padding: 4px; }')
A('.command-palette .cp-item { padding: 8px 14px; border-radius: 6px; cursor: pointer; display: flex; align-items: center; gap: 10px; transition: var(--transition); }')
A('.command-palette .cp-item:hover, .command-palette .cp-item.selected { background: rgba(255,255,255,0.06); }')
A('.command-palette .cp-item .cp-icon { font-size: 18px; width: 24px; text-align: center; }')
A('.command-palette .cp-item .cp-title { font-size: 13px; font-weight: 600; color: var(--text-primary); }')
A('.command-palette .cp-item .cp-desc { font-size: 11px; color: var(--text-muted); }')
A('.command-palette .cp-item .cp-shortcut { margin-left: auto; font-size: 10px; padding: 2px 6px; background: rgba(255,255,255,0.08); border-radius: 4px; color: var(--text-muted); font-family: var(--font-mono); }')
A('')
A('.conv-group-header { font-size: 11px; font-weight: 700; color: var(--text-muted); text-transform: uppercase; letter-spacing: 1px; padding: 8px 16px 4px; }')
A('')
A('.conv-item-details { font-size: 10px; color: var(--text-muted); margin-top: 1px; display: flex; gap: 6px; }')
A('')
A('.typing-status { position: fixed; bottom: 80px; left: 50%; transform: translateX(-50%); font-size: 11px; color: var(--text-muted); padding: 4px 14px; border-radius: 12px; background: rgba(18,18,42,0.8); backdrop-filter: blur(12px); border: 1px solid var(--glass-border); z-index: 30; display: none; }')
A('.typing-status.visible { display: block; }')
A('')
A('.search-badge { display: inline-flex; align-items: center; gap: 2px; padding: 1px 8px; border-radius: 8px; background: rgba(102,126,234,0.12); color: var(--accent-5); font-size: 10px; }')
A('')
A('.scroll-to-bottom-btn { position: absolute; bottom: 16px; left: 50%; transform: translateX(-50%); z-index: 5; width: 36px; height: 36px; border-radius: 50%; border: 1px solid var(--glass-border); background: rgba(18,18,42,0.8); backdrop-filter: blur(12px); color: var(--text-muted); cursor: pointer; font-size: 16px; display: none; align-items: center; justify-content: center; transition: var(--transition); box-shadow: 0 4px 16px rgba(0,0,0,0.2); }')
A('.scroll-to-bottom-btn.visible { display: flex; }')
A('.scroll-to-bottom-btn:hover { background: rgba(255,255,255,0.1); color: var(--text-primary); }')
A('')
A('.dark-room-overlay { position: fixed; inset: 0; background: #000; z-index: 9999; display: none; }')
A('.dark-room-overlay.open { display: block; }')
A('')
A('.chat-background-image { position: fixed; inset: 0; z-index: -1; opacity: 0.03; background-size: cover; background-position: center; pointer-events: none; }')
A('')
A('.divider-text { display: flex; align-items: center; gap: 12px; font-size: 11px; color: var(--text-muted); padding: 8px 0; }')
A('.divider-text::before, .divider-text::after { content: ""; flex: 1; height: 1px; background: var(--glass-border); }')
A('')
A('.message-selectable { user-select: text; cursor: text; }')
A('.msg-fade-in { animation: msg-fade-in 0.3s ease-out; }')
A('@keyframes msg-fade-in { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }')
A('')
A('.glass-progress { width: 100%; height: 4px; background: var(--bg-tertiary); border-radius: 2px; overflow: hidden; }')
A('.glass-progress .gp-fill { height: 100%; border-radius: 2px; background: linear-gradient(90deg, var(--accent-5), var(--accent-6)); transition: width 0.3s; }')
A('')
A('.badge-dot { width: 8px; height: 8px; border-radius: 50%; display: inline-block; }')
A('.badge-dot.online { background: var(--accent-4); box-shadow: 0 0 6px var(--accent-4); }')
A('.badge-dot.offline { background: var(--accent-1); box-shadow: 0 0 6px var(--accent-1); }')
A('.badge-dot.away { background: #ffd93d; box-shadow: 0 0 6px #ffd93d; }')
A('')
A('.model-select-badge-small { display: inline-flex; align-items: center; gap: 3px; padding: 1px 6px; border-radius: 6px; background: rgba(102,126,234,0.1); font-size: 9px; color: var(--accent-5); }')
A('')
A('.code-block-header { display: flex; align-items: center; justify-content: space-between; padding: 6px 12px; background: rgba(0,0,0,0.3); border-bottom: 1px solid var(--glass-border); font-size: 11px; color: var(--text-muted); }')
A('.code-block-header .cbh-lang { font-weight: 600; color: var(--accent-5); }')
A('.code-block-header .cbh-actions { display: flex; gap: 4px; }')
A('.code-block-header .cbh-actions button { font-size: 10px; padding: 2px 8px; background: rgba(255,255,255,0.06); border: 1px solid var(--glass-border); border-radius: 4px; color: var(--text-muted); cursor: pointer; transition: var(--transition); }')
A('.code-block-header .cbh-actions button:hover { color: var(--text-primary); background: rgba(255,255,255,0.1); }')
A('')
A('.quick-input-bar { display: flex; gap: 4px; align-items: center; padding: 4px 0; }')
A('.quick-input-bar .qib-btn { width: 26px; height: 26px; border-radius: 4px; border: none; background: transparent; color: var(--text-muted); cursor: pointer; transition: var(--transition); font-size: 13px; display: flex; align-items: center; justify-content: center; }')
A('.quick-input-bar .qib-btn:hover { background: rgba(255,255,255,0.06); color: var(--text-primary); }')
A('')
A('.settings-row { display: flex; align-items: center; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid var(--glass-border); }')
A('.settings-row:last-child { border-bottom: none; }')
A('.settings-row .sr-label { font-size: 12px; color: var(--text-secondary); }')
A('.settings-row .sr-value { font-size: 12px; color: var(--text-primary); font-weight: 500; }')
A('')
A('.toggle-switch { position: relative; width: 36px; height: 20px; border-radius: 10px; background: var(--bg-tertiary); cursor: pointer; transition: var(--transition); }')
A('.toggle-switch.active { background: var(--accent-5); }')
A('.toggle-switch::after { content: ""; position: absolute; top: 2px; left: 2px; width: 16px; height: 16px; border-radius: 50%; background: #fff; transition: var(--transition); }')
A('.toggle-switch.active::after { left: 18px; }')
A('')
A('.conv-drag-handle { cursor: grab; color: var(--text-muted); font-size: 12px; padding: 0 4px; }')
A('.conv-drag-handle:active { cursor: grabbing; }')
A('')
A('.code-block-wrapper { position: relative; }')
A('.code-block-wrapper .code-lines { position: absolute; top: 0; left: 0; bottom: 0; width: 32px; background: rgba(0,0,0,0.2); border-right: 1px solid var(--glass-border); padding: 4px 0; text-align: right; font-family: var(--font-mono); font-size: 11px; color: var(--text-muted); pointer-events: none; overflow: hidden; }')
A('')
A('.model-status-indicator { display: flex; align-items: center; gap: 5px; font-size: 11px; }')
A('.model-status-indicator .msi-dot { width: 8px; height: 8px; border-radius: 50%; }')
A('.model-status-indicator .msi-dot.loaded { background: var(--accent-4); }')
A('.model-status-indicator .msi-dot.loading { background: #ffd93d; animation: pulse-dot 1.5s infinite; }')
A('.model-status-indicator .msi-dot.error { background: var(--accent-1); }')
A('')
A('.message-body p:first-child { margin-top: 0; }')
A('.message-body p:last-child { margin-bottom: 0; }')
A('')
A('.animation-delay-100 { animation-delay: 0.1s; }')
A('.animation-delay-200 { animation-delay: 0.2s; }')
A('.animation-delay-300 { animation-delay: 0.3s; }')
A('.animation-delay-400 { animation-delay: 0.4s; }')
A('.animation-delay-500 { animation-delay: 0.5s; }')
A('')
A('.conv-item-highlight { animation: conv-highlight 0.5s ease-out; }')
A('@keyframes conv-highlight { 0% { background: rgba(102,126,234,0.2); } 100% { background: transparent; } }')
A('')
A('.model-select-active { background: rgba(102,126,234,0.12) !important; border-color: var(--accent-5) !important; }')
A('')
A('.token-usage { font-size: 10px; color: var(--text-muted); display: flex; gap: 8px; padding: 2px 8px; }')
A('.token-usage .tu-label { color: var(--text-muted); }')
A('.token-usage .tu-value { font-weight: 600; color: var(--accent-5); }')
A('')
A('.model-name-badge { display: inline-flex; align-items: center; gap: 4px; padding: 2px 10px; border-radius: 10px; background: linear-gradient(135deg, rgba(102,126,234,0.15), rgba(151,117,250,0.1)); border: 1px solid rgba(102,126,234,0.2); font-size: 11px; color: var(--accent-5); }')
A('')
A('.typing-animation { overflow: hidden; white-space: nowrap; animation: typing 2s steps(30); }')
A('@keyframes typing { from { width: 0; } to { width: 100%; } }')
A('')
A('.sidebar-footer-extras { display: flex; gap: 4px; padding: 4px 12px 8px; flex-wrap: wrap; }')
A('.sidebar-footer-extras .sfe-btn { padding: 3px 8px; border-radius: 6px; border: 1px solid var(--glass-border); background: rgba(255,255,255,0.03); color: var(--text-muted); font-size: 10px; cursor: pointer; transition: var(--transition); }')
A('.sidebar-footer-extras .sfe-btn:hover { background: rgba(255,255,255,0.08); color: var(--text-primary); }')
A('')
A('.conversation-import-area { border: 2px dashed var(--glass-border); border-radius: var(--radius-md); padding: 20px; text-align: center; margin: 8px 0; color: var(--text-muted); font-size: 12px; cursor: pointer; transition: var(--transition); }')
A('.conversation-import-area:hover { border-color: var(--accent-5); color: var(--text-primary); }')
A('')
A('.sidebar-model-select { padding: 6px 12px; }')
A('.sidebar-model-select select { width: 100%; padding: 4px 8px; border: 1px solid var(--glass-border); border-radius: 6px; background: rgba(26,26,62,0.8); color: var(--text-primary); font-size: 11px; outline: none; }')
A('')
A('.welcome-tip { font-size: 11px; color: var(--text-muted); text-align: center; padding: 8px; font-style: italic; }')
A('')
A('.message-fade-out { animation: msg-fade-out 0.3s ease-in forwards; }')
A('@keyframes msg-fade-out { to { opacity: 0; transform: translateY(-8px); } }')
A('')
A('.emoji-picker-grid { display: grid; grid-template-columns: repeat(6, 1fr); gap: 4px; padding: 8px; }')
A('.emoji-picker-grid .ep-emoji { width: 36px; height: 36px; display: flex; align-items: center; justify-content: center; border-radius: 6px; cursor: pointer; font-size: 20px; transition: var(--transition); }')
A('.emoji-picker-grid .ep-emoji:hover { background: rgba(255,255,255,0.06); transform: scale(1.1); }')
A('')
A('.conversation-info { padding: 8px 16px; font-size: 10px; color: var(--text-muted); border-top: 1px solid var(--glass-border); }')
A('.conversation-info .ci-row { display: flex; justify-content: space-between; padding: 2px 0; }')
A('')
A('.slider-with-label { display: flex; align-items: center; gap: 8px; }')
A('.slider-with-label input[type=range] { flex: 1; }')
A('.slider-with-label .slider-val { min-width: 36px; text-align: right; font-weight: 600; color: var(--accent-5); font-size: 13px; }')
A('')
A('.model-card { display: flex; padding: 10px 14px; border-radius: var(--radius-md); background: rgba(255,255,255,0.03); border: 1px solid var(--glass-border); margin: 4px 0; cursor: pointer; transition: var(--transition); }')
A('.model-card:hover { background: rgba(255,255,255,0.06); border-color: var(--accent-5); }')
A('.model-card .mc-icon { font-size: 24px; margin-right: 10px; }')
A('.model-card .mc-info { flex: 1; }')
A('.model-card .mc-name { font-weight: 600; font-size: 13px; }')
A('.model-card .mc-detail { font-size: 11px; color: var(--text-muted); }')
A('.model-card .mc-size { font-size: 11px; color: var(--text-muted); }')
A('.model-card .mc-actions { display: flex; gap: 4px; align-items: center; }')
A('.model-card .mc-actions button { padding: 3px 8px; border-radius: 4px; border: 1px solid var(--glass-border); background: rgba(255,255,255,0.04); color: var(--text-muted); cursor: pointer; font-size: 10px; transition: var(--transition); }')
A('.model-card .mc-actions button:hover { background: rgba(255,255,255,0.1); color: var(--text-primary); }')
A('')
A('.print-header, .print-footer { display: none; }')
A('@media print {')
A('  body { background: #fff !important; color: #000 !important; }')
A('  .sidebar, .input-area, .model-info-bar, .status-bar, .header-btn, .watermark, .bg-particles, .settings-panel, .notification-panel, .compare-view, .modal-overlay { display: none !important; }')
A('  .main-content { width: 100% !important; }')
A('  .message-content { background: #f5f5f5 !important; border: 1px solid #ddd !important; color: #000 !important; }')
A('  .print-header { display: block; text-align: center; font-size: 18px; font-weight: bold; margin-bottom: 20px; }')
A('  .print-footer { display: block; text-align: center; font-size: 10px; color: #999; margin-top: 20px; }')
A('  .avatar { background: #eee !important; color: #333 !important; }')
A('  * { animation: none !important; transition: none !important; }')
A('}')
A('')
A('.popup-notice { position: fixed; bottom: 60px; left: 50%; transform: translateX(-50%); background: rgba(18,18,42,0.9); backdrop-filter: blur(16px); border: 1px solid var(--glass-border); border-radius: var(--radius-sm); padding: 12px 20px; max-width: 400px; z-index: 100; font-size: 12px; color: var(--text-secondary); box-shadow: 0 8px 32px rgba(0,0,0,0.3); display: none; }')
A('.popup-notice.open { display: block; animation: toast-in 0.3s ease-out; }')
A('.popup-notice .pn-title { font-weight: 600; color: var(--text-primary); margin-bottom: 4px; }')
A('.popup-notice .pn-actions { display: flex; gap: 8px; margin-top: 8px; }')
A('.popup-notice .pn-actions button { padding: 4px 12px; border-radius: 6px; border: 1px solid var(--glass-border); background: rgba(255,255,255,0.04); color: var(--text-muted); cursor: pointer; font-size: 11px; transition: var(--transition); }')
A('.popup-notice .pn-actions button:hover { background: rgba(255,255,255,0.1); color: var(--text-primary); }')
A('.popup-notice .pn-actions button.primary { background: linear-gradient(135deg, #667eea, #764ba2); border: none; color: #fff; }')
A('')
A('.code-diff-added { background: rgba(46,204,113,0.15); }')
A('.code-diff-removed { background: rgba(255,107,107,0.15); }')
A('')
A('.model-context-bar { width: 100%; height: 2px; border-radius: 1px; background: var(--bg-tertiary); margin: 2px 0; overflow: hidden; }')
A('.model-context-bar .mcb-fill { height: 100%; transition: width 0.5s; }')
A('</style>')

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

insertion = '\n'.join(extra)
content = content.replace('</body>', insertion + '\n</body>')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n')
print(f'Total lines after extra CSS: {line_count}')
