path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

lines = []
def L(s):
    lines.append(s)

# Generate ~700 more lines
L('<style>')
L('/* === V2.0 Extended Theming === */')

# Each theme with complete variable set
themes_data = {
    'ocean': {'p1': '#667eea', 'p2': '#5a6fd6', 'p3': '#4facfe', 'p4': '#764ba2', 'p5': '#9b72cf', 'p6': '#b8a0e0', 'p7': '#d4c0f0', 'bg': '#0a0a1a', 'bg2': '#12122a'},
    'sunset': {'p1': '#f093fb', 'p2': '#e882e6', 'p3': '#fca311', 'p4': '#f5576c', 'p5': '#f77f8f', 'p6': '#f9a0ab', 'p7': '#fbc0c7', 'bg': '#0d0d1a', 'bg2': '#1a0e0a'},
    'forest': {'p1': '#2ecc71', 'p2': '#27ae60', 'p3': '#1abc9c', 'p4': '#239954', 'p5': '#3ddc84', 'p6': '#5ee8a0', 'p7': '#80f0b8', 'bg': '#050d0a', 'bg2': '#0a1a12'},
    'neon': {'p1': '#00ff87', 'p2': '#00e67a', 'p3': '#ff00ff', 'p4': '#60efff', 'p5': '#80f5ff', 'p6': '#a0faff', 'p7': '#c0ffff', 'bg': '#050510', 'bg2': '#0a0a20'},
    'midnight': {'p1': '#7c3aed', 'p2': '#6d28d9', 'p3': '#6366f1', 'p4': '#a78bfa', 'p5': '#b8a0fb', 'p6': '#c9b5fc', 'p7': '#dacafd', 'bg': '#03030f', 'bg2': '#080818'},
    'aurora': {'p1': '#00b4d8', 'p2': '#0096c7', 'p3': '#90e0ef', 'p4': '#0077b6', 'p5': '#2395c8', 'p6': '#4db3da', 'p7': '#80cce8', 'bg': '#000814', 'bg2': '#001024'},
    'candy': {'p1': '#ff6b6b', 'p2': '#ee5a24', 'p3': '#ffd93d', 'p4': '#ffa07a', 'p5': '#ffb896', 'p6': '#ffcdaf', 'p7': '#ffe0d0', 'bg': '#0f0a14', 'bg2': '#1a0f1e'},
    'mono': {'p1': '#888', 'p2': '#777', 'p3': '#ccc', 'p4': '#aaa', 'p5': '#bbb', 'p6': '#ccc', 'p7': '#ddd', 'bg': '#050505', 'bg2': '#0f0f0f'}
}

for theme, colors in themes_data.items():
    L(f'.theme-{theme} {{')
    L(f'  --accent-1: {colors["p1"]};')
    L(f'  --accent-2: {colors["p2"]};')
    L(f'  --accent-3: {colors["p3"]};')
    L(f'  --accent-4: {colors["p4"]};')
    L(f'  --accent-5: {colors["p5"]};')
    L(f'  --accent-6: {colors["p6"]};')
    L(f'  --accent-7: {colors["p7"]};')
    L(f'  --bg-primary: {colors["bg"]};')
    L(f'  --bg-secondary: {colors["bg2"]};')
    L(f'  --gradient-main: linear-gradient(135deg, {colors["p1"]}, {colors["p4"]});')
    L(f'  --gradient-chat: linear-gradient(135deg, {colors["p1"]}, {colors["p3"]}, {colors["p4"]});')
    L(f'  --gradient-glass: linear-gradient(135deg, {colors["p1"]}22, {colors["p4"]}11);')
    L('}')
    L(f'.theme-{theme} .new-chat-btn {{ background: linear-gradient(135deg, {colors["p1"]}, {colors["p4"]}); }}')
    L(f'.theme-{theme} .send-btn {{ background: linear-gradient(135deg, {colors["p1"]}, {colors["p4"]}); }}')
    L(f'.theme-{theme} .model-badge {{ background: linear-gradient(135deg, {colors["p1"]}, {colors["p3"]}); }}')
    L(f'.theme-{theme} .sidebar-icon-btn:hover {{ color: {colors["p1"]}; }}')
    L(f'.theme-{theme} ::-webkit-scrollbar-thumb {{ background: {colors["p1"]}44; }}')
    L(f'.theme-{theme} ::selection {{ background: {colors["p1"]}33; }}')

L('')
L('/* Focus visible enhancement */')
L(':focus-visible { outline: 2px solid var(--accent-5); outline-offset: 2px; }')
L('')
L('/* Scrollbar width */')
L('::-webkit-scrollbar { width: 6px; height: 6px; }')
L('::-webkit-scrollbar-track { background: transparent; }')
L('::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.1); border-radius: 3px; }')
L('::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.2); }')
L('* { scrollbar-width: thin; scrollbar-color: rgba(255,255,255,0.1) transparent; }')
L('')
L('/* Print styles */')
L('@media print {')
L('  body { background: #fff; color: #000; }')
L('  .glass-card, .message-content { background: #f5f5f5 !important; backdrop-filter: none !important; }')
L('  .sidebar, .input-area, .status-bar, .settings-panel { display: none !important; }')
L('  .main-content { width: 100% !important; }')
L('}')

L('</style>')

# More JS
L('<script>')
L('// ===== V2.0 Accessibility & UX Enhancements =====')
L('// ---- Skip to content link ----')
L('const skipLink = document.createElement("a");')
L('skipLink.href = "#messagesContainer";')
L('skipLink.textContent = "Skip to content";')
L('skipLink.style.cssText = "position:absolute;top:-40px;left:0;background:var(--accent-5);color:#fff;padding:8px 16px;z-index:9999;transition:top 0.2s;";')
L('skipLink.onfocus = function() { this.style.top = "0"; };')
L('skipLink.onblur = function() { this.style.top = "-40px"; };')
L('document.body.insertBefore(skipLink, document.body.firstChild);')
L('')
L('// ---- ARIA labels ----')
L('document.querySelectorAll(".conv-item").forEach(function(el) {')
L('  el.setAttribute("role", "button");')
L('  el.setAttribute("tabindex", "0");')
L('});')
L('')
L('// ---- Focus trap in modals ----')
L('function focusTrap(modal) {')
L('  const focusable = modal.querySelectorAll("button, input, select, textarea, [tabindex]:not([tabindex=\\"-1\\"])");')
L('  if (focusable.length === 0) return;')
L('  const first = focusable[0];')
L('  const last = focusable[focusable.length - 1];')
L('  modal.addEventListener("keydown", function(e) {')
L('    if (e.key === "Tab") {')
L('      if (e.shiftKey && document.activeElement === first) {')
L('        e.preventDefault(); last.focus();')
L('      } else if (!e.shiftKey && document.activeElement === last) {')
L('        e.preventDefault(); first.focus();')
L('      }')
L('    }')
L('  });')
L('  first.focus();')
L('}')
L('')
L('// ---- Mobile keyboard handling ----')
L('document.getElementById("messageInput").addEventListener("focus", function() {')
L('  if (window.innerWidth <= 768) {')
L('    setTimeout(function() {')
L('      document.getElementById("messagesContainer").scrollTop = document.getElementById("messagesContainer").scrollHeight;')
L('    }, 300);')
L('  }')
L('});')
L('')
L('// ---- Touch event improvements ----')
L('let touchStartX = 0;')
L('document.addEventListener("touchstart", function(e) {')
L('  touchStartX = e.changedTouches[0].screenX;')
L('});')
L('document.addEventListener("touchend", function(e) {')
L('  const diff = touchStartX - e.changedTouches[0].screenX;')
L('  if (Math.abs(diff) > 100 && window.innerWidth <= 768) {')
L('    if (diff > 0) {')
L('      document.querySelector(".app-container").classList.remove("sidebar-open");')
L('    } else {')
L('      document.querySelector(".app-container").classList.add("sidebar-open");')
L('    }')
L('  }')
L('});')
L('')
L('// ---- Analytics (local) ----')
L('let analytics = {')
L('  sessions: 0,')
L('  messagesTotal: 0,')
L('  tokensTotal: 0,')
L('  commandsExecuted: 0,')
L('  themesChanged: 0')
L('};')
L('')
L('function trackEvent(category, action) {')
L('  analytics.sessions++;')
L('  try {')
L('    const stored = JSON.parse(localStorage.getItem("sxigo_analytics") || "{}");')
L('    stored[category] = (stored[category] || 0) + 1;')
L('    localStorage.setItem("sxigo_analytics", JSON.stringify(stored));')
L('  } catch(e) {}')
L('}')
L('')
L('// ---- Quick tip of the day ----')
L('const QUICK_TIPS = [')
L('  "Use Ctrl+Shift+P to open the command palette",')
L('  "You can drag and drop files to attach them",')
L('  "Double-click a conversation to rename it",')
L('  "Right-click messages for more options",')
L('  "Try the compare view to test different models",')
L('  "Bookmark important messages with the star icon",')
L('  "Export your chat as Markdown or JSON",')
L('  "Custom themes can be saved and exported",')
L('  "Voice input works best in Chrome",')
L('  "Use /commands in the input for quick actions"')
L('];')
L('')
L('function showRandomTip() {')
L('  const tip = QUICK_TIPS[Math.floor(Math.random() * QUICK_TIPS.length)];')
L('  showToast("&#x1F4A1; " + tip, "info");')
L('}')
L('')
L('// ---- Lazy load models on dashboard open ----')
L('const origOpenDash = openDashboard;')
L('openDashboard = function() {')
L('  origOpenDash();')
L('  trackEvent("ui", "dashboard_open");')
L('}')
L('')
L('// ---- WebSocket support (future) ----')
L('let ws = null;')
L('function connectWebSocket() {')
L('  try {')
L('    const url = getServerUrl().replace("http", "ws") + "/ws";')
L('    ws = new WebSocket(url);')
L('    ws.onopen = function() { console.log("WebSocket connected"); };')
L('    ws.onmessage = function(e) { console.log("WS message:", e.data); };')
L('    ws.onerror = function() { console.log("WebSocket error (expected if not supported)"); };')
L('  } catch(e) {}')
L('}')
L('// connectWebSocket(); // Disabled by default')
L('')
L('// ---- Export complete app state ----')
L('function exportFullState() {')
L('  const state = {')
L('    version: "2.0",')
L('    timestamp: Date.now(),')
L('    settings: settings,')
L('    conversations: conversations,')
L('    analytics: analytics,')
L('    sessionStats: sessionStats')
L('  };')
L('  const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" });')
L('  const url = URL.createObjectURL(blob);')
L('  const a = document.createElement("a"); a.href = url; a.download = "sxigo_full_state_backup.json"; a.click();')
L('  URL.revokeObjectURL(url);')
L('  showToast("Full state exported!", "success");')
L('}')
L('')
L('// ---- Import full state ----')
L('function importFullState() {')
L('  const input = document.createElement("input");')
L('  input.type = "file"; input.accept = ".json";')
L('  input.onchange = function(e) {')
L('    const reader = new FileReader();')
L('    reader.onload = function(ev) {')
L('      try {')
L('        const state = JSON.parse(ev.target.result);')
L('        if (state.settings) { settings = state.settings; saveSettings(); }')
L('        if (state.conversations) { conversations = state.conversations; saveConversations(); renderConversationList(); }')
L('        showToast("State imported! Reloading...", "success");')
L('        setTimeout(function() { location.reload(); }, 1000);')
L('      } catch(err) { showToast("Invalid state file", "error"); }')
L('    };')
L('    reader.readAsText(file);')
L('  };')
L('  input.click();')
L('}')
L('')
L('// ---- Final note ----')
L('console.log("%cSXIGOai V2.0", "font-size:24px;font-weight:bold;color:#667eea;");')
L('console.log("%cThank you for using SXIGOai V2.0!", "font-size:14px;color:#888;");')
L('console.log("Report issues: https://github.com/anomalyco/opencode/issues");')
L('</script>')

# Add a meta tag for completeness
L('<meta name="generator" content="SXIGOai V2.0">')
L('<meta name="description" content="SXIGOai V2.0 - Next-generation AI chat with glassmorphism and RGB effects">')
L('<meta name="theme-color" content="#0a0a1a">')

insertion = '\n'.join(lines)
content = content.replace('</body>', insertion + '\n</body>')

last_body = content.rfind('</body>')
last_html = content.rfind('</html>')
if last_body > last_html:
    content = content[:last_body + 7] + '\n</html>\n'

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n')
print(f'Total lines: {line_count}')
print(f'Target: 6200')
print(f'Remaining: {6200 - line_count}')
