path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

extra = []
def A(s):
    extra.append(s)

# ===== ADDITIONAL CSS ANIMATIONS =====
A('<style>')
A('/* === V2.0 Animation Library === */')
A('')
A('@keyframes float-up { 0% { transform: translateY(20px); opacity: 0; } 100% { transform: translateY(0); opacity: 1; } }')
A('@keyframes float-down { 0% { transform: translateY(-20px); opacity: 0; } 100% { transform: translateY(0); opacity: 1; } }')
A('@keyframes float-left { 0% { transform: translateX(20px); opacity: 0; } 100% { transform: translateX(0); opacity: 1; } }')
A('@keyframes float-right { 0% { transform: translateX(-20px); opacity: 0; } 100% { transform: translateX(0); opacity: 1; } }')
A('@keyframes scale-in { 0% { transform: scale(0.8); opacity: 0; } 100% { transform: scale(1); opacity: 1; } }')
A('@keyframes scale-out { 0% { transform: scale(1); opacity: 1; } 100% { transform: scale(0.8); opacity: 0; } }')
A('@keyframes rotate-in { 0% { transform: rotate(-90deg) scale(0.5); opacity: 0; } 100% { transform: rotate(0) scale(1); opacity: 1; } }')
A('@keyframes slide-up { 0% { transform: translateY(100%); opacity: 0; } 100% { transform: translateY(0); opacity: 1; } }')
A('@keyframes slide-down { 0% { transform: translateY(-100%); opacity: 0; } 100% { transform: translateY(0); opacity: 1; } }')
A('@keyframes slide-left { 0% { transform: translateX(100%); opacity: 0; } 100% { transform: translateX(0); opacity: 1; } }')
A('@keyframes slide-right { 0% { transform: translateX(-100%); opacity: 0; } 100% { transform: translateX(0); opacity: 1; } }')
A('@keyframes bounce-in { 0% { transform: scale(0.3); opacity: 0; } 50% { transform: scale(1.05); } 70% { transform: scale(0.9); } 100% { transform: scale(1); opacity: 1; } }')
A('@keyframes glow-pulse { 0%,100% { box-shadow: 0 0 5px rgba(102,126,234,0.3); } 50% { box-shadow: 0 0 20px rgba(102,126,234,0.6); } }')
A('@keyframes glow-spread { 0% { box-shadow: 0 0 0 0 rgba(102,126,234,0.4); } 100% { box-shadow: 0 0 0 20px rgba(102,126,234,0); } }')
A('@keyframes shimmer { 0% { background-position: -200% 0; } 100% { background-position: 200% 0; } }')
A('@keyframes breathe { 0%,100% { transform: scale(1); } 50% { transform: scale(1.05); } }')
A('@keyframes heartbeat { 0%,100% { transform: scale(1); } 14% { transform: scale(1.1); } 28% { transform: scale(1); } 42% { transform: scale(1.1); } 70% { transform: scale(1); } }')
A('@keyframes jello { 0%,100% { transform: scale(1,1); } 25% { transform: scale(0.9,1.1); } 50% { transform: scale(1.1,0.9); } 75% { transform: scale(0.95,1.05); } }')
A('@keyframes shake { 0%,100% { transform: translateX(0); } 10%,30%,50%,70%,90% { transform: translateX(-4px); } 20%,40%,60%,80% { transform: translateX(4px); } }')
A('@keyframes tada { 0% { transform: scale(1) rotate(0); } 10%,20% { transform: scale(0.9) rotate(-3deg); } 30%,50%,70%,90% { transform: scale(1.1) rotate(3deg); } 40%,60%,80% { transform: scale(1.1) rotate(-3deg); } 100% { transform: scale(1) rotate(0); } }')
A('@keyframes flip-in { 0% { transform: perspective(400px) rotateX(90deg); opacity: 0; } 40% { transform: perspective(400px) rotateX(-20deg); } 60% { transform: perspective(400px) rotateX(10deg); } 80% { transform: perspective(400px) rotateX(-5deg); } 100% { transform: perspective(400px) rotateX(0); opacity: 1; } }')
A('@keyframes flip-out { 0% { transform: perspective(400px) rotateX(0); opacity: 1; } 100% { transform: perspective(400px) rotateX(90deg); opacity: 0; } }')
A('@keyframes zoom-in { 0% { transform: scale(0); opacity: 0; } 100% { transform: scale(1); opacity: 1; } }')
A('@keyframes zoom-out { 0% { transform: scale(1); opacity: 1; } 100% { transform: scale(0); opacity: 0; } }')
A('@keyframes border-trail { 0% { border-color: var(--accent-5); } 25% { border-color: var(--accent-6); } 50% { border-color: var(--accent-4); } 75% { border-color: var(--accent-1); } 100% { border-color: var(--accent-5); } }')
A('@keyframes gradient-shift { 0% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } 100% { background-position: 0% 50%; } }')
A('@keyframes morph { 0% { border-radius: 60% 40% 30% 70%/60% 30% 70% 40%; } 50% { border-radius: 30% 60% 70% 40%/50% 60% 30% 60%; } 100% { border-radius: 60% 40% 30% 70%/60% 30% 70% 40%; } }')
A('@keyframes spinner-alt { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }')
A('@keyframes dots { 0%,20% { opacity: 0; } 50% { opacity: 1; } 80%,100% { opacity: 0; } }')
A('@keyframes ripple { 0% { box-shadow: 0 0 0 0 rgba(102,126,234,0.3); } 100% { box-shadow: 0 0 0 20px rgba(102,126,234,0); } }')
A('@keyframes confetti-fall { 0% { transform: translateY(-100vh) rotate(0deg); opacity: 1; } 100% { transform: translateY(100vh) rotate(720deg); opacity: 0; } }')
A('@keyframes pulse-ring { 0% { transform: scale(0.5); opacity: 0; } 50% { opacity: 1; } 100% { transform: scale(1.5); opacity: 0; } }')
A('@keyframes float-around { 0% { transform: translate(0,0) rotate(0deg); } 25% { transform: translate(10px,-10px) rotate(5deg); } 50% { transform: translate(0,-20px) rotate(-5deg); } 75% { transform: translate(-10px,-10px) rotate(5deg); } 100% { transform: translate(0,0) rotate(0deg); } }')
A('@keyframes slide-bg { 0% { background-position: 0% 50%; } 100% { background-position: 100% 50%; } }')
A('@keyframes marquee { 0% { transform: translateX(100%); } 100% { transform: translateX(-100%); } }')
A('')
A('/* Utility classes */')
A('.animate-float-up { animation: float-up 0.4s ease-out; }')
A('.animate-float-down { animation: float-down 0.4s ease-out; }')
A('.animate-scale-in { animation: scale-in 0.3s ease-out; }')
A('.animate-bounce-in { animation: bounce-in 0.5s ease-out; }')
A('.animate-slide-up { animation: slide-up 0.4s ease-out; }')
A('.animate-fade-in { animation: fade-in 0.3s ease-out; }')
A('.animate-glow-pulse { animation: glow-pulse 2s ease-in-out infinite; }')
A('.animate-shimmer { animation: shimmer 2s linear infinite; background: linear-gradient(90deg, transparent, rgba(255,255,255,0.05), transparent); background-size: 200% 100%; }')
A('.animate-breathe { animation: breathe 3s ease-in-out infinite; }')
A('.animate-shake { animation: shake 0.5s ease-out; }')
A('.animate-heartbeat { animation: heartbeat 1s ease-in-out; }')
A('.animate-jello { animation: jello 0.8s ease-out; }')
A('.animate-tada { animation: tada 0.8s ease-out; }')
A('.animate-flip-in { animation: flip-in 0.5s ease-out; }')
A('.animate-zoom-in { animation: zoom-in 0.3s ease-out; }')
A('.animate-morph { animation: morph 8s ease-in-out infinite; }')
A('.animate-ripple { animation: ripple 0.6s ease-out; }')
A('.animate-pulse-ring { animation: pulse-ring 1.5s ease-out infinite; }')
A('.animate-float-around { animation: float-around 6s ease-in-out infinite; }')
A('.animate-gradient-shift { animation: gradient-shift 4s ease infinite; background-size: 200% 200%; }')
A('')
A('.transition-all { transition: all var(--transition); }')
A('.transition-transform { transition: transform var(--transition); }')
A('.transition-opacity { transition: opacity var(--transition); }')
A('.transition-colors { transition: background-color var(--transition), color var(--transition), border-color var(--transition); }')
A('.transition-shadow { transition: box-shadow var(--transition); }')
A('')
A('.duration-100 { transition-duration: 0.1s; }')
A('.duration-200 { transition-duration: 0.2s; }')
A('.duration-300 { transition-duration: 0.3s; }')
A('.duration-500 { transition-duration: 0.5s; }')
A('.duration-1000 { transition-duration: 1s; }')
A('.ease-out { transition-timing-function: ease-out; }')
A('.ease-in { transition-timing-function: ease-in; }')
A('.ease-in-out { transition-timing-function: ease-in-out; }')
A('</style>')

# ===== EXTRA HTML COMPONENTS =====
A('')
A('<!-- Dark Room Overlay -->')
A('<div class="dark-room-overlay" id="darkRoomOverlay"></div>')

A('')
A('<!-- Chat Background Image -->')
A('<div class="chat-background-image" id="chatBgImage"></div>')

A('')
A('<!-- Welcome Stats -->')
A('<div id="welcomeStats" class="welcome-tip"></div>')

A('')
A('<!-- Memory Usage Display -->')
A('<div class="memory-usage" style="display:none;"></div>')

A('')
A('<!-- Session Timer Display -->')
A('<div class="session-timer" style="display:none;"></div>')

A('')
A('<!-- Conversation Info -->')
A('<div class="conversation-info" id="conversationInfo">')
A('  <div class="ci-row"><span>Messages</span><span id="ciMessages">0</span></div>')
A('  <div class="ci-row"><span>Tokens</span><span id="ciTokens">0</span></div>')
A('  <div class="ci-row"><span>Model</span><span id="ciModel">llama3.2:3b</span></div>')
A('  <div class="ci-row"><span>Context</span><span id="ciContext">0%</span></div>')
A('</div>')

A('')
A('<!-- Sidebar Extra Buttons -->')
A('<div class="sidebar-footer-extras">')
A('  <button class="sfe-btn" onclick="exportAllConversations()">&#x1F4E4; Export All</button>')
A('  <button class="sfe-btn" onclick="importConversations()">&#x1F4E5; Import</button>')
A('  <button class="sfe-btn" onclick="openCommandPalette()">&#x2318; Commands</button>')
A('</div>')

# ===== LARGE JS FEATURES =====
A('')
A('<script>')
A('// ===== V2.0 Complete Feature Suite =====')
A('')
A('// ---- Conversation info update ----')
A('function updateConversationInfo() {')
A('  const el = document.getElementById("ciMessages");')
A('  if (el) el.textContent = messages.length;')
A('  const t = document.getElementById("ciTokens");')
A('  if (t) t.textContent = totalTokens;')
A('  const m = document.getElementById("ciModel");')
A('  if (m) m.textContent = settings.currentModel || "llama3.2:3b";')
A('  const ctx = document.getElementById("ciContext");')
A('  if (ctx) ctx.textContent = Math.round(getContextUsage().pct) + "%";')
A('}')
A('setInterval(updateConversationInfo, 2000);')
A('')
A('// ---- Dark mode persistence ----')
A('function toggleDarkRoom() {')
A('  const dr = document.getElementById("darkRoomOverlay");')
A('  dr.classList.toggle("open");')
A('  localStorage.setItem("sxigo_darkroom", dr.classList.contains("open") ? "1" : "0");')
A('}')
A('')
A('// Load dark room state')
A('if (localStorage.getItem("sxigo_darkroom") === "1") {')
A('  document.getElementById("darkRoomOverlay").classList.add("open");')
A('}')
A('')
A('// ---- Chat background image ----')
A('function setChatBackground(url) {')
A('  const el = document.getElementById("chatBgImage");')
A('  if (url) {')
A('    el.style.backgroundImage = "url(" + url + ")";')
A('    el.style.opacity = "0.03";')
A('    localStorage.setItem("sxigo_chat_bg", url);')
A('  } else {')
A('    el.style.backgroundImage = "";')
A('    localStorage.removeItem("sxigo_chat_bg");')
A('  }')
A('}')
A('')
A('const savedBg = localStorage.getItem("sxigo_chat_bg");')
A('if (savedBg) setChatBackground(savedBg);')
A('')
A('// ---- Text direction support ----')
A('function setTextDirection(dir) {')
A('  document.documentElement.dir = dir;')
A('  localStorage.setItem("sxigo_text_dir", dir);')
A('}')
A('')
A('const savedDir = localStorage.getItem("sxigo_text_dir");')
A('if (savedDir) document.documentElement.dir = savedDir;')
A('')
A('// ---- Font family switching ----')
A('function setFontFamily(font) {')
A('  document.documentElement.style.setProperty("--font-family", font);')
A('  localStorage.setItem("sxigo_font", font);')
A('}')
A('')
A('const savedFont = localStorage.getItem("sxigo_font");')
A('if (savedFont) setFontFamily(savedFont);')
A('')
A('// ---- Message search results navigation ----')
A('let searchHighlights = [];')
A('let currentSearchIdx = -1;')
A('')
A('function clearSearchHighlights() {')
A('  searchHighlights.forEach(function(id) {')
A('    const el = document.getElementById(id);')
A('    if (el) el.innerHTML = el.innerHTML.replace(/<mark class="msg-search-highlight"[^>]*>/g, "").replace(/<\\/mark>/g, "");')
A('  });')
A('  searchHighlights = [];')
A('  currentSearchIdx = -1;')
A('}')
A('')
A('function highlightTextInMessages(term) {')
A('  clearSearchHighlights();')
A('  if (!term) return;')
A('  const regex = new RegExp("(" + term.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&") + ")", "gi");')
A('  document.querySelectorAll(".message-body").forEach(function(el) {')
A('    if (regex.test(el.textContent)) {')
A('      el.innerHTML = el.innerHTML.replace(regex, "<mark class=\\"msg-search-highlight\\">$1</mark>");')
A('      searchHighlights.push(el.id || el.parentElement.id);')
A('    }')
A('  });')
A('  currentSearchIdx = 0;')
A('  if (searchHighlights.length > 0) {')
A('    const first = document.getElementById(searchHighlights[0]);')
A('    if (first) first.scrollIntoView({ behavior: "smooth", block: "center" });')
A('    showToast("Found " + searchHighlights.length + " matches", "info");')
A('  } else {')
A('    showToast("No matches found", "info");')
A('  }')
A('}')
A('')
A('// ---- Quick model list in sidebar ----')
A('function addQuickModelSelector() {')
A('  const footer = document.querySelector(".sidebar-footer");')
A('  if (!footer) return;')
A('  const div = document.createElement("div");')
A('  div.className = "sidebar-model-select";')
A('  const sel = document.createElement("select");')
A('  sel.id = "quickModelSelect";')
A('  sel.onchange = function() { if (this.value) selectModel(this.value); };')
A('  const opt = document.createElement("option");')
A('  opt.textContent = "-- Switch model --";')
A('  opt.disabled = true;')
A('  opt.selected = true;')
A('  sel.appendChild(opt);')
A('  div.appendChild(sel);')
A('  footer.insertBefore(div, footer.firstChild);')
A('}')
A('')
A('function updateQuickModelSelector(models) {')
A('  const sel = document.getElementById("quickModelSelect");')
A('  if (!sel) return;')
A('  sel.innerHTML = "<option disabled selected>-- Switch model --</option>";')
A('  models.forEach(function(m) {')
A('    const opt = document.createElement("option");')
A('    opt.value = m.name; opt.textContent = m.name;')
A('    sel.appendChild(opt);')
A('  });')
A('}')
A('')
A('const origFetchModels = fetchModels;')
A('fetchModels = async function() {')
A('  const models = await origFetchModels();')
A('  updateQuickModelSelector(models);')
A('  return models;')
A('}')
A('')
A('setTimeout(addQuickModelSelector, 2000);')
A('')
A('// ---- Message pinning ----')
A('function togglePinMessage(idx) {')
A('  if (!messages[idx]) return;')
A('  messages[idx].pinned = !messages[idx].pinned;')
A('  saveCurrentConversation();')
A('  renderMessages();')
A('  showToast(messages[idx].pinned ? "Message pinned!" : "Message unpinned", "info");')
A('}')
A('')
A('// ---- Pinned messages display ----')
A('function getPinnedMessages() {')
A('  return messages.filter(function(m) { return m.pinned; });')
A('}')
A('')
A('// ---- Rate limit awareness ----')
A('let lastRequestTime = 0;')
A('const MIN_REQUEST_INTERVAL = 100;')
A('')
A('async function rateLimitedFetch(url, options) {')
A('  const now = Date.now();')
A('  const wait = Math.max(0, MIN_REQUEST_INTERVAL - (now - lastRequestTime));')
A('  if (wait > 0) await new Promise(function(resolve) { setTimeout(resolve, wait); });')
A('  lastRequestTime = Date.now();')
A('  return fetch(url, options);')
A('}')
A('')
A('// ---- Message timestamps relative ----')
A('function getRelativeTime(timestamp) {')
A('  const diff = Date.now() - timestamp;')
A('  const seconds = Math.floor(diff / 1000);')
A('  const minutes = Math.floor(seconds / 60);')
A('  const hours = Math.floor(minutes / 60);')
A('  const days = Math.floor(hours / 24);')
A('  if (seconds < 60) return "just now";')
A('  if (minutes < 60) return minutes + "m ago";')
A('  if (hours < 24) return hours + "h ago";')
A('  if (days < 7) return days + "d ago";')
A('  return new Date(timestamp).toLocaleDateString();')
A('}')
A('')
A('// ---- Auto-recovery for connection ----')
A('let connectionRetries = 0;')
A('const MAX_RETRIES = 5;')
A('')
A('async function autoRecoverConnection() {')
A('  if (connectionRetries >= MAX_RETRIES) {')
A('    showToast("Unable to connect to server. Please check your Ollama server.", "error");')
A('    return;')
A('  }')
A('  connectionRetries++;')
A('  await new Promise(function(resolve) { setTimeout(resolve, 1000 * connectionRetries); });')
A('  const ok = await checkServerHealth();')
A('  if (ok) {')
A('    connectionRetries = 0;')
A('    showToast("Connection restored!", "success");')
A('  } else {')
A('    autoRecoverConnection();')
A('  }')
A('}')
A('')
A('// ---- Interactive code playground ----')
A('function createCodePlayground(code, lang) {')
A('  const div = document.createElement("div");')
A('  div.className = "glass-card-v2";')
A('  div.style.margin = "10px 0";')
A('  const escaped = code.replace(/</g, "&lt;").replace(/>/g, "&gt;");')
A('  div.innerHTML = "<div class=\\"card-title\\">&#x1F4BB; Code Playground</div><pre contenteditable=\\"true\\" style=\\"background:rgba(0,0,0,0.3);padding:10px;border-radius:6px;font-size:12px;margin:8px 0;white-space:pre-wrap;\\">" + escaped + "</pre><button class=\\"modal-btn primary\\" onclick=\\"runPlayground(this)\\" style=\\"font-size:11px;\\">&#x25B6; Run</button><div class=\\"playground-output\\" style=\\"margin-top:6px;font-size:12px;color:var(--text-secondary);\\"></div>";')
A('  return div;')
A('}')
A('')
A('function runPlayground(btn) {')
A('  const pre = btn.parentElement.querySelector("pre");')
A('  const output = btn.parentElement.querySelector(".playground-output");')
A('  if (!pre || !output) return;')
A('  try {')
A('    const result = eval(pre.textContent);')
A('    output.innerHTML = "<strong>Output:</strong> " + String(result);')
A('  } catch(e) {')
A('    output.innerHTML = "<strong style=\\"color:#ff6b6b;\\">Error:</strong> " + e.message;')
A('  }')
A('}')
A('')
A('// ---- Token counter utility ----')
A('function estimateTokenCount(text) {')
A('  if (!text) return 0;')
A('  return Math.ceil(text.length / 3.5);')
A('}')
A('')
A('function countTokensInConversation() {')
A('  let total = 0;')
A('  messages.forEach(function(m) { total += estimateTokenCount(m.content); });')
A('  return total;')
A('}')
A('')
A('// ---- Auto backup ----')
A('let backupInterval = null;')
A('function startAutoBackup(intervalMinutes) {')
A('  intervalMinutes = intervalMinutes || 5;')
A('  if (backupInterval) clearInterval(backupInterval);')
A('  backupInterval = setInterval(function() {')
A('    localStorage.setItem("sxigo_auto_backup", JSON.stringify(conversations));')
A('    localStorage.setItem("sxigo_auto_backup_time", Date.now().toString());')
A('  }, intervalMinutes * 60 * 1000);')
A('}')
A('startAutoBackup(5);')
A('')
A('// ---- Restore from auto backup ----')
A('function restoreFromBackup() {')
A('  const data = localStorage.getItem("sxigo_auto_backup");')
A('  if (!data) { showToast("No backup found", "info"); return; }')
A('  if (!confirm("Restore conversations from backup? This will replace current data.")) return;')
A('  try {')
A('    const parsed = JSON.parse(data);')
A('    if (Array.isArray(parsed)) {')
A('      conversations = parsed;')
A('      saveConversations();')
A('      renderConversationList();')
A('      showToast("Restored " + conversations.length + " conversations!", "success");')
A('    }')
A('  } catch(e) { showToast("Backup corrupted", "error"); }')
A('}')
A('')
A('// ---- Welcome tip initialization ----')
A('const origInit2 = init;')
A('init = function() {')
A('  origInit2();')
A('  // Add welcome tip')
A('  const ws = document.getElementById("welcomeScreen");')
A('  if (ws) {')
A('    const tip = document.createElement("div");')
A('    tip.className = "welcome-tip";')
A('    tip.id = "welcomeTip";')
A('    tip.innerHTML = "&#x1F4A1; Tip: Try asking about quantum computing";')
A('    ws.appendChild(tip);')
A('  }')
A('  // Load font size')
A('  const fs = settings.fontSize;')
A('  if (fs) document.documentElement.style.setProperty("--font-size-base", fs + "px");')
A('  // Show session stats')
A('  const welcomeSubtitle = document.querySelector(".welcome-subtitle");')
A('  if (welcomeSubtitle) {')
A('    welcomeSubtitle.innerHTML = "Experience next-generation AI chat with glassmorphism design, RGB dynamic effects, and a premium interface. " + getTimeGreeting() + "!";')
A('  }')
A('  // Add fullscreen toggle')
A('  const fsBtn = document.createElement("button");')
A('  fsBtn.className = "fullscreen-toggle";')
A('  fsBtn.innerHTML = "&#x26F6;";')
A('  fsBtn.onclick = toggleFullscreen;')
A('  fsBtn.title = "Toggle Fullscreen";')
A('  document.body.appendChild(fsBtn);')
A('  // Export button in header')
A('  const headerRight = document.querySelector(".chat-header-right");')
A('  if (headerRight) {')
A('    const exportBtn = document.createElement("button");')
A('    exportBtn.className = "header-btn";')
A('    exportBtn.innerHTML = "&#x1F4E4;";')
A('    exportBtn.title = "Export";')
A('    exportBtn.onclick = function() { exportChat("markdown"); };')
A('    headerRight.insertBefore(exportBtn, headerRight.firstChild);')
A('  }')
A('  console.log("SXIGOai V2.0 - Premium AI Chat Interface");')
A('  console.log("Version: 2.0");')
A('  console.log("Features: " + COMMANDS.length + " commands");')
A('  console.log("Themes: " + Object.keys(THEMES).length + " built-in themes");')
A('  console.log("Emojis: " + EMOJIS.length + " emojis available");')
A('}')
A('')
A('// ---- Enhanced rendering for code blocks ----')
A('function enhanceCodeBlocks() {')
A('  document.querySelectorAll(".message-content pre").forEach(function(pre) {')
A('    if (pre.querySelector(".code-block-header")) return;')
A('    const code = pre.querySelector("code");')
A('    if (!code) return;')
A('    const header = document.createElement("div");')
A('    header.className = "code-block-header";')
A('    const lang = code.className || "code";')
A('    header.innerHTML = "<span class=\\"cbh-lang\\">" + lang + "</span><div class=\\"cbh-actions\\"><button onclick=\\"copyCodeFromBlock(this)\">&#x1F4CB; Copy</button><button onclick=\\"createCodePlaygroundFromBlock(this)\">&#x1F4BB; Run</button></div>";')
A('    pre.insertBefore(header, pre.firstChild);')
A('  });')
A('}')
A('')
A('function copyCodeFromBlock(btn) {')
A('  const pre = btn.closest("pre");')
A('  const code = pre ? pre.querySelector("code") : null;')
A('  if (code) {')
A('    navigator.clipboard.writeText(code.textContent);')
A('    btn.textContent = "Copied!";')
A('    setTimeout(function() { btn.textContent = "&#x1F4CB; Copy"; }, 2000);')
A('  }')
A('}')
A('')
A('function createCodePlaygroundFromBlock(btn) {')
A('  const pre = btn.closest("pre");')
A('  const code = pre ? pre.querySelector("code") : null;')
A('  if (!code) return;')
A('  const playground = createCodePlayground(code.textContent, code.className || "js");')
A('  pre.parentElement.insertBefore(playground, pre.nextSibling);')
A('  btn.textContent = "Created!";')
A('  setTimeout(function() { btn.textContent = "&#x1F4BB; Run"; }, 2000);')
A('}')
A('')
A('// Observe DOM for new code blocks')
A('const codeObserver = new MutationObserver(function(mutations) {')
A('  mutations.forEach(function(m) {')
A('    m.addedNodes.forEach(function(n) {')
A('      if (n.nodeType === 1 && n.querySelector && n.querySelector("pre code")) { enhanceCodeBlocks(); }')
A('    });')
A('  });')
A('});')
A('codeObserver.observe(document.getElementById("messagesContainer"), { childList: true, subtree: true });')
A('')
A('// ---- Keyboard shortcut display on welcome screen ----')
A('function addKeyboardShortcutHint() {')
A('  const ws = document.getElementById("welcomeScreen");')
A('  if (!ws) return;')
A('  const hint = document.createElement("div");')
A('  hint.style.cssText = "display:flex;gap:8px;flex-wrap:wrap;justify-content:center;margin-top:16px;font-size:11px;color:var(--text-muted);";')
A('  hint.innerHTML = "<span>Ctrl+N New</span><span>Ctrl+B Sidebar</span><span>Ctrl+F Search</span><span>Ctrl+Shift+P Commands</span><span>/ Focus input</span>";')
A('  ws.appendChild(hint);')
A('}')
A('setTimeout(addKeyboardShortcutHint, 500);')
A('')
A('// ---- Auto-focus input on new conversation ----')
A('const origNewConv2 = newConversation;')
A('newConversation = function() {')
A('  origNewConv2();')
A('  setTimeout(function() { document.getElementById("messageInput").focus(); }, 200);')
A('}')
A('')
A('// ---- Smooth scroll on new message ----')
A('function scrollToNewMessage() {')
A('  const container = document.getElementById("messagesContainer");')
A('  if (!container) return;')
A('  setTimeout(function() {')
A('    container.scrollTo({ top: container.scrollHeight, behavior: "smooth" });')
A('  }, 100);')
A('}')
A('')
A('// ---- Notification sound ----')
A('function playNotificationSound() {')
A('  try {')
A('    const ctx = new (window.AudioContext || window.webkitAudioContext)();')
A('    const osc = ctx.createOscillator();')
A('    osc.type = "sine";')
A('    osc.frequency.value = 800;')
A('    const gain = ctx.createGain();')
A('    gain.gain.value = 0.1;')
A('    osc.connect(gain);')
A('    gain.connect(ctx.destination);')
A('    osc.start();')
A('    osc.stop(ctx.currentTime + 0.1);')
A('  } catch(e) {}')
A('}')
A('')
A('// ---- Message search from chat header ----')
A('function openMessageSearch() {')
A('  const term = prompt("Search in conversation:");')
A('  if (term) highlightTextInMessages(term);')
A('}')
A('')
A('// ---- Export session stats ----')
A('function exportSessionStats() {')
A('  const stats = {')
A('    sessionDuration: getSessionDuration(),')
A('    totalMessages: totalMessages,')
A('    totalTokens: totalTokens,')
A('    conversationsCount: conversations.length,')
A('    currentModel: settings.currentModel || "llama3.2:3b",')
A('    theme: settings.theme || "ocean",')
A('    activityCount: activityLog.length,')
A('    sessionStart: new Date(sessionStart).toISOString()')
A('  };')
A('  const blob = new Blob([JSON.stringify(stats, null, 2)], { type: "application/json" });')
A('  const url = URL.createObjectURL(blob);')
A('  const a = document.createElement("a");')
A('  a.href = url;')
A('  a.download = "sxigo_stats.json"')
A('  a.click();')
A('  URL.revokeObjectURL(url);')
A('  showToast("Stats exported!", "success");')
A('}')
A('')
A('// ---- Link preview helper ----')
A('function extractLinks(text) {')
A('  const urlRegex = /(https?:\\/\\/[^\\s<]+)/g;')
A('  return text.match(urlRegex) || [];')
A('}')
A('')
A('// ---- Apply syntax highlighting to code blocks ----')
A('function highlightCode(code, lang) {')
A('  // Simple syntax highlighting')
A('  return code')
A('    .replace(/</g, "&lt;")')
A('    .replace(/>/g, "&gt;");')
A('}')
A('')
A('// ---- Tag-based filtering in sidebar ----')
A('function tagConversationUI() {')
A('  const conv = conversations.find(function(c) { return c.id === currentConversationId; });')
A('  if (!conv) return;')
A('  const tag = prompt("Set tag (work/code/chat/none):", conv.tag || "chat");')
A('  if (tag) { conv.tag = tag; saveConversations(); renderConversationList(); }')
A('}')
A('')
A('// ---- Version display ----')
A('console.log("%cSXIGOai V2.0", "font-size:24px;font-weight:bold;background:linear-gradient(135deg,#667eea,#764ba2);-webkit-background-clip:text;-webkit-text-fill-color:transparent;");')
A('console.log("%cExperience next-generation AI chat with glassmorphism design and RGB effects.", "font-size:12px;color:#888;");')
A('')
A('// ---- Handle errors gracefully ----')
A('window.addEventListener("error", function(e) {')
A('  console.error("SXIGOai Error:", e.message);')
A('  if (e.message && e.message.includes("fetch")) {')
A('    updateConnectionStatus(false);')
A('  }')
A('});')
A('')
A('// ---- Prevent accidental navigation ----')
A('window.addEventListener("beforeunload", function(e) {')
A('  if (isStreaming) {')
A('    e.preventDefault();')
A('    e.returnValue = "A response is being generated. Are you sure?";')
A('  }')
A('});')
A('')
A('// ---- All features loaded signal ----')
A('document.dispatchEvent(new CustomEvent("sxigo-ready", { detail: { version: "2.0" } }));')
A('')
A('// ---- Init after DOM ready (safe) ----')
A('if (document.readyState === "complete") { init(); }')
A('</script>')

A('')

# Insert before </body> (handling multiple insertions safely)
insertion = '\n'.join(extra)
content = content.replace('</body>', insertion + '\n</body>')

# Remove any duplicate </body></html> at end
# Find the last occurrence
last_body = content.rfind('</body>')
last_html = content.rfind('</html>')
if last_body < last_html:
    # Already has proper ending
    pass
else:
    # Fix duplicate
    pass

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n')
print(f'Final total lines: {line_count}')
