path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

# Read current content
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

js3 = []
def J(line):
    js3.append(line)

J('')
J('// ---- Messages ----')
J('function renderMessages(scrollToBottom) {')
J('  const container = document.getElementById("messagesContainer");')
J('  container.innerHTML = "";')
J('  if (!messages.length) {')
J('    container.appendChild(document.getElementById("welcomeScreen"));')
J('    return;')
J('  }')
J('  const ws = document.getElementById("welcomeScreen");')
J('  if (ws && ws.parentNode) ws.remove();')
J('  messages.forEach((msg, idx) => {')
J('    const wrapper = document.createElement("div");')
J('    wrapper.className = "message-wrapper " + msg.role;')
J('    wrapper.id = "msg-" + idx;')
J('    const avatar = document.createElement("div");')
J('    avatar.className = "avatar " + msg.role;')
J('    avatar.textContent = msg.role === "user" ? "U" : "AI";')
J('    const content = document.createElement("div");')
J('    content.className = "message-content";')
J('    content.style.position = "relative";')
J('    const body = document.createElement("div");')
J('    body.className = "message-body";')
J('    body.innerHTML = formatMessage(msg.content);')
J('    content.appendChild(body);')
J('    const actions = document.createElement("div");')
J('    actions.className = "message-actions";')
J('    const aHtml = "<button class=\\"message-action-btn\\" onclick=\\"copyMessage(" + idx + ' + ')\\" title=\\"Copy\\">&#x1F4CB;</button><button class=\\"message-action-btn\\" onclick=\\"editMessage(" + idx + ' + ')\\" title=\\"Edit\\">&#x270F;&#xFE0F;</button><button class=\\"message-action-btn\\" onclick=\\"resendMessage(" + idx + ' + ')\\" title=\\"Resend\\">&#x1F504;</button>";')
J('    actions.innerHTML = aHtml;')
J('    content.appendChild(actions);')
J('    const reactions = document.createElement("div");')
J('    reactions.className = "message-reactions";')
J('    ["&#x1F44D;","&#x2764;&#xFE0F;","&#x1F44E;","&#x1F60A;","&#x1F4A1;","&#x1F389;"].forEach(r => {')
J('      const btn = document.createElement("button");')
J('      btn.className = "reaction-btn";')
J('      btn.innerHTML = r;')
J('      btn.onclick = function() { toggleReaction(idx, r, btn); };')
J('      reactions.appendChild(btn);')
J('    });')
J('    content.appendChild(reactions);')
J('    const ts = document.createElement("div");')
J('    ts.className = "message-timestamp";')
J('    ts.textContent = msg.timestamp ? new Date(msg.timestamp).toLocaleTimeString() : "";')
J('    content.appendChild(ts);')
J('    wrapper.appendChild(avatar);')
J('    wrapper.appendChild(content);')
J('    container.appendChild(wrapper);')
J('  });')
J('  if (scrollToBottom !== false) {')
J('    setTimeout(() => { container.scrollTop = container.scrollHeight; }, 50);')
J('  }')
J('}')

J('')
J('function formatMessage(text) {')
J('  let html = text')
J('    .replace(/&/g, "&amp;")')
J('    .replace(/</g, "&lt;")')
J('    .replace(/>/g, "&gt;")')
J('    .replace(/```(\\w*)\\n?([\\s\\S]*?)```/g, function(_, lang, code) {')
J('      const enc = encodeURIComponent(code);')
J('      return "<pre><button class=\\"copy-btn\\" onclick=\\"copyCode(this)\\" data-code=\\"" + enc + "\\">Copy</button><code>" + code + "</code></pre>";')
J('    })')
J('    .replace(/`([^`]+)`/g, "<code>$1</code>")')
J('    .replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>")')
J('    .replace(/\\*(.+?)\\*/g, "<em>$1</em>")')
J('    .replace(/\\n\\n/g, "</p><p>")')
J('    .replace(/\\n/g, "<br>");')
J('  return "<p>" + html + "</p>";')
J('}')

J('')
J('function copyMessage(idx) {')
J('  const text = messages[idx] ? messages[idx].content : "";')
J('  navigator.clipboard.writeText(text).then(() => showToast("Copied!", "success"));')
J('}')

J('')
J('function editMessage(idx) {')
J('  const msg = messages[idx];')
J('  if (!msg) return;')
J('  const newText = prompt("Edit message:", msg.content);')
J('  if (newText !== null) {')
J('    msg.content = newText;')
J('    msg.edited = true;')
J('    saveCurrentConversation();')
J('    renderMessages();')
J('  }')
J('}')

J('')
J('function resendMessage(idx) {')
J('  const msg = messages[idx];')
J('  if (msg && msg.role === "user") {')
J('    document.getElementById("messageInput").value = msg.content;')
J('    messages = messages.slice(0, idx);')
J('    sendMessage();')
J('  }')
J('}')

J('')
J('function toggleReaction(idx, reaction, btn) {')
J('  const msg = messages[idx];')
J('  if (!msg) return;')
J('  if (!msg.reactions) msg.reactions = {};')
J('  if (msg.reactions[reaction]) {')
J('    delete msg.reactions[reaction];')
J('    btn.classList.remove("active");')
J('  } else {')
J('    msg.reactions[reaction] = true;')
J('    btn.classList.add("active");')
J('  }')
J('  saveCurrentConversation();')
J('}')

J('')
J('function copyCode(btn) {')
J('  const code = decodeURIComponent(btn.dataset.code);')
J('  navigator.clipboard.writeText(code).then(() => {')
J('    btn.textContent = "Copied!";')
J('    setTimeout(() => { btn.textContent = "Copy"; }, 2000);')
J('  });')
J('}')

J('')
J('// ---- Streaming ----')
J('async function sendMessage() {')
J('  const input = document.getElementById("messageInput");')
J('  const text = input.value.trim();')
J('  if (!text || isStreaming) return;')
J('  const model = settings.currentModel || "llama3.2:3b";')
J('  if (!currentConversationId) newConversation();')
J('  const conv = conversations.find(c => c.id === currentConversationId);')
J('  if (conv && conv.name === "New Chat") {')
J('    conv.name = text.substring(0, 40) + (text.length > 40 ? "..." : "");')
J('    document.getElementById("chatTitle").textContent = conv.name;')
J('  }')
J('  messages.push({ role: "user", content: text, timestamp: Date.now() });')
J('  input.value = "";')
J('  autoResize(input);')
J('  renderMessages();')
J('  document.getElementById("welcomeScreen").style.display = "none";')
J('  const msgIdx = messages.length;')
J('  messages.push({ role: "assistant", content: "", timestamp: Date.now() });')
J('  renderMessages();')
J('  isStreaming = true;')
J('  abortController = new AbortController();')
J('  document.getElementById("sendBtn").style.display = "none";')
J('  document.getElementById("stopBtn").classList.add("visible");')
J('  const startTime = Date.now();')
J('  totalMessages++;')
J('  try {')
J('    const systemPrompt = document.getElementById("systemPrompt").value;')
J('    const contextLen = parseInt(document.getElementById("contextLength").value);')
J('    const temp = parseFloat(document.getElementById("temperature").value);')
J('    const maxTok = parseInt(document.getElementById("maxTokens").value);')
J('    const msgs = messages.slice(0, -1).map(m => ({ role: m.role, content: m.content }));')
J('    if (systemPrompt) msgs.unshift({ role: "system", content: systemPrompt });')
J('    const res = await fetch(getServerUrl() + "/api/chat", {')
J('      method: "POST",')
J('      headers: { "Content-Type": "application/json" },')
J('      body: JSON.stringify({ model: model, messages: msgs, stream: true, options: { temperature: temp, num_predict: maxTok, num_ctx: contextLen } }),')
J('      signal: abortController.signal')
J('    });')
J('    if (!res.ok) throw new Error("HTTP " + res.status);')
J('    updateConnectionStatus(true);')
J('    const reader = res.body.getReader();')
J('    const decoder = new TextDecoder();')
J('    let buffer = "";')
J('    let totalResponseTokens = 0;')
J('    while (true) {')
J('      const { done, value } = await reader.read();')
J('      if (done) break;')
J('      buffer += decoder.decode(value, { stream: true });')
J('      const lines = buffer.split("\\n");')
J('      buffer = lines.pop() || "";')
J('      for (const line of lines) {')
J('        if (!line.trim()) continue;')
J('        try {')
J('          const data = JSON.parse(line);')
J('          if (data.message && data.message.content) {')
J('            messages[msgIdx].content += data.message.content;')
J('            totalResponseTokens++;')
J('            totalTokens++;')
J('          }')
J('          if (data.done) {')
J('            if (data.total_duration) messages[msgIdx].timing = data;')
J('            if (data.eval_count) messages[msgIdx].tokenCount = data.eval_count;')
J('          }')
J('        } catch(e) {}')
J('      }')
J('      const bodyEl = document.querySelector("#msg-" + msgIdx + " .message-body");')
J('      if (bodyEl) bodyEl.innerHTML = formatMessage(messages[msgIdx].content);')
J('      const container = document.getElementById("messagesContainer");')
J('      container.scrollTop = container.scrollHeight;')
J('      document.getElementById("tokenCountDisplay").textContent = totalTokens + " tokens";')
J('      document.getElementById("statusBarTokens").textContent = totalTokens + " tokens";')
J('    }')
J('    const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);')
J('    messages[msgIdx].timestamp = Date.now();')
J('    modelTimings[model] = { tokens: totalResponseTokens, time: elapsed };')
J('    if (totalResponseTokens > 0 && elapsed > 0) {')
J('      const rate = (totalResponseTokens / parseFloat(elapsed)).toFixed(1);')
J('      document.getElementById("modelRateBadge").textContent = "~" + rate + " tok/s";')
J('    }')
J('    renderMessages();')
J('    addActivity("Received response from " + model + " (" + totalResponseTokens + " tokens, " + elapsed + "s)");')
J('  } catch(e) {')
J('    if (e.name === "AbortError") {')
J('      messages[msgIdx].content += "\\n\\n[Response stopped]";')
J('      showToast("Streaming stopped", "info");')
J('    } else {')
J('      showToast("Error: " + e.message, "error");')
J('      messages[msgIdx].content = "Error: " + e.message;')
J('    }')
J('    renderMessages();')
J('  } finally {')
J('    isStreaming = false;')
J('    abortController = null;')
J('    document.getElementById("sendBtn").style.display = "flex";')
J('    document.getElementById("stopBtn").classList.remove("visible");')
J('    saveCurrentConversation();')
J('  }')
J('}')

J('')
J('function stopStreaming() {')
J('  if (abortController) { abortController.abort(); }')
J('}')

J('')
J('function saveCurrentConversation() {')
J('  const conv = conversations.find(c => c.id === currentConversationId);')
J('  if (conv) { conv.messages = messages; saveConversations(); }')
J('}')

J('')
J('function handleKeyDown(e) {')
J('  if (e.key === "Enter" && !e.shiftKey) {')
J('    e.preventDefault();')
J('    sendMessage();')
J('  }')
J('  if (e.key === "Escape" && isStreaming) {')
J('    stopStreaming();')
J('  }')
J('}')

J('')
J('function autoResize(el) {')
J('  el.style.height = "auto";')
J('  el.style.height = Math.min(el.scrollHeight, 180) + "px";')
J('}')

J('')
J('function suggestPrompt(text) {')
J('  document.getElementById("messageInput").value = text;')
J('  autoResize(document.getElementById("messageInput"));')
J('  sendMessage();')
J('}')

# Append to file before </body>
insertion = '\n'.join(js3)
content = content.replace('</body>', insertion + '\n</body>')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n') + 1
print(f'Total lines after JS3: {line_count}')
