path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

js4 = []

def J(s):
    js4.append(s)

J('')
J('// ---- Voice Input ----')
J('function toggleVoice() {')
J('  if (!("webkitSpeechRecognition" in window) && !("SpeechRecognition" in window)) {')
J('    showToast("Speech recognition not supported in this browser", "error");')
J('    return;')
J('  }')
J('  if (isRecording) {')
J('    stopVoice();')
J('    return;')
J('  }')
J('  const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;')
J('  recognition = new SpeechRecognition();')
J('  recognition.lang = "en-US";')
J('  recognition.interimResults = true;')
J('  recognition.continuous = false;')
J('  isRecording = true;')
J('  document.getElementById("voiceBtn").classList.add("recording");')
J('  document.getElementById("voiceWave").classList.add("visible");')
J('  recognition.onresult = function(e) {')
J('    const transcript = Array.from(e.results).map(r => r[0].transcript).join("");')
J('    document.getElementById("messageInput").value = transcript;')
J('    autoResize(document.getElementById("messageInput"));')
J('  };')
J('  recognition.onerror = function() {')
J('    stopVoice();')
J('    showToast("Voice recognition error", "error");')
J('  };')
J('  recognition.onend = function() {')
J('    if (isRecording) {')
J('      const input = document.getElementById("messageInput");')
J('      if (input.value.trim()) sendMessage();')
J('      stopVoice();')
J('    }')
J('  };')
J('  recognition.start();')
J('}')
J('')
J('function stopVoice() {')
J('  isRecording = false;')
J('  document.getElementById("voiceBtn").classList.remove("recording");')
J('  document.getElementById("voiceWave").classList.remove("visible");')
J('  if (recognition) { try { recognition.stop(); } catch(e) {} recognition = null; }')
J('}')

J('')
J('// ---- Search Messages ----')
J('function searchMessages() {')
J('  const input = document.getElementById("messageInput");')
J('  const currentText = input.value;')
J('  if (searchResults.length > 0 && searchIndex >= 0) {')
J('    searchIndex++;')
J('    if (searchIndex >= searchResults.length) searchIndex = 0;')
J('    highlightSearch(searchIndex);')
J('    return;')
J('  }')
J('  const term = prompt("Search messages:", "");')
J('  if (!term) return;')
J('  searchResults = [];')
J('  messages.forEach((msg, i) => {')
J('    if (msg.content.toLowerCase().includes(term.toLowerCase())) searchResults.push(i);')
J('  });')
J('  if (searchResults.length === 0) {')
J('    showToast("No results found", "info");')
J('    return;')
J('  }')
J('  searchIndex = 0;')
J('  highlightSearch(0);')
J('  showToast(searchResults.length + " result(s) found. Press Search button to navigate.", "info");')
J('}')
J('')
J('function highlightSearch(idx) {')
J('  document.querySelectorAll(".message-wrapper").forEach(el => el.style.outline = "none");')
J('  const el = document.getElementById("msg-" + searchResults[idx]);')
J('  if (el) {')
J('    el.style.outline = "2px solid var(--accent-5)";')
J('    el.style.outlineOffset = "2px";')
J('    el.scrollIntoView({ behavior: "smooth", block: "center" });')
J('  }')
J('}')

J('')
J('// ---- Notifications ----')
J('function addNotification(title, body) {')
J('  notifCount++;')
J('  document.getElementById("notifBadge").textContent = notifCount;')
J('  document.getElementById("headerNotifBadge").textContent = notifCount;')
J('  const list = document.getElementById("notifList");')
J('  if (list) {')
J('    const empty = list.querySelector(".notif-empty");')
J('    if (empty) empty.remove();')
J('    const item = document.createElement("div");')
J('    item.className = "notif-item";')
J('    item.innerHTML = "<div class=\\"notif-icon\\">&#x1F514;</div><div class=\\"notif-body\\"><div class=\\"notif-title\\">" + title + "</div><div>" + body + "</div><div class=\\"notif-time\\">" + new Date().toLocaleTimeString() + "</div></div>";')
J('    list.prepend(item);')
J('  }')
J('}')
J('')
J('function clearNotifications() {')
J('  notifCount = 0;')
J('  document.getElementById("notifBadge").textContent = "0";')
J('  document.getElementById("headerNotifBadge").textContent = "0";')
J('  document.getElementById("notifList").innerHTML = "<div class=\\"notif-empty\\">&#x1F4AC; No notifications yet</div>";')
J('}')
J('')
J('function toggleNotifications() {')
J('  document.getElementById("notificationPanel").classList.toggle("open");')
J('}')
J('')
J('function openNotifications() { toggleNotifications(); }')

J('')
J('// ---- Settings Panel ----')
J('function openSettings() {')
J('  document.getElementById("settingsPanel").classList.add("open");')
J('  document.getElementById("settingsOverlay").classList.add("open");')
J('  buildThemeGrid();')
J('  updateServerStatus();')
J('  fetchModels();')
J('}')
J('')
J('function closeSettings() {')
J('  document.getElementById("settingsPanel").classList.remove("open");')
J('  document.getElementById("settingsOverlay").classList.remove("open");')
J('}')

J('')
J('// ---- Modals ----')
J('function openPullModel() {')
J('  document.getElementById("pullModelOverlay").classList.add("open");')
J('  document.getElementById("pullModelName").focus();')
J('}')
J('function closePullModel() {')
J('  document.getElementById("pullModelOverlay").classList.remove("open");')
J('  document.getElementById("pullProgress").classList.remove("visible");')
J('}')
J('')
J('function setPullPreset(name) {')
J('  document.getElementById("pullModelName").value = name;')
J('}')
J('')
J('async function startPull() {')
J('  const name = document.getElementById("pullModelName").value.trim();')
J('  if (!name) { showToast("Enter a model name", "error"); return; }')
J('  const progress = document.getElementById("pullProgress");')
J('  const fill = document.getElementById("pullProgressFill");')
J('  const text = document.getElementById("pullProgressText");')
J('  progress.classList.add("visible");')
J('  fill.style.width = "0%";')
J('  text.textContent = "Starting pull of " + name + "...";')
J('  document.getElementById("pullStartBtn").disabled = true;')
J('  try {')
J('    const res = await fetch(getServerUrl() + "/api/pull", {')
J('      method: "POST",')
J('      headers: { "Content-Type": "application/json" },')
J('      body: JSON.stringify({ name: name, stream: true })')
J('    });')
J('    if (!res.ok) throw new Error("HTTP " + res.status);')
J('    const reader = res.body.getReader();')
J('    const decoder = new TextDecoder();')
J('    let buffer = "";')
J('    while (true) {')
J('      const { done, value } = await reader.read();')
J('      if (done) break;')
J('      buffer += decoder.decode(value, { stream: true });')
J('      const lines = buffer.split("\\n");')
J('      buffer = lines.pop() || "";')
J('      for (const line of lines) {')
J('        if (!line.trim()) continue;')
J('        try {')
J('          const data = JSON.parse(line);')
J('          if (data.status) text.textContent = data.status;')
J('          if (data.completed && data.total) {')
J('            const pct = Math.round((data.completed / data.total) * 100);')
J('            fill.style.width = pct + "%";')
J('          }')
J('          if (data.digest) text.textContent = "Pulling layer...";')
J('        } catch(e) {}')
J('      }')
J('    }')
J('    fill.style.width = "100%";')
J('    text.textContent = "Pull complete!";')
J('    showToast("Model " + name + " pulled successfully!", "success");')
J('    await fetchModels();')
J('    setTimeout(closePullModel, 1500);')
J('  } catch(e) {')
J('    text.textContent = "Error: " + e.message;')
J('    showToast("Pull failed: " + e.message, "error");')
J('  } finally {')
J('    document.getElementById("pullStartBtn").disabled = false;')
J('  }')
J('}')

J('')
J('function openShortcuts() { document.getElementById("shortcutsOverlay").classList.add("open"); }')
J('function closeShortcuts() { document.getElementById("shortcutsOverlay").classList.remove("open"); }')
J('function openAbout() { document.getElementById("aboutOverlay").classList.add("open"); }')
J('function closeAbout() { document.getElementById("aboutOverlay").classList.remove("open"); }')

J('')
J('// ---- Dashboard ----')
J('function openDashboard() {')
J('  document.getElementById("dashboardOverlay").classList.add("open");')
J('  const now = Date.now();')
J('  const elapsed = Math.floor((now - sessionStart) / 1000);')
J('  const hrs = Math.floor(elapsed / 3600);')
J('  const mins = Math.floor((elapsed % 3600) / 60);')
J('  document.getElementById("dashSessions").textContent = hrs + "h " + mins + "m";')
J('  document.getElementById("dashMessages").textContent = totalMessages;')
J('  document.getElementById("dashConversations").textContent = conversations.length;')
J('  document.getElementById("dashTokens").textContent = totalTokens;')
J('  fetchModels().then(models => {')
J('    document.getElementById("dashModels").textContent = models.length;')
J('  });')
J('  // Avg response time')
J('  const times = Object.values(modelTimings).map(t => parseFloat(t.time)).filter(t => t > 0);')
J('  if (times.length > 0) {')
J('    const avg = (times.reduce((a,b) => a+b, 0) / times.length).toFixed(1);')
J('    document.getElementById("dashAvgResponse").textContent = avg + "s";')
J('  }')
J('  updateActivityList();')
J('}')
J('')
J('function closeDashboard() { document.getElementById("dashboardOverlay").classList.remove("open"); }')

J('')
J('// ---- Compare ----')
J('function openCompare() {')
J('  document.getElementById("compareView").classList.add("open");')
J('  document.getElementById("comparePaneA").innerHTML = "Select a model and send a prompt to compare responses.";')
J('  document.getElementById("comparePaneB").innerHTML = "Select a model and send a prompt to compare responses.";')
J('  fetchModels();')
J('}')
J('function closeCompare() { document.getElementById("compareView").classList.remove("open"); }')

J('')
J('// ---- File Attach ----')
J('let attachedFiles = [];')
J('function handleFiles(files) {')
J('  for (const f of files) {')
J('    if (f.size > 10 * 1024 * 1024) {')
J('      showToast("File too large (max 10MB): " + f.name, "error");')
J('      continue;')
J('    }')
J('    attachedFiles.push(f);')
J('  }')
J('  renderAttachments();')
J('}')
J('')
J('function renderAttachments() {')
J('  const bar = document.getElementById("attachPreviewBar");')
J('  bar.innerHTML = "";')
J('  attachedFiles.forEach((f, i) => {')
J('    const chip = document.createElement("div");')
J('    chip.className = "attach-chip";')
J('    chip.innerHTML = "&#x1F4CE; " + f.name + " <button class=\\"remove-attach-chip\\" onclick=\\"removeAttachment(' + ' + i + ' + ')\">&#x2716;</button>";')
J('    bar.appendChild(chip);')
J('  });')
J('}')
J('')
J('function removeAttachment(i) {')
J('  attachedFiles.splice(i, 1);')
J('  renderAttachments();')
J('}')

J('')
J('// ---- Activity Log ----')
J('function addActivity(text) {')
J('  activityLog.push({ text: text, time: Date.now() });')
J('  if (activityLog.length > 200) activityLog.shift();')
J('}')
J('')
J('function updateActivityList() {')
J('  const list = document.getElementById("activityList");')
J('  if (!list) return;')
J('  list.innerHTML = "";')
J('  const recent = activityLog.slice(-20).reverse();')
J('  recent.forEach(a => {')
J('    const div = document.createElement("div");')
J('    div.className = "activity-item";')
J('    div.innerHTML = "<span class=\\"activity-time\\">" + new Date(a.time).toLocaleTimeString() + "</span><span class=\\"activity-text\\">" + a.text + "</span>";')
J('    list.appendChild(div);')
J('  });')
J('  // Also update settings activity log')
J('  const log = document.getElementById("activityLog");')
J('  if (log) {')
J('    log.innerHTML = "";')
J('    activityLog.slice(-30).reverse().forEach(a => {')
J('      log.innerHTML += "<div class=\\"activity-item\\"><span class=\\"activity-time\\">" + new Date(a.time).toLocaleTimeString() + "</span><span class=\\"activity-text\\">" + a.text + "</span></div>";')
J('    });')
J('  }')
J('}')

J('')
J('// ---- Server Status ----')
J('async function updateServerStatus() {')
J('  const el = document.getElementById("srvStatus");')
J('  const online = await checkServerHealth();')
J('  el.textContent = online ? "Online" : "Offline";')
J('  document.getElementById("srvConnection").innerHTML = online ? "&#x1F7E2; Online" : "&#x1F534; Offline";')
J('}')

J('')
J('// ---- Pull Model name display ----')
J('function updatePullModelDisplay() {}')

J('')
J('// ---- Keyboard shortcuts ----')
J('document.addEventListener("keydown", function(e) {')
J('  if (e.ctrlKey && e.key === "n") { e.preventDefault(); newConversation(); }')
J('  if (e.ctrlKey && e.key === "b") { e.preventDefault(); toggleSidebar(); }')
J('  if (e.ctrlKey && e.key === "f") { e.preventDefault(); searchMessages(); }')
J('  if (e.ctrlKey && e.key === ",") { e.preventDefault(); openSettings(); }')
J('  if (e.ctrlKey && e.key === "p") { e.preventDefault(); openPullModel(); }')
J('  if (e.ctrlKey && e.key === "m") { e.preventDefault(); toggleVoice(); }')
J('  if (e.key === "/" && document.activeElement !== document.getElementById("messageInput")) {')
J('    e.preventDefault(); document.getElementById("messageInput").focus();')
J('  }')
J('})')

J('')
J('// ---- Init ----')
J('function init() {')
J('  loadSettings();')
J('  loadConversations();')
J('  buildThemeGrid();')
J('  checkServerHealth();')
J('  fetchModels();')
J('  // Load custom theme if saved')
J('  try {')
J('    const ct = JSON.parse(localStorage.getItem("sxigo_custom_theme"));')
J('    if (ct) {')
J('      document.getElementById("customPrimary").value = ct.primary;')
J('      document.getElementById("customSecondary").value = ct.secondary;')
J('      document.getElementById("customAccent").value = ct.accent;')
J('      document.getElementById("customBg").value = ct.bg;')
J('    }')
J('  } catch(e) {}')
J('  if (conversations.length > 0) loadConversation(conversations[0].id);')
J('  addActivity("Session started");')
J('  // Periodic health check')
J('  setInterval(checkServerHealth, 30000);')
J('  setInterval(updateServerStatus, 60000);')
J('}')

J('')
J('// ---- Drag and Drop ----')
J('const dropZone = document.getElementById("fileDropZone");')
J('if (dropZone) {')
J('  document.addEventListener("dragenter", function(e) { e.preventDefault(); dropZone.classList.add("drag-over"); });')
J('  document.addEventListener("dragover", function(e) { e.preventDefault(); dropZone.classList.add("drag-over"); });')
J('  document.addEventListener("dragleave", function(e) { e.preventDefault(); dropZone.classList.remove("drag-over"); });')
J('  document.addEventListener("drop", function(e) {')
J('    e.preventDefault(); dropZone.classList.remove("drag-over");')
J('    if (e.dataTransfer.files.length > 0) handleFiles(e.dataTransfer.files);')
J('  });')
J('}')

J('')
J('// ---- Start ----')
J('document.addEventListener("DOMContentLoaded", init);')
J('')
J('</script>')

# Append to file before </body>
insertion = '\n'.join(js4)
content = content.replace('</body>', insertion + '\n</body>')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n') + 1
print(f'Total lines after JS4: {line_count}')
