path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

js2 = []

js2.append('')
js2.append('// ---- API ----')
js2.append('function getServerUrl() { return (settings.serverUrl || "http://localhost:11434").replace(/\\/+$/, ""); }')

js2.append('')
js2.append('async function apiFetch(endpoint, options) {')
js2.append('  const url = getServerUrl() + endpoint;')
js2.append('  const start = Date.now();')
js2.append('  try {')
js2.append('    const res = await fetch(url, { ...options, signal: abortController ? abortController.signal : null });')
js2.append('    const latency = Date.now() - start;')
js2.append('    document.getElementById("statusBarLatency").textContent = latency + "ms";')
js2.append('    document.getElementById("srvLatency").textContent = latency + "ms";')
js2.append('    if (!res.ok) throw new Error("HTTP " + res.status);')
js2.append('    return res;')
js2.append('  } catch(e) {')
js2.append('    if (e.name === "AbortError") throw e;')
js2.append('    updateConnectionStatus(false);')
js2.append('    throw e;')
js2.append('  }')
js2.append('}')

js2.append('')
js2.append('function updateConnectionStatus(online) {')
js2.append('  const el = document.getElementById("connectionQuality");')
js2.append('  const dot = document.getElementById("statusBarDot");')
js2.append('  const srv = document.getElementById("statusBarServer");')
js2.append('  if (online) {')
js2.append('    el.innerHTML = "&#x1F7E2; Connected";')
js2.append('    dot.className = "status-dot online";')
js2.append('    srv.textContent = "Connected";')
js2.append('    document.getElementById("srvStatus").textContent = "Online";')
js2.append('  } else {')
js2.append('    el.innerHTML = "&#x1F534; Disconnected";')
js2.append('    dot.className = "status-dot offline";')
js2.append('    srv.textContent = "Disconnected";')
js2.append('    document.getElementById("srvStatus").textContent = "Offline";')
js2.append('  }')
js2.append('}')

js2.append('')
js2.append('async function checkServerHealth() {')
js2.append('  try {')
js2.append('    const res = await fetch(getServerUrl() + "/api/tags", { signal: AbortSignal.timeout(5000) });')
js2.append('    if (res.ok) { updateConnectionStatus(true); return true; }')
js2.append('  } catch(e) {}')
js2.append('  updateConnectionStatus(false);')
js2.append('  return false;')
js2.append('}')

js2.append('')
js2.append('// ---- Models ----')
js2.append('async function fetchModels() {')
js2.append('  try {')
js2.append('    const res = await apiFetch("/api/tags");')
js2.append('    const data = await res.json();')
js2.append('    const models = data.models || [];')
js2.append('    document.getElementById("srvModels").textContent = models.length;')
js2.append('    document.getElementById("dashModels").textContent = models.length;')
js2.append('    const ml = document.getElementById("modelList");')
js2.append('    ml.innerHTML = "";')
js2.append('    const sel = document.getElementById("compareModelA");')
js2.append('    sel.innerHTML = "";')
js2.append('    const sel2 = document.getElementById("compareModelB");')
js2.append('    sel2.innerHTML = "";')
js2.append('    models.forEach(m => {')
js2.append('      const name = m.name;')
js2.append('      const div = document.createElement("div");')
js2.append('      div.style.cssText = "display:flex;align-items:center;gap:8px;padding:6px 8px;margin:3px 0;border-radius:6px;background:rgba(255,255,255,0.03);border:1px solid var(--glass-border);font-size:12px;cursor:pointer;";')
js2.append('      div.innerHTML = "<span>&#x1F916;</span><strong>" + name + "</strong><span style=\"margin-left:auto;color:var(--text-muted);font-size:10px;\">" + (m.details ? m.details.parameter_size || "" : "") + "</span>";')
js2.append('      div.onclick = function() { selectModel(name); };')
js2.append('      ml.appendChild(div);')
js2.append('      const opt = document.createElement("option");')
js2.append('      opt.value = name; opt.textContent = name;')
js2.append('      sel.appendChild(opt.cloneNode(true));')
js2.append('      sel2.appendChild(opt);')
js2.append('    });')
js2.append('    return models;')
js2.append('  } catch(e) {')
js2.append('    if (e.name !== "AbortError") showToast("Failed to fetch models: " + e.message, "error");')
js2.append('    return [];')
js2.append('  }')
js2.append('}')

js2.append('')
js2.append('function selectModel(name) {')
js2.append('  settings.currentModel = name;')
js2.append('  document.getElementById("modelBadge").textContent = name;')
js2.append('  document.getElementById("modelNameDisplay").textContent = name;')
js2.append('  document.getElementById("statusBarModel").textContent = name;')
js2.append('  saveSettings();')
js2.append('  showToast("Switched to " + name, "success");')
js2.append('}')

js2.append('')
js2.append('async function refreshModels() {')
js2.append('  showToast("Refreshing models...", "info");')
js2.append('  await fetchModels();')
js2.append('  showToast("Models refreshed", "success");')
js2.append('}')

js2.append('')
js2.append('// ---- Conversations ----')
js2.append('function loadConversations() {')
js2.append('  try {')
js2.append('    conversations = JSON.parse(localStorage.getItem("sxigo_conversations") || "[]");')
js2.append('    if (conversations.length === 0) {')
js2.append('      conversations.push({ id: "default", name: "Welcome", messages: [], tag: "chat", createdAt: Date.now() });')
js2.append('    }')
js2.append('  } catch(e) { conversations = []; }')
js2.append('  renderConversationList();')
js2.append('  document.getElementById("dashConversations").textContent = conversations.length;')
js2.append('}')

js2.append('')
js2.append('function saveConversations() {')
js2.append('  localStorage.setItem("sxigo_conversations", JSON.stringify(conversations));')
js2.append('}')

js2.append('')
js2.append('function renderConversationList(filter) {')
js2.append('  const list = document.getElementById("conversationList");')
js2.append('  list.innerHTML = "";')
js2.append('  const searchVal = (document.getElementById("convSearch").value || "").toLowerCase();')
js2.append('  const activeTag = document.querySelector(".tag-chip.active");')
js2.append('  const tag = activeTag ? activeTag.dataset.tag : "all";')
js2.append('  conversations.forEach(c => {')
js2.append('    const name = c.name || "Untitled";')
js2.append('    if (searchVal && !name.toLowerCase().includes(searchVal)) return;')
js2.append('    if (tag === "bookmarked" && !c.bookmarked) return;')
js2.append('    if (tag !== "all" && tag !== "bookmarked" && c.tag !== tag) return;')
js2.append('    const div = document.createElement("div");')
js2.append('    div.className = "conv-item" + (c.id === currentConversationId ? " active" : "");')
js2.append('    const bookmarkStar = c.bookmarked ? "&#x2B50;" : "";')
js2.append('    div.innerHTML = "<div class=\"conv-name\" onclick=\"loadConversation(\'" + c.id + "\')\"><span>&#x1F4AC;</span> " + name + " <span class=\"bookmark-indicator\">" + bookmarkStar + "</span></div><div class=\"conv-actions\"><button class=\"conv-action-btn\" onclick=\"event.stopPropagation();toggleBookmark(\'" + c.id + "\')\" title=\"Bookmark\">&#x2B50;</button><button class=\"conv-action-btn\" onclick=\"event.stopPropagation();renameConversation(\'" + c.id + "\')\" title=\"Rename\">&#x270F;&#xFE0F;</button><button class=\"conv-action-btn\" onclick=\"event.stopPropagation();deleteConversation(\'" + c.id + "\')\" title=\"Delete\">&#x1F5D1;&#xFE0F;</button></div>";')
js2.append('    list.appendChild(div);')
js2.append('  });')
js2.append('}')

js2.append('')
js2.append('function newConversation() {')
js2.append('  const id = "conv_" + Date.now();')
js2.append('  const conv = { id: id, name: "New Chat", messages: [], tag: "chat", createdAt: Date.now() };')
js2.append('  conversations.unshift(conv);')
js2.append('  currentConversationId = id;')
js2.append('  messages = [];')
js2.append('  saveConversations();')
js2.append('  renderConversationList();')
js2.append('  renderMessages();')
js2.append('  document.getElementById("chatTitle").textContent = "New Chat";')
js2.append('  document.getElementById("messageInput").focus();')
js2.append('  addActivity("Created new conversation");')
js2.append('}')

js2.append('')
js2.append('function loadConversation(id) {')
js2.append('  const conv = conversations.find(c => c.id === id);')
js2.append('  if (!conv) return;')
js2.append('  currentConversationId = id;')
js2.append('  messages = conv.messages || [];')
js2.append('  renderConversationList();')
js2.append('  renderMessages();')
js2.append('  document.getElementById("chatTitle").textContent = conv.name;')
js2.append('}')

js2.append('')
js2.append('function deleteConversation(id) {')
js2.append('  if (!confirm("Delete this conversation?")) return;')
js2.append('  conversations = conversations.filter(c => c.id !== id);')
js2.append('  if (currentConversationId === id) {')
js2.append('    currentConversationId = null;')
js2.append('    messages = [];')
js2.append('    if (conversations.length > 0) loadConversation(conversations[0].id);')
js2.append('    else newConversation();')
js2.append('  }')
js2.append('  saveConversations();')
js2.append('  renderConversationList();')
js2.append('}')

js2.append('')
js2.append('function renameConversation(id) {')
js2.append('  const conv = conversations.find(c => c.id === id);')
js2.append('  if (!conv) return;')
js2.append('  const name = prompt("Rename conversation:", conv.name);')
js2.append('  if (name && name.trim()) { conv.name = name.trim(); saveConversations(); renderConversationList(); }')
js2.append('}')

js2.append('')
js2.append('function toggleBookmark(id) {')
js2.append('  const conv = conversations.find(c => c.id === id);')
js2.append('  if (!conv) return;')
js2.append('  conv.bookmarked = !conv.bookmarked;')
js2.append('  saveConversations();')
js2.append('  renderConversationList();')
js2.append('  showToast(conv.bookmarked ? "Bookmarked!" : "Removed bookmark", "info");')
js2.append('}')

js2.append('')
js2.append('function filterConversations(val) { renderConversationList(); }')
js2.append('function filterByTag(tag, el) {')
js2.append('  document.querySelectorAll(".tag-chip").forEach(t => t.classList.remove("active"));')
js2.append('  el.classList.add("active");')
js2.append('  renderConversationList();')
js2.append('}')

js2.append('')
js2.append('// ---- Sidebar ----')
js2.append('function toggleSidebar() {')
js2.append('  document.querySelector(".app-container").classList.toggle("sidebar-open");')
js2.append('  document.getElementById("sidebar").classList.toggle("collapsed");')
js2.append('}')

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

insertion = '\n'.join(js2)
content = content.replace('</body>', insertion + '\n</body>')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

line_count = content.count('\n') + 1
print(f'Total lines after JS2: {line_count}')
