path = r'C:\Users\gamju\AppData\Local\Temp\opencode\SXIGOai.html'

with open(path, 'r', encoding='utf-8-sig') as f:
    lines = f.readlines()

# Remove duplicate first 3 lines (condensed head)
if '<!DOCTYPE html>' in lines[0] and '<html' in lines[1]:
    lines = lines[3:]

# Remove trailing whitespace/empty lines from end
while lines and lines[-1].strip() == '':
    lines.pop()

# Ensure file ends properly
last = lines[-1].strip() if lines else ''
if '</html>' not in last:
    lines.append('</body>\n')
    lines.append('</html>\n')

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print(f'Fixed. Total: {len(lines)} lines')

# Now add JavaScript at the end (before </body>)
js = []
js.append('')
js.append('<script>')
js.append('// ===== SXIGOai V2.0 - Full Application Logic =====')
js.append('// ---- State ----')
js.append('let conversations = [];')
js.append('let currentConversationId = null;')
js.append('let messages = [];')
js.append('let isStreaming = false;')
js.append('let abortController = null;')
js.append('let isRecording = false;')
js.append('let recognition = null;')
js.append('let searchResults = [];')
js.append('let searchIndex = -1;')
js.append('let notifCount = 0;')
js.append('let settings = {};')
js.append('let activityLog = [];')
js.append('let sessionStart = Date.now();')
js.append('let totalTokens = 0;')
js.append('let totalMessages = 0;')
js.append('let modelTimings = {};')
js.append('')
js.append('// ---- Toast System ----')
js.append('function showToast(msg, type) {')
js.append('  type = type || "info";')
js.append('  const c = document.getElementById("toastContainer");')
js.append('  const t = document.createElement("div");')
js.append('  t.className = "toast " + type;')
js.append('  t.textContent = msg;')
js.append('  c.appendChild(t);')
js.append('  setTimeout(() => { t.style.opacity = "0"; t.style.transition = "opacity 0.3s"; setTimeout(() => t.remove(), 300); }, 3000);')
js.append('}')
js.append('')
js.append('// ---- Settings ----')
js.append('function loadSettings() {')
js.append('  try {')
js.append('    const s = JSON.parse(localStorage.getItem("sxigo_settings") || "{}");')
js.append('    settings = s;')
js.append('    if (s.serverUrl) document.getElementById("serverUrl").value = s.serverUrl;')
js.append('    if (s.systemPrompt) document.getElementById("systemPrompt").value = s.systemPrompt;')
js.append('    if (s.contextLength) document.getElementById("contextLength").value = s.contextLength;')
js.append('    if (s.temperature !== undefined) {')
js.append('      document.getElementById("temperature").value = s.temperature;')
js.append('      updateRangeValue(document.getElementById("temperature"), "tempVal");')
js.append('    }')
js.append('    if (s.maxTokens) {')
js.append('      document.getElementById("maxTokens").value = s.maxTokens;')
js.append('      updateRangeValue(document.getElementById("maxTokens"), "maxTokVal");')
js.append('    }')
js.append('    if (s.glassDepth !== undefined) {')
js.append('      document.getElementById("glassDepth").value = s.glassDepth;')
js.append('      updateRangeValue(document.getElementById("glassDepth"), "glassVal");')
js.append('      applyGlassDepth(s.glassDepth);')
js.append('    }')
js.append('    if (s.theme) switchTheme(s.theme);')
js.append('    if (s.fontSize) {')
js.append('      document.documentElement.style.setProperty("--font-size-base", s.fontSize + "px");')
js.append('      document.getElementById("fontSizeLabel").textContent = s.fontSize + "px";')
js.append('    }')
js.append('  } catch(e) {}')
js.append('}')

js.append('')
js.append('function saveSettings() {')
js.append('  const s = {')
js.append('    serverUrl: document.getElementById("serverUrl").value,')
js.append('    systemPrompt: document.getElementById("systemPrompt").value,')
js.append('    contextLength: parseInt(document.getElementById("contextLength").value),')
js.append('    temperature: parseFloat(document.getElementById("temperature").value),')
js.append('    maxTokens: parseInt(document.getElementById("maxTokens").value),')
js.append('    glassDepth: parseFloat(document.getElementById("glassDepth").value),')
js.append('    theme: settings.theme || "ocean",')
js.append('    fontSize: settings.fontSize || 14')
js.append('  };')
js.append('  settings = s;')
js.append('  localStorage.setItem("sxigo_settings", JSON.stringify(s));')
js.append('}')

js.append('')
js.append('function switchSettingsTab(tab, btn) {')
js.append('  document.querySelectorAll(".settings-tab").forEach(t => t.classList.remove("active"));')
js.append('  btn.classList.add("active");')
js.append('  document.querySelectorAll(".settings-section").forEach(s => s.classList.remove("active"));')
js.append('  document.getElementById("settings" + tab.charAt(0).toUpperCase() + tab.slice(1)).classList.add("active");')
js.append('}')

js.append('')
js.append('function updateRangeValue(slider, labelId) {')
js.append('  document.getElementById(labelId).textContent = slider.value;')
js.append('}')

js.append('')
js.append('function adjustFontSize(delta) {')
js.append('  let current = parseInt(settings.fontSize) || 14;')
js.append('  current = Math.max(10, Math.min(24, current + delta));')
js.append('  settings.fontSize = current;')
js.append('  document.documentElement.style.setProperty("--font-size-base", current + "px");')
js.append('  document.getElementById("fontSizeLabel").textContent = current + "px";')
js.append('  saveSettings();')
js.append('}')

js.append('')
js.append('// ---- Theme ----')
js.append('const THEMES = {')
js.append('  ocean: { primary:"#667eea", secondary:"#764ba2", accent:"#4facfe", bg:"#0a0a1a" },')
js.append('  sunset: { primary:"#f093fb", secondary:"#f5576c", accent:"#fca311", bg:"#0d0d1a" },')
js.append('  forest: { primary:"#2ecc71", secondary:"#27ae60", accent:"#1abc9c", bg:"#050d0a" },')
js.append('  neon: { primary:"#00ff87", secondary:"#60efff", accent:"#ff00ff", bg:"#050510" },')
js.append('  midnight: { primary:"#7c3aed", secondary:"#a78bfa", accent:"#6366f1", bg:"#03030f" },')
js.append('  aurora: { primary:"#00b4d8", secondary:"#0077b6", accent:"#90e0ef", bg:"#000814" },')
js.append('  candy: { primary:"#ff6b6b", secondary:"#ffa07a", accent:"#ffd93d", bg:"#0f0a14" },')
js.append('  mono: { primary:"#888", secondary:"#aaa", accent:"#ccc", bg:"#050505" }')
js.append('};')

js.append('')
js.append('function switchTheme(theme) {')
js.append('  if (!THEMES[theme]) return;')
js.append('  const t = THEMES[theme];')
js.append('  document.body.className = "theme-" + theme;')
js.append('  const root = document.documentElement;')
js.append('  root.style.setProperty("--accent-1", t.primary);')
js.append('  root.style.setProperty("--accent-5", t.secondary);')
js.append('  root.style.setProperty("--accent-6", t.accent);')
js.append('  settings.theme = theme;')
js.append('  saveSettings();')
js.append('  // Update theme grid UI')
js.append('  document.querySelectorAll(".theme-option").forEach(o => o.classList.toggle("active", o.dataset.theme === theme));')
js.append('}')

js.append('')
js.append('function applyCustomColors() {')
js.append('  const root = document.documentElement;')
js.append('  root.style.setProperty("--accent-1", document.getElementById("customPrimary").value);')
js.append('  root.style.setProperty("--accent-5", document.getElementById("customSecondary").value);')
js.append('  root.style.setProperty("--accent-6", document.getElementById("customAccent").value);')
js.append('  root.style.setProperty("--bg-primary", document.getElementById("customBg").value);')
js.append('}')

js.append('')
js.append('function saveCustomTheme() {')
js.append('  const ct = {')
js.append('    primary: document.getElementById("customPrimary").value,')
js.append('    secondary: document.getElementById("customSecondary").value,')
js.append('    accent: document.getElementById("customAccent").value,')
js.append('    bg: document.getElementById("customBg").value')
js.append('  };')
js.append('  localStorage.setItem("sxigo_custom_theme", JSON.stringify(ct));')
js.append('  showToast("Custom theme saved!", "success");')
js.append('}')

js.append('')
js.append('function applyGlassDepth(val) {')
js.append('  if (!val) val = document.getElementById("glassDepth").value;')
js.append('  document.documentElement.style.setProperty("--glass-depth", val);')
js.append('}')

js.append('')
js.append('// ---- Theme Grid (populate) ----')
js.append('function buildThemeGrid() {')
js.append('  const g = document.getElementById("themeGrid");')
js.append('  g.innerHTML = "";')
js.append('  for (const [name, colors] of Object.entries(THEMES)) {')
js.append('    const div = document.createElement("div");')
js.append('    div.className = "theme-option" + (settings.theme === name ? " active" : "");')
js.append('    div.dataset.theme = name;')
js.append('    const gradient = "linear-gradient(135deg," + colors.primary + "," + colors.secondary + "," + colors.accent + ")";')
js.append('    div.innerHTML = "<div class=\"theme-preview\" style=\"background:" + gradient + "\"></div>" + name.charAt(0).toUpperCase() + name.slice(1);')
js.append('    div.onclick = function() { switchTheme(name); };')
js.append('    g.appendChild(div);')
js.append('  }')
js.append('}')

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# Insert JS before </body>
insertion = '\n'.join(js)
content = content.replace('</body>', insertion + '\n</body>')

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

# Count lines
line_count = content.count('\n') + 1
print(f'Total lines after JS: {line_count}')
